#!/usr/bin/env python3
# This content is generated by AI (Kiro)
"""Minimal stdio MCP server: the only delegation capability of a native child.

Exposes one `subagent` tool. Each call writes an HMAC-signed request into the
owning run's private request directory and waits for the parent's signed
acknowledgement. The parent applies every policy decision (allowlist,
capability ceiling, limits); this server only authenticates and relays.
Never prints anything but JSON-RPC on stdout.
"""
import hashlib
import hmac
import json
import os
import re
import secrets
import sys
import tempfile
import time

AGENT = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,99}$")


def mac(secret, fields):
    payload = "".join("%d:%s;" % (len(field.encode("utf8")), field) for field in fields)
    return hmac.new(bytes.fromhex(secret), payload.encode("utf8"), hashlib.sha256).hexdigest()


def write(message):
    sys.stdout.write(json.dumps(message) + "\n")
    sys.stdout.flush()


def reply(mid, result):
    write({"jsonrpc": "2.0", "id": mid, "result": result})


def error(mid, code, message):
    write({"jsonrpc": "2.0", "id": mid, "error": {"code": code, "message": message}})


def tool(config):
    agents = config["agents"]
    return {
        "name": "subagent",
        "description": (
            "Delegate one bounded, self-contained task to a parent-managed subagent in its own pane. "
            "Fire-and-forget: this returns only an acknowledgement. The result arrives later as a new "
            "message beginning with 'Nested subagent result'; end your turn after delegating and do not "
            "poll. Nested subagents cannot delegate further and never receive more tools than you have. "
            "Allowed agents: " + ", ".join(agents) + "."
        ),
        "inputSchema": {
            "type": "object",
            "properties": {
                "agent": {"type": "string", "enum": agents},
                "name": {"type": "string", "minLength": 1, "maxLength": 80},
                "task": {"type": "string", "minLength": 1, "maxLength": config["max_task_bytes"]},
            },
            "required": ["agent", "name", "task"],
            "additionalProperties": False,
        },
    }


def text_result(text, is_error):
    return {"content": [{"type": "text", "text": text}], "isError": is_error}


def atomic_write(path, value):
    fd, temp = tempfile.mkstemp(prefix=".request-", dir=os.path.dirname(path))
    try:
        with os.fdopen(fd, "w", encoding="utf8") as stream:
            json.dump(value, stream)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temp, path)
    finally:
        if os.path.exists(temp):
            os.unlink(temp)


def read_response(config, nonce):
    path = os.path.join(config["response_dir"], nonce + ".json")
    try:
        with open(path, encoding="utf8") as stream:
            data = json.load(stream)
    except (OSError, ValueError):
        return None
    if not isinstance(data, dict) or data.get("nonce") != nonce:
        return None
    accepted = data.get("accepted") is True
    text = data.get("text") if isinstance(data.get("text"), str) else ""
    expected = mac(config["secret"], ["1", nonce, "1" if accepted else "0", text])
    if not hmac.compare_digest(expected, str(data.get("mac", ""))):
        return None
    return accepted, text


def call(config, state, arguments):
    agent = arguments.get("agent")
    name = arguments.get("name")
    task = arguments.get("task")
    if not isinstance(agent, str) or agent not in config["agents"] or not AGENT.match(agent):
        return text_result("Rejected: agent must be one of " + ", ".join(config["agents"]) + ".", True)
    if not isinstance(name, str) or not name.strip() or not isinstance(task, str) or not task.strip():
        return text_result("Rejected: name and task must be non-empty strings.", True)
    if len(task.encode("utf8")) > config["max_task_bytes"]:
        return text_result("Rejected: task is too long.", True)
    state["seq"] += 1
    nonce = secrets.token_hex(16)
    request = {
        "version": 1, "run_id": config["run_id"], "nonce": nonce, "seq": state["seq"],
        "pid": os.getpid(), "created_at": int(time.time() * 1000),
        "agent": agent, "name": name.strip()[:80], "task": task,
    }
    request["mac"] = mac(config["secret"], [
        "1", request["run_id"], nonce, str(request["seq"]), str(request["pid"]),
        str(request["created_at"]), request["agent"], request["name"], task,
    ])
    path = os.path.join(config["request_dir"], nonce + ".json")
    atomic_write(path, request)
    deadline = time.time() + config["wait_ms"] / 1000.0
    withdrawn = False
    while True:
        response = read_response(config, nonce)
        if response:
            accepted, text = response
            return text_result(text, not accepted)
        if time.time() >= deadline:
            if withdrawn:
                return text_result("The parent did not acknowledge the claimed request; it may still run. Do not resubmit it.", True)
            try:
                os.rename(path, path + ".withdrawn")
                return text_result("The parent did not acknowledge the request in time; it was withdrawn and will not run.", True)
            except OSError:
                # The parent already claimed it: wait once more for its answer.
                withdrawn = True
                deadline = time.time() + 30
        time.sleep(0.2)


def main(config_path):
    with open(config_path, encoding="utf8") as stream:
        config = json.load(stream)
    state = {"seq": 0}
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            message = json.loads(line)
        except ValueError:
            continue
        if not isinstance(message, dict):
            continue
        method = message.get("method")
        mid = message.get("id")
        params = message.get("params") if isinstance(message.get("params"), dict) else {}
        if method == "initialize":
            version = params.get("protocolVersion") if isinstance(params.get("protocolVersion"), str) else "2025-06-18"
            reply(mid, {"protocolVersion": version, "capabilities": {"tools": {}},
                        "serverInfo": {"name": "pi-subagents", "version": "1"}})
        elif method == "tools/list":
            reply(mid, {"tools": [tool(config)]})
        elif method == "tools/call":
            if params.get("name") != "subagent":
                error(mid, -32602, "unknown tool")
                continue
            arguments = params.get("arguments") if isinstance(params.get("arguments"), dict) else {}
            try:
                reply(mid, call(config, state, arguments))
            except Exception as failure:  # pylint: disable=broad-except
                reply(mid, text_result("Rejected: " + str(failure)[:200], True))
        elif method == "ping":
            reply(mid, {})
        elif mid is not None:
            error(mid, -32601, "method not found")


if __name__ == "__main__":
    main(sys.argv[1])
