// This content is generated by AI (Kiro)
/**
 * Spawn-time harness selection through the public paths: startSubagentRun,
 * the registered `subagent` and `subagent_resume` tools, and the registered
 * `/subagent` command. Native launches drive the offline fixture CLIs through
 * the fake Herdr seam; Pi launches record the real launch command through
 * the same seam and settle through its Pi watch override. No model is
 * contacted and no Herdr resource is created.
 */
import "./isolated-agent-dir.ts";
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const agentDir = process.env.PI_CODING_AGENT_DIR!;
// Pi model defaults that must never reach a native launch. The extension
// reads this durable configuration when its module is evaluated, so it is
// written before the flow harness imports the extension.
const example = JSON.parse(
	readFileSync(new URL("../config.json.example", import.meta.url), "utf8"),
);
mkdirSync(join(agentDir, "herdr-agents"), { recursive: true });
writeFileSync(
	join(agentDir, "herdr-agents", "config.json"),
	JSON.stringify({
		...example,
		models: {
			default: "fake/pi-default",
			agents: { "hs-pi-open": "fake/pi-agent-default" },
		},
	}),
);

const {
	api,
	commands,
	ctxFor,
	registered,
	resultFor,
	resume,
	start,
	testApi,
	useHerdr,
	userMessages,
	waitForMessage,
	writeRole,
} = await import("./native-flow-harness.ts");
const { scratch } = await import("./native-fixtures.ts");
const { appendPersistentTaskEvent } = await import(
	"../pi-extension/subagents/session.ts"
);

writeRole("hs-pi-open", [
	"auto-exit: true",
	"tools: read, bash",
	"thinking: high",
]);
writeRole("hs-pi-pinned", [
	"model: fake/pinned",
	"auto-exit: true",
	"tools: read, bash",
]);
writeRole("hs-pi-persistent", ["persistent: true", "tools: read, bash"]);
writeRole("hs-pi-resume", ["auto-exit: true", "tools: read, bash"]);
writeRole("hs-pi-minimal", [
	"auto-exit: true",
	"tools: read",
	"thinking: minimal",
]);
writeRole("hs-pi-replace", [
	"auto-exit: true",
	"tools: read",
	"system-prompt: replace",
]);
writeRole("hs-pi-writer", ["auto-exit: true", "tools: read, write"]);
writeRole("hs-pi-spawner", [
	"auto-exit: true",
	"tools: read",
	"spawning: true",
]);
writeRole("hs-pi-orchestrator", ["auto-exit: true", "tools: read, subagent"]);
writeRole("hs-pi-unrestricted", ["auto-exit: true"]);
writeRole("hs-pi-skilled", [
	"auto-exit: true",
	"tools: read",
	"skills: hs-missing-skill",
]);
writeRole("hs-pi-hidden", [
	"auto-exit: true",
	"tools: read",
	"disable-model-invocation: true",
]);
writeRole("hs-claude-pinned", [
	"cli: claude",
	"model: opus",
	"auto-exit: true",
	"tools: read, bash",
]);
writeRole("hs-claude-open", [
	"cli: claude",
	"auto-exit: true",
	"tools: read, bash",
]);
writeRole("hs-claude-persistent", [
	"cli: claude",
	"persistent: true",
	"tools: read, bash",
]);
writeRole("hs-kiro-pinned", [
	"cli: kiro",
	"model: kiro-pinned",
	"auto-exit: true",
	"tools: read",
]);
writeRole("hs-delegator", [
	"cli: claude",
	"auto-exit: true",
	"tools: read",
	"spawn-agents: hs-claude-open",
]);

type StartParams = Parameters<typeof testApi.startSubagentRun>[1];

/** The launched Pi child a scripted settlement observes. */
interface PiChild {
	sessionFile: string;
	taskId?: string;
	generationId?: string;
}

/** A scripted settlement for one watched Pi attempt. */
interface PiOutcome {
	exitCode?: number;
	errorMessage?: string;
}

/** A Pi registry with authenticated reasoning models under provider `fake`. */
function piCtx(project: string) {
	const models = [
		"parent",
		"pi-a",
		"pi-b",
		"pinned",
		"pi-default",
		"pi-agent-default",
	].map((id) => ({ provider: "fake", id, reasoning: true }));
	return {
		...ctxFor(project),
		model: { provider: "fake", id: "parent" },
		modelRegistry: {
			find: (provider: string, id: string) =>
				models.find((model) => model.provider === provider && model.id === id),
			getAvailable: () => models,
			hasConfiguredAuth: () => true,
		},
	};
}

/**
 * Record Pi launches through the fake Herdr seam: panes are IDs only and the
 * staged command is captured, never run. Each watched Pi attempt settles with
 * the next scripted outcome.
 */
function usePiRecorder(
	outcomes: Array<(child: PiChild) => PiOutcome> = [() => ({})],
) {
	const events: string[] = [];
	const launched: string[] = [];
	let panes = 0;
	let watched = 0;
	testApi.setNativeTestSeam({
		operations: {
			createPane(name) {
				events.push(`create:${name}`);
				return `pi-pane-${++panes}`;
			},
			createWorktree() {
				throw new Error("unexpected worktree creation");
			},
			async waitForShellReady() {
				events.push("ready");
			},
			runScript(_surface, command, script) {
				events.push("run");
				launched.push(command);
				return script.scriptPath;
			},
			closePane() {},
		},
		terminalAvailable: true,
		piWatch: async (child) => {
			const outcome = outcomes[Math.min(watched++, outcomes.length - 1)];
			return {
				name: child.name,
				task: child.task,
				summary: `Pi fixture result ${watched}`,
				exitCode: 0,
				elapsed: 0,
				sessionFile: child.sessionFile,
				...outcome(child),
			};
		},
	});
	return { events, launched };
}

const subagentTool = () => registered.find((tool) => tool.name === "subagent");

const executeTool = (project: string, params: StartParams) =>
	subagentTool().execute(
		"call",
		params,
		new AbortController().signal,
		() => {},
		ctxFor(project),
	);

/** The text of a tool result's content blocks. */
function textOf(result: { content: Array<{ type: string; text?: string }> }) {
	return result.content.map((block) => block.text ?? "").join("");
}

function fixtureArgs(log: string): string[] {
	return JSON.parse(readFileSync(log, "utf8")).args;
}

describe("harness selection rejects before any Herdr resource", () => {
	it("rejects an unresolved role with an explicit native harness", async () => {
		const project = scratch("hs-unknown");
		const herdr = useHerdr({ log: join(project, "..", "unknown.json") });
		const before = testApi.runningSubagents.size;
		for (const harness of ["claude", "kiro", "pi"] as const)
			for (const launch of [
				() =>
					testApi.startSubagentRun(
						api,
						{ name: "hs-unknown", task: "Task", agent: "hs-nope", harness },
						ctxFor(project),
					),
				() =>
					executeTool(project, {
						name: "hs-unknown",
						task: "Task",
						agent: "hs-nope",
						harness,
					}),
			]) {
				const result = await launch();
				assert.equal(result.details.error, "agent-not-found");
				assert.match(textOf(result), /Agent "hs-nope" was not found/);
			}
		assert.deepEqual(herdr.events, []);
		assert.equal(testApi.runningSubagents.size, before);
	});

	it("rejects a harness without a named role", async () => {
		const project = scratch("hs-bare");
		const herdr = useHerdr({ log: join(project, "..", "bare.json") });
		const result = await executeTool(project, {
			name: "hs-bare",
			task: "Task",
			harness: "claude",
		});
		assert.equal(result.details.error, "harness-requires-agent");
		assert.deepEqual(herdr.events, []);
	});

	it("rejects native spawn-agents projected to Pi", async () => {
		const project = scratch("hs-delegator");
		const herdr = useHerdr({ log: join(project, "..", "delegator.json") });
		const result = await testApi.startSubagentRun(
			api,
			{
				name: "hs-delegator",
				task: "Task",
				agent: "hs-delegator",
				harness: "pi",
				model: "fake/pi-a",
			},
			piCtx(project),
		);
		assert.equal(result.details.error, "harness-projection-unsupported");
		assert.match(textOf(result), /spawn-agents/);
		assert.match(textOf(result), /no equivalent bounded Pi policy/);
		assert.deepEqual(herdr.events, []);
	});

	it("requires an explicit destination model when a pinned role switches harness", async () => {
		const project = scratch("hs-pinned");
		const herdr = useHerdr({ log: join(project, "..", "pinned.json") });
		for (const [agent, harness, pinned] of [
			["hs-pi-pinned", "claude", "fake/pinned"],
			["hs-pi-pinned", "kiro", "fake/pinned"],
			["hs-claude-pinned", "pi", "opus"],
			["hs-claude-pinned", "kiro", "opus"],
			["hs-kiro-pinned", "claude", "kiro-pinned"],
			["hs-kiro-pinned", "pi", "kiro-pinned"],
		] as const) {
			const result = await testApi.startSubagentRun(
				api,
				{ name: `hs-${agent}-${harness}`, task: "Task", agent, harness },
				piCtx(project),
			);
			assert.equal(
				result.details.error,
				"harness-switch-requires-model",
				`${agent} -> ${harness}`,
			);
			assert.ok(
				textOf(result).includes(`pins model "${pinned}"`),
				textOf(result),
			);
		}
		// Selecting the role's own harness is not a switch.
		usePiRecorder();
		const own = await testApi.startSubagentRun(
			api,
			{ name: "hs-own", task: "Task", agent: "hs-pi-pinned", harness: "pi" },
			piCtx(project),
		);
		assert.equal(own.details.status, "started", JSON.stringify(own.content));
		assert.equal(own.details.runtimePlan.model, "fake/pinned");
		await resultFor("hs-own");
		assert.deepEqual(herdr.events, []);
	});

	it("never passes a Pi model ref to a native harness or a native ID to Pi", async () => {
		const project = scratch("hs-namespace");
		const herdr = useHerdr({ log: join(project, "..", "namespace.json") });
		const native = await testApi.startSubagentRun(
			api,
			{
				name: "hs-pi-ref",
				task: "Task",
				agent: "hs-pi-pinned",
				harness: "claude",
				model: "fake/pi-a",
			},
			piCtx(project),
		);
		assert.equal(native.details.error, "native-harness-unsupported");
		assert.match(
			textOf(native),
			/^Error: Role "hs-pi-pinned" cannot be projected from pi to claude: .*Pi provider\/model/,
		);
		assert.deepEqual(herdr.events, []);

		const pi = usePiRecorder();
		await assert.rejects(
			testApi.startSubagentRun(
				api,
				{
					name: "hs-native-id",
					task: "Task",
					agent: "hs-claude-pinned",
					harness: "pi",
					model: "opus",
				},
				piCtx(project),
			),
			/exact authenticated provider\/model-id/,
		);
		assert.deepEqual(pi.events, []);
	});

	it("rejects incompatible tool, thinking, prompt, skill, and delegation projections", async () => {
		const project = scratch("hs-incompatible");
		const herdr = useHerdr({ log: join(project, "..", "incompatible.json") });
		const cases: Array<
			[
				Required<Pick<StartParams, "agent" | "harness">> &
					Pick<StartParams, "thinking">,
				RegExp,
			]
		> = [
			[
				{ agent: "hs-pi-minimal", harness: "claude" },
				/cannot represent thinking level minimal/,
			],
			[
				{ agent: "hs-pi-open", harness: "kiro", thinking: "off" },
				/cannot represent thinking level off/,
			],
			[
				{ agent: "hs-pi-replace", harness: "kiro" },
				/cannot replace the native Kiro system prompt/,
			],
			[
				{ agent: "hs-pi-writer", harness: "kiro" },
				/strictly mappable tools allowlist/,
			],
			[
				{ agent: "hs-pi-unrestricted", harness: "claude" },
				/strictly mappable tools allowlist/,
			],
			[
				{ agent: "hs-pi-orchestrator", harness: "claude" },
				/Pi orchestration tools \(subagent\)/,
			],
			[
				{ agent: "hs-pi-spawner", harness: "kiro" },
				/without an explicit spawn-agents allowlist/,
			],
			[{ agent: "hs-pi-skilled", harness: "claude" }, /hs-missing-skill/],
		];
		for (const [params, reason] of cases) {
			const result = await executeTool(project, {
				name: `hs-${params.agent}`,
				task: "Task",
				...params,
			});
			assert.equal(
				result.details.error,
				"native-harness-unsupported",
				JSON.stringify(result.content),
			);
			assert.match(
				textOf(result),
				new RegExp(
					`^Error: Role "${params.agent}" cannot be projected from pi to ${params.harness}: `,
				),
			);
			assert.match(textOf(result), reason);
		}
		assert.deepEqual(herdr.events, []);
	});

	it("keeps hidden roles invocable by exact name with a harness", async () => {
		const project = scratch("hs-hidden");
		const herdr = useHerdr({ log: join(project, "..", "hidden.json") });
		testApi.setNativeTestSeam({ terminalAvailable: false });
		const result = await executeTool(project, {
			name: "hs-hidden",
			task: "Task",
			agent: "hs-pi-hidden",
			harness: "claude",
		});
		// Every projection check passed; only the Herdr prerequisite failed.
		assert.equal(result.details.error, "herdr not available");
		assert.deepEqual(herdr.events, []);
	});
});

describe("harness selection launches through the public paths", () => {
	it("runs a model-less Pi role on Claude and Kiro without Pi model defaults", async () => {
		for (const harness of ["claude", "kiro"] as const) {
			const project = scratch(`hs-open-${harness}`);
			const log = join(project, "..", `open-${harness}.json`);
			useHerdr({ log });
			const name = `hs-open-${harness}`;
			const started = await start(project, {
				name,
				task: "Task",
				agent: "hs-pi-open",
				harness,
			});
			assert.equal(started.details.harness, harness);
			assert.equal(started.details.model, undefined);
			assert.equal(started.details.runtimePlan, undefined);
			assert.equal(started.details.nativeThinking, "high");
			assert.deepEqual(started.details.selection, {
				harness,
				harnessSource: "request",
				projected: true,
				role: { name: "hs-pi-open", source: "global", harness: "pi" },
			});
			assert.match(
				textOf(started),
				new RegExp(
					`Harness: ${harness} \\(request; role hs-pi-open from global declares pi, projected\\)`,
				),
			);
			const result = await resultFor(name);
			assert.equal(result.details.exitCode, 0, result.content);
			assert.equal(result.details.native.harness, harness);
			assert.equal(result.details.native.model, null);
			assert.deepEqual(result.details.selection, started.details.selection);
			const args = fixtureArgs(log);
			assert.ok(!args.includes("--model"), args.join(" "));
			assert.ok(!args.some((arg) => arg.includes("fake/")), args.join(" "));
		}
	});

	it("replaces a pinned model across native harnesses and from Pi", async () => {
		for (const [agent, harness, model, pinned] of [
			["hs-claude-pinned", "kiro", "kiro-dest", "opus"],
			["hs-kiro-pinned", "claude", "claude-dest", "kiro-pinned"],
			["hs-pi-pinned", "claude", "claude-dest", "fake/pinned"],
		] as const) {
			const project = scratch(`hs-replace-${agent}`);
			const log = join(project, "..", `replace-${agent}.json`);
			useHerdr({ log });
			const name = `hs-replace-${agent}`;
			const started = await start(project, {
				name,
				task: "Task",
				agent,
				harness,
				model,
			});
			assert.equal(started.details.harness, harness);
			assert.equal(started.details.model, model);
			assert.equal(started.details.selection.projected, true);
			const result = await resultFor(name);
			assert.equal(result.details.exitCode, 0, result.content);
			const args = fixtureArgs(log);
			assert.equal(args[args.indexOf("--model") + 1], model);
			assert.ok(!args.includes(pinned), args.join(" "));
		}
	});

	it("uses the Pi path for a native role projected to Pi and keeps the native path when omitted", async () => {
		const project = scratch("hs-native-to-pi");
		const pi = usePiRecorder();
		const started = await testApi.startSubagentRun(
			api,
			{
				name: "hs-to-pi",
				task: "Task",
				agent: "hs-claude-pinned",
				harness: "pi",
				model: "fake/pi-a",
			},
			piCtx(project),
		);
		assert.equal(started.details.status, "started", JSON.stringify(started));
		assert.equal(started.details.harness, undefined);
		assert.equal(started.details.runtimePlan.model, "fake/pi-a");
		assert.equal(started.details.runtimePlan.modelSource, "request");
		assert.deepEqual(started.details.selection, {
			harness: "pi",
			harnessSource: "request",
			projected: true,
			role: { name: "hs-claude-pinned", source: "global", harness: "claude" },
		});
		assert.equal(pi.launched.length, 1);
		assert.match(pi.launched[0], /\bpi --session /);
		assert.match(pi.launched[0], /--model '?fake\/pi-a'?/);
		assert.doesNotMatch(pi.launched[0], /\bopus\b/);
		const result = await resultFor("hs-to-pi");
		assert.equal(result.details.native, undefined);
		assert.deepEqual(result.details.selection, started.details.selection);

		const nativeProject = scratch("hs-native-omitted");
		const log = join(nativeProject, "..", "omitted.json");
		useHerdr({ log });
		const omitted = await start(nativeProject, {
			name: "hs-omitted",
			task: "Task",
			agent: "hs-claude-pinned",
		});
		assert.equal(omitted.details.harness, "claude");
		assert.equal(omitted.details.model, "opus");
		assert.deepEqual(omitted.details.selection, {
			harness: "claude",
			harnessSource: "role",
			projected: false,
			role: { name: "hs-claude-pinned", source: "global", harness: "claude" },
		});
		// Omitted harness keeps the legacy acknowledgement text.
		assert.doesNotMatch(textOf(omitted), /Harness:/);
		await resultFor("hs-omitted");
		const args = fixtureArgs(log);
		assert.equal(args[args.indexOf("--model") + 1], "opus");
	});

	it("keeps a legacy Pi role on Pi with its configured default when harness is omitted", async () => {
		const project = scratch("hs-legacy-pi");
		const pi = usePiRecorder();
		const started = await testApi.startSubagentRun(
			api,
			{ name: "hs-legacy", task: "Task", agent: "hs-pi-open" },
			piCtx(project),
		);
		assert.equal(started.details.runtimePlan.model, "fake/pi-agent-default");
		assert.deepEqual(started.details.selection, {
			harness: "pi",
			harnessSource: "default",
			projected: false,
			role: { name: "hs-pi-open", source: "global", harness: "pi" },
		});
		assert.doesNotMatch(textOf(started), /Harness:/);
		assert.match(pi.launched[0], /--model '?fake\/pi-agent-default'?/);
		await resultFor("hs-legacy");
	});

	it("reports the project role's provenance over a global definition", async () => {
		const project = scratch("hs-provenance");
		const previous = process.cwd();
		mkdirSync(join(project, ".pi", "agents"), { recursive: true });
		writeFileSync(
			join(project, ".pi", "agents", "hs-pi-open.md"),
			"---\ndescription: project override\nauto-exit: true\ntools: read\n---\n\nProject role.\n",
		);
		process.chdir(project);
		try {
			usePiRecorder();
			const started = await testApi.startSubagentRun(
				api,
				{
					name: "hs-provenance",
					task: "Task",
					agent: "hs-pi-open",
					model: "fake/pi-a",
				},
				piCtx(project),
			);
			assert.equal(started.details.selection.role.source, "project");
			await resultFor("hs-provenance");
		} finally {
			process.chdir(previous);
		}
	});

	it("keeps one role snapshot and selection across Pi fallback attempts", async () => {
		const project = scratch("hs-pi-fallback");
		const rolePath = join(agentDir, "agents", "hs-claude-open.md");
		const original = readFileSync(rolePath, "utf8");
		const pi = usePiRecorder([
			() => {
				// A role edit between attempts never reaches the next attempt.
				writeFileSync(
					rolePath,
					original.replace("tools: read, bash", "tools: read"),
				);
				return { exitCode: 1, errorMessage: "provider unavailable" };
			},
			() => ({}),
		]);
		try {
			const started = await testApi.startSubagentRun(
				api,
				{
					name: "hs-pi-fallback",
					task: "Task",
					agent: "hs-claude-open",
					harness: "pi",
					model: "fake/pi-a, fake/pi-b",
				},
				piCtx(project),
			);
			const result = await resultFor("hs-pi-fallback");
			assert.deepEqual(result.details.fallbackAttempts, [
				"fake/pi-a",
				"fake/pi-b",
			]);
			assert.equal(result.details.runtimePlan.model, "fake/pi-b");
			assert.deepEqual(result.details.selection, started.details.selection);
			assert.equal(pi.launched.length, 2);
			for (const command of pi.launched)
				assert.match(command, /--tools '[^']*\bbash\b/);
		} finally {
			writeFileSync(rolePath, original);
		}
	});

	it("keeps the selection across native fallback attempts through the public selector", async () => {
		const project = scratch("hs-native-fallback");
		const log = join(project, "..", "native-fallback.json");
		useHerdr({ log, env: { FAKE_FAIL_MODEL: "bad" } });
		const started = await start(project, {
			name: "hs-native-fallback",
			task: "Task",
			agent: "hs-pi-open",
			harness: "claude",
			model: "bad, good",
		});
		assert.deepEqual(started.details.nativeModels, ["bad", "good"]);
		const result = await resultFor("hs-native-fallback");
		assert.equal(result.details.exitCode, 0, result.content);
		assert.deepEqual(result.details.fallbackAttempts, ["bad", "good"]);
		assert.equal(result.details.native.model, "good");
		assert.deepEqual(result.details.selection, started.details.selection);
	});

	it("carries the selection on every persistent specialist task", async () => {
		const project = scratch("hs-persistent");
		useHerdr({ log: join(project, "..", "persistent.json") });
		const started = await start(project, {
			name: "hs-spec",
			task: "First task",
			agent: "hs-pi-persistent",
			harness: "claude",
		});
		assert.equal(started.details.nativeMode, "persistent");
		const first = await waitForMessage((message) =>
			/Persistent specialist "hs-spec" completed task/.test(
				message.content ?? "",
			),
		);
		assert.deepEqual(first.details.selection, started.details.selection);
		const second = testApi.handleSubagentSend({
			name: "hs-spec",
			message: "Second task",
		});
		assert.equal(second.details.outcome, "dispatched");
		const next = await waitForMessage((message) =>
			/completed task [\s\S]*2 tasks settled/.test(message.content ?? ""),
		);
		assert.equal(next.details.generationId, first.details.generationId);
		assert.deepEqual(next.details.selection, started.details.selection);
		testApi.handleSubagentStop({ name: "hs-spec" }, api);
		const stopped = await waitForMessage(
			(message) =>
				message.customType === "subagent_stop" &&
				message.details?.status === "stopped" &&
				message.details?.facts?.logicalId === first.details.logicalId,
		);
		assert.deepEqual(stopped.details.selection, started.details.selection);
	});

	it("carries the selection on a projected Pi specialist's help request and crash notice", async () => {
		const project = scratch("hs-pi-specialist");
		usePiRecorder([
			(child) => {
				// The specialist asks for help, then its process ends without a
				// stop request: the parent delivers the help request, then the
				// crash notice.
				appendPersistentTaskEvent(child.sessionFile, {
					type: "help-request",
					task: child.taskId!,
					generation: child.generationId!,
					message: "Which schema?",
				});
				return { exitCode: 1 };
			},
		]);
		const started = await testApi.startSubagentRun(
			api,
			{
				name: "hs-pi-spec",
				task: "First task",
				agent: "hs-claude-persistent",
				harness: "pi",
				model: "fake/pi-a",
			},
			piCtx(project),
		);
		assert.equal(started.details.status, "started", JSON.stringify(started));
		assert.deepEqual(started.details.selection, {
			harness: "pi",
			harnessSource: "request",
			projected: true,
			role: {
				name: "hs-claude-persistent",
				source: "global",
				harness: "claude",
			},
		});
		const help = await waitForMessage(
			(message) =>
				message.customType === "subagent_ping" &&
				message.details?.name === "hs-pi-spec",
		);
		assert.match(help.content, /requests help for task [\s\S]*Which schema\?/);
		assert.deepEqual(help.details.selection, started.details.selection);
		const crash = await waitForMessage(
			(message) =>
				message.details?.error === "persistent-crash" &&
				message.details?.facts?.sessionFile === help.details.sessionFile,
		);
		assert.match(crash.content, /Persistent specialist crashed/);
		assert.deepEqual(crash.details.selection, started.details.selection);
	});

	it("resumes a projected native session from its marker without re-resolving the role", async () => {
		const project = scratch("hs-resume");
		const log = join(project, "..", "resume.json");
		useHerdr({ log });
		await start(project, {
			name: "hs-resume",
			task: "Task",
			agent: "hs-pi-resume",
			harness: "claude",
		});
		const first = await resultFor("hs-resume");
		assert.equal(first.details.exitCode, 0, first.content);
		// The role no longer exists, so any role or harness lookup would fail.
		rmSync(join(agentDir, "agents", "hs-pi-resume.md"));
		const resumed = await resume(project, {
			sessionPath: first.details.native.markerFile,
			message: "Continue",
			name: "hs-resumed",
		});
		assert.equal(resumed.details.status, "started", JSON.stringify(resumed));
		assert.equal(resumed.details.harness, "claude");
		const result = await resultFor("hs-resumed");
		assert.equal(result.details.exitCode, 0, result.content);
		assert.equal(result.details.native.harness, "claude");
		assert.equal(result.details.selection, undefined);
		assert.ok(fixtureArgs(log).includes("--resume"));
	});
});

describe("/subagent command", () => {
	const notices: Array<{ text: string; level: string }> = [];
	const commandCtx = {
		ui: {
			notify: (text: string, level: string) => notices.push({ text, level }),
		},
	};
	const runCommand = async (args: string) => {
		notices.length = 0;
		const dispatched = userMessages.length;
		await commands.get("subagent").handler(args, commandCtx);
		return userMessages.slice(dispatched);
	};
	/** Decode the JSON-serialized arguments of a dispatched instruction. */
	const decode = (message: string) =>
		Object.fromEntries(
			[...message.matchAll(/(\w+): ("(?:[^"\\]|\\.)*")/g)].map(
				([, key, value]) => [key, JSON.parse(value)],
			),
		);

	it("dispatches the exact parsed arguments, which launch through the tool", async () => {
		const task = "Run git diff -- \"a b\" \\d+\there\nline two --flag 'q'";
		const [message] = await runCommand(
			`hs-pi-open --harness kiro --model "kiro-a, kiro-b" --thinking high -- ${task}`,
		);
		assert.equal(
			message,
			`Use subagent with agent: "hs-pi-open", name: "Hs-pi-open", task: ${JSON.stringify(task)}, harness: "kiro", model: "kiro-a, kiro-b", thinking: "high"`,
		);
		const params: StartParams = {
			agent: "hs-pi-open",
			name: "Hs-pi-open",
			task,
			harness: "kiro",
			model: "kiro-a, kiro-b",
			thinking: "high",
		};
		// The decoded instruction carries exactly these tool arguments.
		assert.deepEqual(decode(message), params);
		const project = scratch("hs-command");
		const log = join(project, "..", "command.json");
		useHerdr({ log });
		const started = await executeTool(project, params);
		assert.equal(started.details.status, "started", JSON.stringify(started));
		assert.equal(started.details.harness, "kiro");
		assert.deepEqual(started.details.nativeModels, ["kiro-a", "kiro-b"]);
		assert.equal(started.details.task, task);
		const result = await resultFor("Hs-pi-open");
		assert.equal(result.details.exitCode, 0, result.content);
		assert.equal(result.details.selection.harness, "kiro");
	});

	it("keeps the legacy default wait task and message without options", async () => {
		assert.deepEqual(await runCommand("hs-pi-open"), [
			'Use subagent with agent: "hs-pi-open", name: "Hs-pi-open", task: "You are the hs-pi-open agent. Wait for instructions."',
		]);
		assert.deepEqual(await runCommand("hs-pi-open   Map the flow  "), [
			'Use subagent with agent: "hs-pi-open", name: "Hs-pi-open", task: "Map the flow"',
		]);
		assert.deepEqual(await runCommand("hs-pi-open --harness claude"), [
			'Use subagent with agent: "hs-pi-open", name: "Hs-pi-open", task: "You are the hs-pi-open agent. Wait for instructions.", harness: "claude"',
		]);
	});

	it("rejects malformed options, unknown roles, and invalid projections without dispatching", async () => {
		for (const [args, error] of [
			["hs-pi-open --harness", /--harness requires a value/],
			[
				"hs-pi-open --harness codex Task",
				/--harness must be one of pi, claude, kiro/,
			],
			["hs-pi-open --model --harness kiro Task", /--model requires a value/],
			['hs-pi-open --model "" Task', /--model value cannot be empty/],
			['hs-pi-open --model "opus, sonnet Task', /unclosed " quote/],
			["hs-pi-open --model a --model b Task", /Duplicate option --model/],
			["hs-pi-open --thinking extreme Task", /--thinking must be one of/],
			["hs-pi-open --verbose Task", /Unknown option --verbose/],
			['hs-pi-open --model "a"b Task', /followed by whitespace/],
			['hs-pi-open --model a"b Task', /quoted as a whole/],
			["--harness claude hs-pi-open Task", /agent name must come first/],
			["hs-nope --harness claude Task", /Agent "hs-nope" not found/],
			[
				"hs-claude-pinned --harness pi Task",
				/requires an explicit Pi provider\/model-id/,
			],
			["hs-delegator --harness pi --model fake/pi-a Task", /spawn-agents/],
		] as const) {
			assert.deepEqual(await runCommand(args), [], args);
			assert.equal(notices.length, 1, args);
			assert.equal(notices[0].level, "error", args);
			assert.match(notices[0].text, error, args);
		}
	});
});

describe("slash option parser", () => {
	const parse = testApi.parseSubagentCommand;

	it("parses quoted option values and preserves the task verbatim", () => {
		assert.deepEqual(
			parse(
				`scout --model 'opus, "sonnet"' --thinking "low" Find \\d+ "x"\t--y`,
			),
			{
				ok: true,
				agent: "scout",
				task: 'Find \\d+ "x"\t--y',
				model: 'opus, "sonnet"',
				thinking: "low",
			},
		);
		assert.deepEqual(parse('scout --model "a \\"b\\" c\\\\d\\e" Task'), {
			ok: true,
			agent: "scout",
			task: "Task",
			model: 'a "b" c\\d\\e',
		});
		assert.deepEqual(parse("scout\n--harness\tkiro\n\nline one\nline two"), {
			ok: true,
			agent: "scout",
			task: "line one\nline two",
			harness: "kiro",
		});
		assert.deepEqual(parse("scout Run git diff -- README.md"), {
			ok: true,
			agent: "scout",
			task: "Run git diff -- README.md",
		});
		assert.deepEqual(parse("scout -- -- --harness pi"), {
			ok: true,
			agent: "scout",
			task: "-- --harness pi",
		});
		assert.deepEqual(parse("scout --"), { ok: true, agent: "scout", task: "" });
		assert.equal(parse("   ").ok, false);
		assert.equal(parse("scout --harness pi --harness pi").ok, false);
	});
});

describe("role projection contract", () => {
	const role = (overrides: { cli?: "claude" | "kiro"; model?: string }) => ({
		name: "packed",
		description: "packed role",
		disableModelInvocation: false,
		source: "package" as const,
		path: "/roles/packed.md",
		provider: "@acme/roles",
		providerVersion: "1.2.3",
		tools: "read",
		...overrides,
	});

	it("records role-pack provenance and never carries a pinned model across harnesses", () => {
		const projection = testApi.resolveRoleProjection(
			{ agent: "packed", harness: "kiro", model: "kiro-x" },
			role({ cli: "claude", model: "opus" }),
		);
		assert.ok(projection.ok);
		assert.deepEqual(projection.selection, {
			harness: "kiro",
			harnessSource: "request",
			projected: true,
			role: {
				name: "packed",
				source: "package",
				provider: "@acme/roles",
				providerVersion: "1.2.3",
				harness: "claude",
			},
		});
		assert.equal(projection.agentDefs?.cli, "kiro");
		assert.equal(projection.agentDefs?.model, undefined);

		const toPi = testApi.resolveRoleProjection(
			{ agent: "packed", harness: "pi", model: "fake/pi-a" },
			role({ cli: "kiro", model: "kiro-pinned" }),
		);
		assert.ok(toPi.ok);
		assert.equal(toPi.agentDefs?.cli, undefined);
		assert.equal(toPi.agentDefs?.model, undefined);

		const same = testApi.resolveRoleProjection(
			{ agent: "packed", harness: "claude" },
			role({ cli: "claude", model: "opus" }),
		);
		assert.ok(same.ok);
		assert.equal(same.selection.projected, false);
		assert.equal(same.agentDefs?.model, "opus");

		const bare = testApi.resolveRoleProjection({}, null);
		assert.deepEqual(bare, {
			ok: true,
			selection: { harness: "pi", harnessSource: "default", projected: false },
			agentDefs: null,
		});
	});
});
