// This content is generated by AI (Kiro)
/**
 * Shared offline helpers for native harness tests. Launches use the real
 * script staging and process receipts with the fixture `claude` and
 * `kiro-cli` stand-ins on PATH; nothing contacts a model.
 */
import assert from "node:assert/strict";
import {
	type ChildProcess,
	execFileSync,
	spawn,
	spawnSync,
} from "node:child_process";
import {
	existsSync,
	mkdirSync,
	mkdtempSync,
	readFileSync,
	rmSync,
	writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
	createProcessRun,
	terminateProcessRun,
	type ProcessRun,
} from "../pi-extension/subagents/process-run.ts";
import { stageScript } from "../pi-extension/subagents/terminal.ts";
import {
	createNativeHarnessOperations,
	planNativeLaunch,
	resolveNativeLaunchSpec,
	type NativeRoleDefinition,
} from "../pi-extension/subagents/native-harness.ts";
import type {
	FreshNativeLaunchRequest,
	PiLaunchOperations,
} from "../pi-extension/subagents/launch.ts";
import type { JsonObject } from "../pi-extension/subagents/type-guards.ts";

export const FIXTURE_BIN = join(
	dirname(fileURLToPath(import.meta.url)),
	"fixtures",
	"native-bin",
);
export const fixtureEnv = (extra: Record<string, string> = {}) => ({
	...process.env,
	PATH: `${FIXTURE_BIN}:${process.env.PATH}`,
	...extra,
});
export const UUID = /^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$/;
/** Linux-only assertions skip gracefully elsewhere; ownership fails closed there. */
export const linux = process.platform === "linux";

let root: string | undefined;
export function scratch(name: string): string {
	if (!root) {
		root = mkdtempSync(join(tmpdir(), "native-harness-test-"));
		const owned = root;
		process.once("exit", () => rmSync(owned, { recursive: true, force: true }));
	}
	return mkdtempSync(join(root, `${name}-`));
}

export function role(
	overrides: Partial<NativeRoleDefinition> = {},
): NativeRoleDefinition {
	return {
		name: "native-worker",
		cli: "claude",
		tools: "read, bash",
		autoExit: true,
		body: "You are a native worker.",
		...overrides,
	};
}

export function runHook(hook: string, config: string, payload: JsonObject) {
	return spawnSync("python3", [hook, config], {
		input: JSON.stringify(payload),
		encoding: "utf8",
	});
}

export function processRunIn(dir: string, id = "run-1"): ProcessRun {
	mkdirSync(dir, { recursive: true });
	return createProcessRun(id, join(dir, "process.json"));
}

export function killGroup(pid: number | undefined) {
	try {
		if (pid) process.kill(-pid, "SIGKILL");
	} catch {
		// Already gone.
	}
}

export async function waitFor(check: () => boolean, timeoutMs = 5000) {
	const deadline = Date.now() + timeoutMs;
	while (!check()) {
		if (Date.now() > deadline) throw new Error("timed out waiting");
		await new Promise((resolve) => setTimeout(resolve, 20));
	}
}

export interface Harness {
	operations: PiLaunchOperations;
	children: ChildProcess[];
	events: string[];
	closed: string[];
	send(surface: string, text: string): void;
	/** Model the interrupt key reaching the native TUI. */
	interrupt(surface: string): void;
	/** Model a human typing a prompt into the native TUI. */
	human(surface: string, text: string): void;
}

export function fakeHerdr(options: {
	mode?: string;
	log: string;
	env?: Record<string, string>;
	createWorktree?: PiLaunchOperations["createWorktree"];
	/**
	 * Dispatch the script, then report a delivery failure: on every run, or
	 * only on the given 1-based run call.
	 */
	failAfterRun?: boolean | number;
	/** Return only once the wrapper recorded its exit (fast-exit races). */
	waitForExit?: boolean;
	/** Refuse to dispatch: the script is never staged or started. */
	failBeforeRun?: boolean;
	/** Runs as a dispatch begins (after the launch's pre-dispatch steps). */
	onRun?: (surface: string) => void;
	/** Replace the shell-readiness wait (called with a 1-based call count). */
	waitForShellReady?: (surface: string, call: number) => Promise<void>;
}): Harness {
	const children: ChildProcess[] = [];
	const events: string[] = [];
	const closed: string[] = [];
	const bySurface = new Map<string, ChildProcess>();
	let panes = 0;
	const write = (surface: string, line: string) =>
		bySurface.get(surface)?.stdin?.write(`${line}\n`);
	const operations: PiLaunchOperations = {
		createPane(name) {
			events.push(`create:${name}`);
			return `pane-${++panes}`;
		},
		createWorktree:
			options.createWorktree ??
			(() => {
				throw new Error("unexpected worktree creation");
			}),
		async waitForShellReady(surface) {
			events.push("ready");
			const call = events.filter((event) => event === "ready").length;
			await options.waitForShellReady?.(surface, call);
		},
		runScript(surface, command, script) {
			options.onRun?.(surface);
			if (options.failBeforeRun)
				throw new Error("herdr refused to run the script in the pane");
			events.push("run");
			// The real staging used by runScriptInPane, without Herdr delivery.
			stageScript(command, script);
			const child = spawn("bash", [script.scriptPath], {
				detached: true,
				stdio: ["pipe", "ignore", "ignore"],
				env: fixtureEnv({
					FAKE_NATIVE_MODE: options.mode ?? "ok",
					FAKE_NATIVE_LOG: options.log,
					...options.env,
				}),
			});
			children.push(child);
			bySurface.set(surface, child);
			if (options.waitForExit) {
				const receipt = command.match(
					/mv -f -- '[^']+' '([^']+process\.json)'/,
				)?.[1];
				const sleeper = new Int32Array(new SharedArrayBuffer(4));
				const deadline = Date.now() + 10_000;
				const exited = () => {
					try {
						return /"exitCode"/.test(readFileSync(receipt ?? "", "utf8"));
					} catch {
						return false;
					}
				};
				while (receipt && !exited() && Date.now() < deadline)
					Atomics.wait(sleeper, 0, 0, 20);
			}
			const runCall = events.filter((event) => event === "run").length;
			if (options.failAfterRun === true || options.failAfterRun === runCall) {
				// Fail only once the wrapper has provably started (its receipt
				// exists), modelling a lost acknowledgement after dispatch.
				const receipt = command.match(
					/mv -f -- '[^']+' '([^']+process\.json)'/,
				)?.[1];
				const sleeper = new Int32Array(new SharedArrayBuffer(4));
				const deadline = Date.now() + 5_000;
				while (receipt && !existsSync(receipt) && Date.now() < deadline)
					Atomics.wait(sleeper, 0, 0, 20);
				throw new Error("herdr pane run acknowledgement was lost");
			}
			return script.scriptPath;
		},
		closePane(surface) {
			closed.push(surface);
		},
	};
	return {
		operations,
		children,
		events,
		closed,
		send: write,
		interrupt: (surface) => write(surface, "ESC"),
		human: (surface, text) => write(surface, `HUMAN ${text}`),
	};
}

export const nativeOperations = createNativeHarnessOperations(
	(file, args, opts) =>
		execFileSync(file, args, {
			encoding: "utf8",
			timeout: opts.timeout,
			stdio: "pipe",
			env: fixtureEnv(),
		}),
);

export interface ParentSessionPaths {
	sessionDir: string;
	sessionFile: string;
}

export function parentSession(project: string): ParentSessionPaths {
	const sessionDir = join(
		project,
		"..",
		`${project.split("/").pop()}-sessions`,
	);
	mkdirSync(sessionDir, { recursive: true });
	return { sessionDir, sessionFile: join(sessionDir, "parent.jsonl") };
}

export function nativeRequest(
	project: string,
	harness: "claude" | "kiro",
	overrides: Partial<FreshNativeLaunchRequest> = {},
	roleOverrides: Partial<NativeRoleDefinition> = {},
): FreshNativeLaunchRequest {
	const { sessionDir, sessionFile } = parentSession(project);
	const task = overrides.task ?? "Implement the bounded change.";
	const spec = resolveNativeLaunchSpec(
		role({
			cli: harness,
			tools: harness === "claude" ? "read,bash" : "read",
			thinking: "high",
			model: "fixture-model",
			...roleOverrides,
		}),
	);
	return {
		kind: "native",
		id: `native-${harness}`,
		name: "Native worker",
		task,
		agent: `${harness}-worker`,
		parent: {
			cwd: project,
			sessionFile,
			sessionId: "parent",
			sessionDir,
			agentDir: join(project, "..", "agent"),
		},
		behavior: { interactive: spec.mode === "interactive" },
		plan: planNativeLaunch(spec, {
			task,
			parentSessionFile: sessionFile,
			installedSkills: () => [],
		}),
		...overrides,
	};
}

export function watchDeps(harness: Harness, terminated: string[] = []) {
	return {
		send: harness.send,
		inspectPane: async () => ({
			kind: "present" as const,
			agentStatus: "done" as const,
			observedAt: Date.now(),
		}),
		readVisiblePane: async () => "",
		terminate: (processRun: ProcessRun) => {
			terminated.push(processRun.id);
			return terminateProcessRun(processRun);
		},
		intervalMs: 20,
		terminationGraceMs: 3000,
	};
}

export function initRepo(project: string): string {
	execFileSync("git", ["init", "-q", "-b", "main"], { cwd: project });
	for (const [key, value] of [
		["user.email", "test@example.com"],
		["user.name", "Test"],
		["commit.gpgsign", "false"],
	])
		execFileSync("git", ["config", key, value], { cwd: project });
	writeFileSync(join(project, "base.txt"), "base\n");
	execFileSync("git", ["add", "."], { cwd: project });
	execFileSync("git", ["commit", "-qm", "base"], { cwd: project });
	return execFileSync("git", ["rev-parse", "HEAD"], {
		cwd: project,
		encoding: "utf8",
	}).trim();
}

export function assertMatchesAll(text: string, patterns: RegExp[]): void {
	for (const pattern of patterns) assert.match(text, pattern);
}
