// This content is generated by AI (Kiro)
/**
 * End-to-end native flows through the extension's public tool handlers, with
 * fixture CLIs and a fake Herdr surface. Covers follow-ups, reload races,
 * fork context, model fallback, persistent specialists, interrupts,
 * interactive sessions, resume with exact loadout replay, session leases,
 * worktree leases, and nested delegation. No model is contacted.
 */
import "./isolated-agent-dir.ts";
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { execFileSync, spawn } from "node:child_process";
import { randomUUID } from "node:crypto";
import {
	existsSync,
	readdirSync,
	readFileSync,
	statSync,
	writeFileSync,
} from "node:fs";
import { join } from "node:path";
import * as subagentsModule from "../pi-extension/subagents/index.ts";
import {
	checkNativeResume,
	readNativeSessionMarker,
} from "../pi-extension/subagents/native-harness.ts";
import {
	OWNER_ENV,
	createProcessRun,
	terminateProcessRun,
} from "../pi-extension/subagents/process-run.ts";
import { writeWorktreeManifest } from "../pi-extension/subagents/launch.ts";
import { readPersistentDeliveryLedger } from "../pi-extension/subagents/session.ts";
import { createLifecycle } from "../pi-extension/subagents/lifecycle.ts";
import {
	initRepo,
	killGroup,
	linux,
	parentSession,
	scratch,
	waitFor,
} from "./native-fixtures.ts";
import {
	api,
	ctxFor,
	fixtureEvents,
	markerV2,
	resultFor,
	resume,
	running,
	sent,
	start,
	testApi,
	useHerdr,
	waitForMessage,
	writeRole,
} from "./native-flow-harness.ts";

writeRole("native-claude", [
	"cli: claude",
	"auto-exit: true",
	"tools: read, bash",
]);
writeRole("native-kiro", ["cli: kiro", "auto-exit: true", "tools: read"]);
writeRole("native-mcp", [
	"cli: kiro",
	"auto-exit: true",
	"tools: read",
	"kiro-mcp-servers: jira-connector",
]);
writeRole("native-persistent", [
	"cli: claude",
	"persistent: true",
	"tools: read, bash",
]);
writeRole("native-interactive", ["cli: claude", "tools: read"]);
writeRole("native-scout", ["cli: claude", "auto-exit: true", "tools: read"]);
writeRole("native-delegator", [
	"cli: claude",
	"auto-exit: true",
	"tools: read, bash",
	"spawn-agents: native-scout, pi-wide, pi-open, native-persistent, native-interactive",
]);
writeRole("pi-wide", ["auto-exit: true", "tools: read, write"]);
writeRole("pi-open", ["auto-exit: true"]);

describe("native follow-ups, reload, and fork context", () => {
	it("types a queued follow-up after the verified Stop, including after a module reload", async () => {
		const project = scratch("flow-follow-up");
		const log = join(project, "..", "follow-up.json");
		useHerdr({ log });
		const started = await start(project, {
			name: "fu-claude",
			task: "Initial task",
			agent: "native-claude",
		});
		assert.equal(started.details.harness, "claude");
		assert.equal(started.details.nativeMode, "autonomous");
		// The reloaded module adopts the shared registry and driver state; the
		// original watcher delivers what the reloaded tool queued.
		const reloaded: typeof subagentsModule = await import(
			new URL(
				"../pi-extension/subagents/index.ts?native-reload",
				import.meta.url,
			).href
		);
		const queued = reloaded.__test__.handleSubagentSend({
			name: "fu-claude",
			message: "Follow\nup please",
		});
		assert.equal(queued.details.outcome, "queued", JSON.stringify(queued));
		const result = await resultFor("fu-claude");
		assert.equal(result.details.exitCode, 0, result.content);
		assert.match(result.content, /Claude follow-up result 2/);
		assert.deepEqual(
			result.details.native.turns.map(
				(turn: any) => `${turn.kind}=${turn.outcome}`,
			),
			["initial=completed", "follow-up=completed"],
		);
		const inputs = fixtureEvents(log).flatMap((event) =>
			event.input ? [event.input] : [],
		);
		assert.match(
			inputs[0],
			/^\[pi-subagent-turn:[0-9a-f-]{36}\] Follow up please$/,
		);
		assert.equal(inputs.at(-1), "/exit");
		const unknown = testApi.handleSubagentSend({
			name: "nobody",
			message: "x",
		});
		assert.match(unknown.details.error ?? "", /No running subagent/);
	});

	it("forks bounded parent text into an untrusted first-turn block", async () => {
		const project = scratch("flow-fork");
		const log = join(project, "..", "fork.json");
		useHerdr({ log });
		const { sessionFile } = parentSession(project);
		const entry = (
			id: string,
			parentId: string | null,
			role: string,
			text: string,
		) =>
			JSON.stringify({
				type: "message",
				id,
				parentId,
				timestamp: new Date().toISOString(),
				message: { role, content: [{ type: "text", text }], timestamp: 0 },
			});
		writeFileSync(
			sessionFile,
			[
				JSON.stringify({
					type: "session",
					version: 3,
					id: randomUUID(),
					timestamp: new Date().toISOString(),
					cwd: project,
				}),
				entry("a1", null, "user", "context question"),
				entry("a2", "a1", "assistant", "context answer"),
				entry("a3", "a2", "user", "spawn it now"),
			].join("\n") + "\n",
		);
		await start(project, {
			name: "fork-claude",
			task: "Use the context",
			agent: "native-claude",
			fork: true,
		});
		const result = await resultFor("fork-claude");
		assert.equal(result.details.exitCode, 0, result.content);
		const prompt = JSON.parse(readFileSync(log, "utf8")).args.at(-1);
		assert.match(
			prompt,
			/Inherited parent conversation \(untrusted reference data\)/,
		);
		assert.match(prompt, /\[assistant\] context answer/);
		assert.doesNotMatch(prompt, /spawn it now/);
		const marker = readNativeSessionMarker(result.details.sessionFile);
		assert.equal(marker?.version, 2);
		assert.ok(marker?.version === 2);
		const lineage = marker.loadout.lineage;
		assert.equal(lineage?.mode, "fork");
		assert.equal(lineage?.parentSessionFile, sessionFile);
		assert.equal(statSync(lineage!.context!.file).mode & 0o777, 0o600);
		assert.match(
			readFileSync(lineage!.context!.file, "utf8"),
			/context answer/,
		);
	});
});

describe("native model fallback", () => {
	it("fails closed on Claude workspace trust without typing, fallback, or pane close", async () => {
		const project = scratch("flow-workspace-trust");
		const log = join(project, "..", "trust.json");
		const terminations: string[] = [];
		const herdr = useHerdr(
			{ log, mode: "workspace-trust" },
			{
				watch: {
					inspectPane: async () => ({
						kind: "present",
						agentStatus: "blocked",
						observedAt: Date.now(),
					}),
					readVisiblePane: async () =>
						"Accessing workspace: /tmp/example\nQuick safety check: Is this a project you created or one you trust?\nClaude Code'll be able to read, edit, and execute files here.\nYes, I trust this folder\nNo, exit",
					terminate: (run) => {
						terminations.push(run.id);
						return terminateProcessRun(run);
					},
				},
			},
		);
		await start(project, {
			name: "trust-claude",
			task: "Task",
			agent: "native-claude",
			model: "first, second",
		});
		const result = await resultFor("trust-claude");
		assert.equal(result.details.native.startupBlock, "claude-workspace-trust");
		assert.deepEqual(result.details.fallbackAttempts, ["first"]);
		assert.equal(terminations.length, 1, "owned termination runs exactly once");
		assert.deepEqual(
			fixtureEvents(log),
			[],
			"the parent never types an answer",
		);
		assert.equal(result.details.native.resume.available, false);
		assert.match(result.content, /workspace trust blocked startup/);
		assert.match(result.content, /Native cwd:/);
		assert.match(result.content, /Native pane: pane-1/);
		assert.match(result.content, /Retained for inspection: pane pane-1/);
		assert.match(result.content, /start Claude manually/);
		assert.deepEqual(
			herdr.closed,
			[],
			"diagnostic pane remains for manual close",
		);
	});

	it("advances past a model that never started and records ordered evidence", async () => {
		const project = scratch("flow-fallback");
		useHerdr({
			log: join(project, "..", "fb.json"),
			env: { FAKE_FAIL_MODEL: "bad" },
		});
		await start(project, {
			name: "fb-claude",
			task: "Task",
			agent: "native-claude",
			model: "bad, good",
		});
		const result = await resultFor("fb-claude");
		assert.equal(result.details.exitCode, 0, result.content);
		assert.deepEqual(result.details.fallbackAttempts, ["bad", "good"]);
		assert.match(
			result.details.fallbackFailures[0].error,
			/unacknowledged[\s\S]*marker /,
		);
		assert.equal(result.details.native.model, "good");
		assert.match(result.content, /Models attempted: bad, good/);
	});

	it("never retries after a correlated Claude StopFailure, which may follow work", async () => {
		const project = scratch("flow-stop-failure");
		useHerdr({
			log: join(project, "..", "sf.json"),
			env: { FAKE_STOP_FAILURE_MODEL: "m1" },
		});
		await start(project, {
			name: "sf-claude",
			task: "Task",
			agent: "native-claude",
			model: "m1, m2",
		});
		const result = await resultFor("sf-claude");
		assert.notEqual(result.details.exitCode, 0);
		assert.deepEqual(result.details.fallbackAttempts, ["m1"]);
		assert.match(result.details.errorMessage, /rate_limit/);
		assert.match(
			result.details.errorMessage,
			/No native model fallback: there is no positive evidence/,
		);
	});

	it("never retries an attempt that exited before any hook receipt", async () => {
		const project = scratch("flow-no-receipt");
		useHerdr({
			log: join(project, "..", "nr0.json"),
			mode: "exit-before-hooks",
		});
		await start(project, {
			name: "no-receipt",
			task: "Task",
			agent: "native-claude",
			model: "a1, a2",
		});
		const result = await resultFor("no-receipt");
		assert.deepEqual(
			result.details.fallbackAttempts,
			["a1"],
			"a missing receipt is not evidence that nothing ran",
		);
		assert.match(result.details.errorMessage, /no positive evidence/);
	});

	it("never retries a completed result or a Kiro turn that exited mid-task", async () => {
		const project = scratch("flow-no-retry");
		useHerdr({ log: join(project, "..", "nr.json") });
		await start(project, {
			name: "nr-claude",
			task: "Task",
			agent: "native-claude",
			model: "m1, m2",
		});
		const completed = await resultFor("nr-claude");
		assert.deepEqual(completed.details.fallbackAttempts, ["m1"]);

		const kiroProject = scratch("flow-kiro-no-retry");
		useHerdr({
			log: join(kiroProject, "..", "k.json"),
			env: { FAKE_STOP_FAILURE_MODEL: "k1" },
		});
		await start(kiroProject, {
			name: "nr-kiro",
			task: "Task",
			agent: "native-kiro",
			model: "k1, k2",
		});
		const failed = await resultFor("nr-kiro");
		assert.notEqual(failed.details.exitCode, 0);
		assert.deepEqual(failed.details.fallbackAttempts, ["k1"]);
		assert.match(
			failed.details.errorMessage,
			/No native model fallback: there is no positive evidence/,
		);
	});

	it("reuses a retained worktree only when the failed attempt left it pristine", async () => {
		const project = scratch("flow-worktree-fallback");
		initRepo(project);
		let created = 0;
		const tree = join(project, "..", "fallback-tree");
		const herdr = useHerdr({
			log: join(project, "..", "wt.json"),
			env: { FAKE_FAIL_MODEL: "bad" },
			createWorktree(_name, cwd, branch, base) {
				created++;
				execFileSync(
					"git",
					["worktree", "add", "-q", "-b", branch, tree, base],
					{
						cwd,
					},
				);
				return { path: tree, branch, workspaceId: "ws-fb", paneId: "root-fb" };
			},
		});
		await start(project, {
			name: "wt-claude",
			task: "Task",
			agent: "native-claude",
			model: "bad, good",
			worktree: { branch: "native/fallback" },
		});
		const result = await resultFor("wt-claude");
		assert.equal(result.details.exitCode, 0, result.content);
		assert.equal(created, 1, "the same retained worktree is reused");
		assert.deepEqual(result.details.fallbackAttempts, ["bad", "good"]);
		assert.equal(result.details.worktree.clean, true);
		assert.deepEqual(herdr.closed, [], "the retained root pane is kept");
		const manifest = JSON.parse(
			readFileSync(result.details.worktree.manifestFile, "utf8"),
		);
		assert.equal(manifest.state, "ready_for_review");
		assert.equal(manifest.nativeModel, "good");

		const dirtyProject = scratch("flow-worktree-no-fallback");
		initRepo(dirtyProject);
		const dirtyTree = join(dirtyProject, "..", "dirty-tree");
		useHerdr({
			log: join(dirtyProject, "..", "wt2.json"),
			env: { FAKE_STOP_FAILURE_MODEL: "m1" },
			createWorktree(_name, cwd, branch, base) {
				execFileSync(
					"git",
					["worktree", "add", "-q", "-b", branch, dirtyTree, base],
					{ cwd },
				);
				return {
					path: dirtyTree,
					branch,
					workspaceId: "ws-d",
					paneId: "root-d",
				};
			},
		});
		await start(dirtyProject, {
			name: "wt-no-fallback",
			task: "Task",
			agent: "native-claude",
			model: "m1, m2",
			worktree: { branch: "native/no-fallback" },
		});
		const failed = await resultFor("wt-no-fallback");
		assert.deepEqual(failed.details.fallbackAttempts, ["m1"]);
		assert.match(failed.details.errorMessage, /no positive evidence/);
	});
});

describe("native persistent specialists", () => {
	it("delivers each task exactly once and stops at a verified idle point", async () => {
		const project = scratch("flow-persistent");
		const log = join(project, "..", "persist.json");
		useHerdr({ log });
		await start(project, {
			name: "spec-claude",
			task: "First task",
			agent: "native-persistent",
		});
		const first = await waitForMessage((message) =>
			/Persistent specialist "spec-claude" completed task/.test(
				message.content ?? "",
			),
		);
		assert.match(first.content, /Claude fixture result/);
		const child = running("spec-claude")!;
		assert.equal(testApi.persistentSpecialistState(child), "idle");
		const second = testApi.handleSubagentSend({
			name: "spec-claude",
			message: "Second task",
		});
		assert.equal(second.details.outcome, "dispatched");
		await waitForMessage((message) =>
			/completed task [\s\S]*2 tasks settled/.test(message.content ?? ""),
		);
		const stop = testApi.handleSubagentStop({ name: "spec-claude" }, api);
		assert.equal(stop.details.status, "stop_requested");
		const stopped = await waitForMessage(
			(message) =>
				message.customType === "subagent_stop" &&
				message.details?.status === "stopped",
		);
		assert.match(stopped.content, /Persistent specialist stopped/);
		const ledger = readPersistentDeliveryLedger(child.sessionFile).map(
			(entry) => entry.outcome,
		);
		// The first task is planned before its process exists, then committed.
		assert.deepEqual(ledger, [
			"planned",
			"dispatched",
			"delivered",
			"dispatched",
			"delivered",
			"stopped",
		]);
		assert.equal(
			fixtureEvents(log).filter((event) => event.input === "/exit").length,
			1,
		);
	});

	it("rejects busy sends and ends an interrupted task without a Stop receipt", async (t) => {
		if (!linux) return t.skip("verified interrupts need /proc ownership");
		const project = scratch("flow-persistent-busy");
		const herdr = useHerdr({
			log: join(project, "..", "busy.json"),
			env: { FAKE_FOLLOW_UP: "hang" },
		});
		await start(project, {
			name: "busy-claude",
			task: "First task",
			agent: "native-persistent",
		});
		await waitForMessage((message) =>
			/"busy-claude" completed task/.test(message.content ?? ""),
		);
		const child = running("busy-claude")!;
		assert.equal(
			testApi.handleSubagentSend({ name: "busy-claude", message: "Long task" })
				.details.outcome,
			"dispatched",
		);
		await waitFor(() => child.native!.driver.turns[1]?.acknowledged === true);
		const busy = testApi.handleSubagentSend({
			name: "busy-claude",
			message: "Third task",
		});
		assert.equal(busy.details.outcome, "rejected-busy");
		const interrupted = testApi.handleSubagentInterrupt(
			{ name: "busy-claude" },
			herdr.interrupt,
		);
		assert.equal(interrupted.details.status, "interrupt_requested");
		await waitForMessage((message) =>
			/"busy-claude" settled \(interrupted\) task/.test(message.content ?? ""),
		);
		// Ended by verified termination: an exit notice with its reason, sent
		// after the interrupted task's own result.
		const ended = await waitForMessage(
			(message) =>
				message.details?.error === "persistent-crash" &&
				message.details?.facts?.sessionFile === child.sessionFile,
		);
		assert.match(
			ended.content,
			/exited without a stop request \(2 settled task result\(s\) delivered before this notice\)\. Reason: [^\n]*interrupted/,
		);
		assert.match(ended.content, /rejected-busy/);
	});
});

describe("native interrupts and interactive sessions", () => {
	it("interrupts a verified live autonomous turn and keeps it resumable", async (t) => {
		if (!linux) return t.skip("verified interrupts need /proc ownership");
		const project = scratch("flow-interrupt");
		const log = join(project, "..", "int.json");
		const herdr = useHerdr({ log, mode: "hang-turn" });
		await start(project, {
			name: "int-claude",
			task: "Long task",
			agent: "native-claude",
		});
		const early = testApi.handleSubagentInterrupt(
			{ name: "int-claude" },
			herdr.interrupt,
		);
		assert.match(early.details.error ?? "", /Nothing was sent/);
		const child = running("int-claude")!;
		await waitFor(() => child.native!.driver.turns[0].acknowledged);
		const unverifiable = testApi.handleNativeInterrupt(
			child,
			() => assert.fail("must not send"),
			{ procRoot: null, uid: null, isAlive: () => true, kill: () => {} },
		);
		assert.match(unverifiable.details.error ?? "", /cannot be verified/);
		const accepted = testApi.handleSubagentInterrupt(
			{ name: "int-claude" },
			herdr.interrupt,
		);
		assert.equal(accepted.details.status, "interrupt_requested");
		const result = await resultFor("int-claude");
		assert.notEqual(result.details.exitCode, 0);
		assert.match(result.content, /was interrupted/);
		assert.equal(result.details.native.interrupted, true);
		assert.equal(result.details.native.processExit, "confirmed");
		assert.equal(result.details.native.resume.available, true);
		assert.ok(fixtureEvents(log).some((event) => event.input === "ESC"));
	});

	it("never auto-exits an interactive session and discloses human turns separately", async () => {
		const project = scratch("flow-interactive");
		const log = join(project, "..", "interactive.json");
		const herdr = useHerdr({ log });
		await start(project, {
			name: "human-claude",
			task: "Pair with the human",
			agent: "native-interactive",
		});
		const child = running("human-claude")!;
		await waitFor(() => child.native!.driver.turns[0].outcome === "completed");
		await new Promise((resolve) => setTimeout(resolve, 150));
		assert.equal(
			fixtureEvents(log).some((event) => event.input === "/exit"),
			false,
		);
		herdr.human(child.surface, "what about tests?");
		await waitFor(() => child.native!.driver.lastState?.untrackedTurns === 1);
		const followUp = testApi.handleSubagentSend({
			name: "human-claude",
			message: "Summarize the plan",
		});
		assert.equal(followUp.details.outcome, "queued");
		await waitFor(() => child.native!.driver.turns[1]?.outcome === "completed");
		herdr.send(child.surface, "/exit"); // the human ends the session
		const result = await resultFor("human-claude");
		assert.equal(result.details.exitCode, 0, result.content);
		assert.match(result.content, /Claude follow-up result 2/);
		assert.equal(result.details.native.humanTurns, 1);
		assert.match(
			result.content,
			/Human-driven turns: 1 \(not part of the orchestrator's result\)/,
		);
		assert.match(
			result.content,
			/disclosure only, not a task result\): Human-driven answer/,
		);
	});
});

describe("native resume", () => {
	it("retains a resumed pane when Claude workspace trust blocks its first turn", async () => {
		const project = scratch("flow-resume-trust");
		useHerdr({ log: join(project, "..", "resume-trust-initial.json") });
		const started = await start(project, {
			name: "resume-trust-source",
			task: "Initial task",
			agent: "native-claude",
		});
		await resultFor("resume-trust-source");

		const log = join(project, "..", "resume-trust.json");
		const terminations: string[] = [];
		const herdr = useHerdr(
			{ log, mode: "workspace-trust" },
			{
				watch: {
					inspectPane: async () => ({
						kind: "present",
						agentStatus: "blocked",
						observedAt: Date.now(),
					}),
					readVisiblePane: async () =>
						"Accessing workspace: /tmp/example\nQuick safety check: Is this a project you created or one you trust?\nClaude Code'll be able to read, edit, and execute files here.\nYes, I trust this folder\nNo, exit",
					terminate: (run) => {
						terminations.push(run.id);
						return terminateProcessRun(run);
					},
				},
			},
		);
		const sentBefore = sent.length;
		const acknowledgement = await resume(project, {
			sessionPath: started.details.sessionFile,
			name: "resume-trust-blocked",
			message: "Continue",
		});
		assert.equal(acknowledgement.details.status, "started");
		const result = await waitForMessage(
			(message) =>
				sent.indexOf(message) >= sentBefore &&
				message.customType === "subagent_result" &&
				message.details?.name === "resume-trust-blocked",
		);
		assert.equal(result.details.native.startupBlock, "claude-workspace-trust");
		assert.equal(result.details.native.resume.available, false);
		assert.equal(terminations.length, 1);
		assert.deepEqual(fixtureEvents(log), [], "no trust choice is typed");
		assert.deepEqual(
			herdr.closed,
			[],
			"the resumed pane remains for manual close",
		);
	});

	it("replays exactly the recorded loadout even after the role widens", async () => {
		const project = scratch("flow-resume");
		const log = join(project, "..", "resume.json");
		useHerdr({ log });
		await start(project, {
			name: "res-claude",
			task: "Initial",
			agent: "native-claude",
			model: "opus",
			thinking: "high",
		});
		const first = await resultFor("res-claude");
		const markerFile = first.details.sessionFile;
		const marker = markerV2(markerFile);
		writeRole("native-claude", [
			"cli: claude",
			"auto-exit: true",
			"tools: read, bash, write, edit",
			"model: sonnet",
		]);
		try {
			const missing = await resume(project, { sessionPath: markerFile });
			assert.match(missing.content[0].text, /non-empty message/);
			const resumed = await resume(project, {
				sessionPath: markerFile,
				name: "res-claude-2",
				message: "Continue",
			});
			assert.equal(resumed.details.status, "started", resumed.content[0].text);
			assert.equal(resumed.details.nativeSessionId, marker.nativeSessionId);
			const second = await resultFor("res-claude-2");
			assert.equal(second.details.exitCode, 0, second.content);
			const launched = JSON.parse(readFileSync(log, "utf8"));
			assert.equal(launched.resumed, true);
			assert.equal(launched.tools, "Read,Bash", "never widened on resume");
			const args: string[] = launched.args;
			assert.equal(args[args.indexOf("--resume") + 1], marker.nativeSessionId);
			assert.equal(args[args.indexOf("--model") + 1], "opus");
			assert.equal(args[args.indexOf("--effort") + 1], "high");
			assert.deepEqual(
				second.details.native.turns.map(
					(turn: any) => `${turn.kind}=${turn.outcome}`,
				),
				["resume=completed"],
			);
			const runs = readFileSync(`${markerFile}.runs.jsonl`, "utf8")
				.trim()
				.split("\n")
				.map((line) => JSON.parse(line));
			assert.deepEqual(
				runs.map((entry) => `${entry.kind}:${entry.event}`),
				["fresh:started", "fresh:settled", "resume:started", "resume:settled"],
			);
			assert.equal(existsSync(`${markerFile}.lease`), false, "lease released");

			// Tampering with the recorded permissions fails closed.
			const tampered = JSON.parse(readFileSync(markerFile, "utf8"));
			tampered.loadout.tools = "read,bash,write";
			writeFileSync(markerFile, JSON.stringify(tampered));
			const rejected = await resume(project, {
				sessionPath: markerFile,
				message: "Again",
			});
			assert.match(
				rejected.content[0].text,
				/integrity hash[\s\S]*Nothing was launched/,
			);
		} finally {
			writeRole("native-claude", [
				"cli: claude",
				"auto-exit: true",
				"tools: read, bash",
			]);
		}
	});

	it("reopens Kiro with its saved agent name and session identity", async () => {
		const project = scratch("flow-resume-kiro");
		const log = join(project, "..", "resume-kiro.json");
		useHerdr({ log });
		await start(project, {
			name: "res-kiro",
			task: "Initial",
			agent: "native-kiro",
		});
		const first = await resultFor("res-kiro");
		const marker = markerV2(first.details.sessionFile);
		assert.equal(
			marker.nativeSessionId,
			"11111111-1111-4111-8111-111111111111",
		);
		const resumed = await resume(project, {
			sessionPath: first.details.sessionFile,
			name: "res-kiro-2",
			message: "Continue",
		});
		assert.equal(resumed.details.status, "started", resumed.content[0].text);
		const second = await resultFor("res-kiro-2");
		assert.equal(second.details.exitCode, 0, second.content);
		const args: string[] = JSON.parse(readFileSync(log, "utf8")).args;
		assert.equal(
			args[args.indexOf("--agent") + 1],
			marker.loadout.kiroAgentName,
		);
		assert.equal(args[args.indexOf("--resume-id") + 1], marker.nativeSessionId);
		assert.equal(existsSync(join(project, ".kiro")), false, "profile released");
	});

	it("refuses concurrent, persistent, and still-leased resumes", async (t) => {
		const project = scratch("flow-resume-lease");
		useHerdr({ log: join(project, "..", "lease.json") });
		await start(project, {
			name: "lease-claude",
			task: "Initial",
			agent: "native-claude",
		});
		const first = await resultFor("lease-claude");
		const markerFile = first.details.sessionFile;
		const herdr = useHerdr({
			log: join(project, "..", "lease2.json"),
			mode: "hang-turn",
		});
		const live = await resume(project, {
			sessionPath: markerFile,
			name: "lease-live",
			message: "Long",
		});
		assert.equal(live.details.status, "started");
		const concurrent = await resume(project, {
			sessionPath: markerFile,
			name: "lease-second",
			message: "Also",
		});
		// The session lease refuses a second driver before any in-process check.
		assert.match(
			concurrent.content[0].text,
			/still leased: run [0-9a-f-]+ may still be driving it[\s\S]*Nothing was launched/,
		);
		const check = checkNativeResume(
			readNativeSessionMarker(markerFile)!,
			markerFile,
		);
		assert.equal(check.ok, false);
		assert.match(check.ok ? "" : check.error, /still leased/);
		const child = running("lease-live")!;
		if (linux) {
			await waitFor(() => child.native!.driver.turns[0].acknowledged);
			testApi.handleSubagentInterrupt({ name: "lease-live" }, herdr.interrupt);
			await resultFor("lease-live");
			assert.equal(existsSync(`${markerFile}.lease`), false);
		} else {
			for (const spawned of herdr.children) killGroup(spawned.pid);
			t.skip("verified interrupts need /proc ownership");
			return;
		}

		useHerdr({ log: join(project, "..", "lease3.json") });
		await start(project, {
			name: "lease-spec",
			task: "x",
			agent: "native-persistent",
		});
		await waitForMessage((message) =>
			/"lease-spec" completed task/.test(message.content ?? ""),
		);
		const spec = running("lease-spec")!;
		const persistentResume = await resume(project, {
			sessionPath: spec.sessionFile,
			message: "revive",
		});
		assert.match(persistentResume.content[0].text, /persistent specialist/);
		testApi.handleSubagentStop({ name: "lease-spec" }, api);
		await waitForMessage(
			(message) =>
				message.customType === "subagent_stop" &&
				message.details?.facts?.sessionFile === spec.sessionFile,
		);
	});

	it("reclaims a crashed parent's stale lease only after confirming exit", async (t) => {
		if (!linux) return t.skip("lease ownership uses /proc");
		const project = scratch("flow-stale-lease");
		useHerdr({ log: join(project, "..", "stale.json") });
		await start(project, {
			name: "stale-claude",
			task: "Initial",
			agent: "native-claude",
		});
		const first = await resultFor("stale-claude");
		const markerFile = first.details.sessionFile;
		const marker = readNativeSessionMarker(markerFile)!;
		const dir = scratch("stale-run");
		const holder = createProcessRun("crashed-run", join(dir, "process.json"));
		const sleeper = spawn("sleep", ["30"], {
			env: { ...process.env, [OWNER_ENV]: holder.ownerToken },
			detached: true,
			stdio: "ignore",
		});
		try {
			writeFileSync(
				holder.receiptFile,
				JSON.stringify({
					version: 1,
					runId: holder.id,
					owner: holder.ownerToken,
					pid: sleeper.pid,
				}),
			);
			writeFileSync(
				`${markerFile}.lease`,
				JSON.stringify({
					version: 1,
					sessionKey: "k",
					runId: holder.id,
					receiptFile: holder.receiptFile,
					ownerToken: holder.ownerToken,
					createdAt: Date.now(),
				}),
			);
			const held = checkNativeResume(marker, markerFile);
			assert.match(
				held.ok ? "" : held.error,
				/crashed-run may still be driving it/,
			);
		} finally {
			killGroup(sleeper.pid);
		}
		await waitFor(() => checkNativeResume(marker, markerFile).ok);
		const resumed = await resume(project, {
			sessionPath: markerFile,
			name: "stale-claude-2",
			message: "Continue",
		});
		assert.equal(resumed.details.status, "started", resumed.content[0].text);
		assert.equal((await resultFor("stale-claude-2")).details.exitCode, 0);
	});

	it("binds a worktree resume to the verified retained checkout and its lease", () => {
		const project = scratch("flow-resume-worktree");
		const baseSha = initRepo(project);
		const tree = join(project, "..", "resume-tree");
		execFileSync(
			"git",
			["worktree", "add", "-q", "-b", "native/resume", tree, baseSha],
			{
				cwd: project,
			},
		);
		const manifestFile = join(scratch("resume-manifest"), "manifest.json");
		const binding = {
			path: tree,
			workspaceId: "ws-r",
			branch: "native/resume",
			baseSha,
			manifestFile,
		};
		writeWorktreeManifest(manifestFile, {
			state: "ready_for_review",
			path: tree,
			branch: "native/resume",
			workspaceId: "ws-r",
			paneId: "root-r",
			baseRef: "HEAD",
		});
		const verified = testApi.verifyResumeWorktree(binding, tree, "/m.json");
		assert.ok("worktree" in verified, JSON.stringify(verified));
		assert.equal(verified.worktree.paneId, "root-r");
		const error = (value: any) => ("error" in value ? value.error : "");
		assert.match(
			error(testApi.verifyResumeWorktree(binding, project, "/m.json")),
			/does not match its cwd/,
		);
		assert.match(
			error(
				testApi.verifyResumeWorktree(
					{ ...binding, branch: "other" },
					tree,
					"/m",
				),
			),
			/disagrees/,
		);
		testApi.runningSubagents.set("wt-holder", {
			id: "wt-holder",
			name: "holder",
			task: "t",
			surface: "p",
			startTime: Date.now(),
			sessionFile: "/x",
			interactive: false,
			runtimePlan: undefined,
			lifecycle: createLifecycle(Date.now()),
			worktree: { ...verified.worktree },
		});
		try {
			assert.match(
				error(testApi.verifyResumeWorktree(binding, tree, "/m.json")),
				/leased by live child "holder"/,
			);
		} finally {
			testApi.runningSubagents.delete("wt-holder");
		}
		execFileSync("git", ["-C", tree, "switch", "-q", "-c", "elsewhere"]);
		assert.match(
			error(testApi.verifyResumeWorktree(binding, tree, "/m.json")),
			/no longer on branch native\/resume/,
		);
		writeWorktreeManifest(manifestFile, { state: "removed" });
		assert.match(
			error(testApi.verifyResumeWorktree(binding, tree, "/m.json")),
			/was removed/,
		);
	});
});

describe("native nested delegation", () => {
	it("serves an authenticated bridge request as a leaf child and returns its result as a turn", async (t) => {
		if (!linux) return t.skip("nested requests need /proc ownership");
		const project = scratch("flow-nested");
		const log = join(project, "..", "nested.json");
		useHerdr({ log, mode: "spawn", env: { FAKE_SPAWN_AGENT: "native-scout" } });
		await start(project, {
			name: "delegator",
			task: "Delegate a probe",
			agent: "native-delegator",
		});
		const result = await resultFor("delegator");
		assert.equal(result.details.exitCode, 0, result.content);
		assert.deepEqual(
			result.details.native.turns.map(
				(turn: any) => `${turn.kind}=${turn.outcome}`,
			),
			["initial=completed", "nested-result=completed"],
		);
		assert.deepEqual(result.details.native.nested, [
			{ name: "delegator/probe", agent: "native-scout", outcome: "completed" },
		]);
		const mcp = fixtureEvents(log).find((event) => event.mcp)?.mcp;
		assert.deepEqual(
			mcp.tools.map((tool: any) => tool.name),
			["subagent"],
		);
		assert.deepEqual(mcp.tools[0].inputSchema.properties.agent.enum, [
			"native-scout",
			"pi-wide",
			"pi-open",
			"native-persistent",
			"native-interactive",
		]);
		assert.equal(mcp.call.isError, false, mcp.call.content[0].text);
		assert.match(
			mcp.call.content[0].text,
			/Launched nested subagent "delegator\/probe"/,
		);
		assert.equal(
			sent.some(
				(message) =>
					message.customType === "subagent_result" &&
					message.details?.name === "delegator/probe",
			),
			false,
			"the nested result goes to the requester, not the parent",
		);
		const markers = readdirSync(
			join(
				parentSession(project).sessionDir,
				"artifacts",
				"parent",
				"native-sessions",
			),
		)
			.filter((name) => name.endsWith(".json"))
			.map((name) =>
				markerV2(
					join(
						parentSession(project).sessionDir,
						"artifacts",
						"parent",
						"native-sessions",
						name,
					),
				),
			);
		const leaf = markers.find((marker) => marker.name === "delegator/probe");
		assert.equal(leaf?.loadout.spawnAgents, null, "nested children are leaves");
		const requester = markers.find((marker) => marker.name === "delegator");
		assert.deepEqual(requester?.loadout.spawnAgents?.length, 5);
	});

	it("rejects delegation outside the allowlist or the requester's capability ceiling", async () => {
		const project = scratch("flow-nested-policy");
		const requester: any = {
			id: "req",
			name: "req",
			agent: "native-delegator",
			task: "t",
			surface: "p",
			startTime: Date.now(),
			sessionFile: "/x",
			interactive: false,
			runtimePlan: undefined,
			lifecycle: createLifecycle(Date.now()),
			native: { driver: { outstandingNested: 0 } },
			nativeDelegation: {
				ctx: ctxFor(project),
				parentThinking: "medium",
				tools: new Set(["read", "bash"]),
				agents: [
					"native-scout",
					"pi-wide",
					"pi-open",
					"native-persistent",
					"native-interactive",
					"native-mcp",
					"native-delegator",
				],
				cwd: project,
				children: new Map(),
				total: 0,
				queue: Promise.resolve(),
			},
		};
		const request = (agent: string) => ({
			nonce: randomUUID().replace(/-/g, ""),
			pid: 1,
			createdAt: Date.now(),
			agent,
			name: "probe",
			task: "t",
		});
		const ended = await testApi.handleNestedSpawnRequest(
			requester,
			request("native-scout"),
		);
		assert.match(ended.text, /has ended/);
		testApi.runningSubagents.set("req", requester);
		try {
			for (const [agent, pattern] of [
				["native-kiro", /not in spawn-agents/],
				["pi-wide", /tools the requester lacks \(write\)/],
				["pi-open", /no explicit tools allowlist/],
				["native-persistent", /persistent roles/],
				["native-interactive", /only autonomous/],
				["native-mcp", /nested roles cannot receive external MCP/],
				["native-delegator", /its own role/],
			] as const) {
				const response = await testApi.handleNestedSpawnRequest(
					requester,
					request(agent),
				);
				assert.equal(response.accepted, false, agent);
				assert.match(response.text, pattern);
			}
			requester.nativeDelegation.total = 16;
			const limit = await testApi.handleNestedSpawnRequest(
				requester,
				request("native-scout"),
			);
			assert.match(limit.text, /per-run limit of 16/);
			requester.nativeDelegation.total = 0;
			for (let index = 0; index < 4; index++)
				requester.nativeDelegation.children.set(`c${index}`, {
					name: `c${index}`,
					agent: "native-scout",
					outcome: "running",
				});
			const concurrent = await testApi.handleNestedSpawnRequest(
				requester,
				request("native-scout"),
			);
			assert.match(concurrent.text, /already running \(limit 4\)/);
		} finally {
			testApi.runningSubagents.delete("req");
		}
	});
});
