// This content is generated by AI (Kiro)
/**
 * End-to-end native flow harness: a mock Pi extension API, role files in the
 * isolated agent directory, and the fake-Herdr test seam driving the offline
 * fixture CLIs through the extension's own tool handlers. Import
 * `./isolated-agent-dir.ts` before this module.
 */
import { after, afterEach } from "node:test";
import assert from "node:assert/strict";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
	SessionManager,
	type ExtensionContext,
	type InputEvent,
	type InputEventResult,
} from "@earendil-works/pi-coding-agent";
import * as subagentsModule from "../pi-extension/subagents/index.ts";
import {
	readNativeSessionMarker,
	type NativeSessionMarker,
} from "../pi-extension/subagents/native-harness.ts";
import {
	fakeHerdr,
	killGroup,
	nativeOperations,
	parentSession,
	waitFor,
	type Harness,
} from "./native-fixtures.ts";

export const testApi = subagentsModule.__test__;
const agentDir = process.env.PI_CODING_AGENT_DIR!;

export function writeRole(name: string, lines: string[]) {
	mkdirSync(join(agentDir, "agents"), { recursive: true });
	writeFileSync(
		join(agentDir, "agents", `${name}.md`),
		`---\nname: ${name}\ndescription: ${name} test role\n${lines.join("\n")}\n---\n\nYou are ${name}.\n`,
	);
}

export const sent: any[] = [];
export const registered: any[] = [];
/** Slash commands registered by the extension, by name. */
export const commands = new Map<string, any>();
/** Messages the extension dispatched through sendUserMessage. */
export const userMessages: string[] = [];
const handlers = new Map<string, Function[]>();
interface SendFailures {
	match?: (message: any) => boolean;
	remaining: number;
}

/** Messages matching this predicate throw from sendMessage (transient failure). */
export const sendFailures: SendFailures = { remaining: 0 };
interface SendHook {
	hook?: (message: any) => void;
}

/** Runs synchronously when sendMessage is entered, before any failure. */
export const beforeSend: SendHook = {};
/** Installed Pi skills reported by the mock API's getCommands(). */
export const skillCommands: Array<{
	name: string;
	source: "skill";
	sourceInfo: { path: string };
}> = [];

export function createApi(
	sink: any[] = sent,
	registry = handlers,
	localTools = registered,
	localCommands = commands,
	localUserMessages = userMessages,
): any {
	// SAFETY: a partial ExtensionAPI with only the members these flows use.
	return {
		on(event: string, handler: Function) {
			registry.set(event, [...(registry.get(event) ?? []), handler]);
		},
		registerTool(tool: any) {
			localTools.push(tool);
		},
		registerCommand(name: string, command: any) {
			localCommands.set(name, command);
		},
		registerMessageRenderer() {},
		registerShortcut() {},
		events: { on() {}, emit() {} },
		getThinkingLevel: () => "medium",
		sendMessage(message: any) {
			beforeSend.hook?.(message);
			if (sendFailures.remaining > 0 && sendFailures.match?.(message)) {
				sendFailures.remaining--;
				throw new Error("transient parent delivery failure");
			}
			sink.push(message);
		},
		sendUserMessage(message: string) {
			localUserMessages.push(message);
		},
		getAllTools: () => [],
		getCommands: () => skillCommands,
	};
}

/**
 * Pi's public ordered input contract, without original-input metadata: each
 * transform feeds the next handler, handled stops the chain, and continue
 * never discards a transform another handler has already made.
 */
export async function runOrderedInput(
	registry: Map<string, Function[]>,
	input: InputEvent,
	ctx: ExtensionContext,
): Promise<InputEventResult> {
	let text = input.text;
	let images = input.images;
	for (const handler of registry.get("input") ?? []) {
		const result: InputEventResult | undefined = await handler(
			{ ...input, text, images },
			ctx,
		);
		if (result?.action === "handled") return result;
		if (result?.action === "transform") {
			text = result.text;
			images = result.images ?? images;
		}
	}
	return text !== input.text || images !== input.images
		? { action: "transform", text, images }
		: { action: "continue" };
}

/** Isolated registrations and real host-owned session appends for input flows. */
export function inputHost(
	project: string,
	persisted = true,
	session?: SessionManager,
) {
	const manager =
		session ?? SessionManager.create(project, join(project, "sessions"));
	if (persisted && !session) {
		manager.appendMessage({
			role: "user",
			content: [{ type: "text", text: "Earlier question." }],
			timestamp: Date.now(),
		});
		manager.appendMessage({
			role: "assistant",
			content: [{ type: "text", text: "Earlier answer." }],
			api: "openai-completions",
			provider: "fake",
			model: "parent",
			usage: {
				input: 0,
				output: 0,
				cacheRead: 0,
				cacheWrite: 0,
				totalTokens: 0,
				cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 },
			},
			stopReason: "stop",
			timestamp: Date.now(),
		});
	}
	const registry = new Map<string, Function[]>();
	const messages: Array<{ message: any; options: any }> = [];
	const tools: any[] = [];
	const localCommands = new Map<string, any>();
	const injectedUserMessages: string[] = [];
	const localApi = createApi(
		[],
		registry,
		tools,
		localCommands,
		injectedUserMessages,
	);
	const state = { idle: true, pending: false, signalReads: 0 };
	const models = ["parent", "exact-2"].map((id) => ({
		provider: "fake",
		id,
		api: "openai-completions",
		reasoning: true,
		input: ["text"],
	}));
	const notices: string[] = [];
	// SAFETY: UI and registry are offline stand-ins; the session manager is
	// the real host implementation. No private session mutation/flush API.
	const ctx: ExtensionContext = {
		mode: "tui",
		cwd: project,
		hasUI: true,
		isIdle: () => state.idle,
		hasPendingMessages: () => state.pending,
		get signal() {
			state.signalReads++;
			return undefined;
		},
		sessionManager: manager,
		model: models[0],
		modelRegistry: {
			find: (provider: string, id: string) =>
				models.find((m) => m.provider === provider && m.id === id),
			getAvailable: () => models,
			hasConfiguredAuth: () => true,
			findOfType: () => {
				throw new Error("unexpected classifier lookup");
			},
			classify: () => {
				throw new Error("unexpected classifier call");
			},
		},
		ui: {
			notify: (text: string) => notices.push(text),
			confirm: async () => false,
			setWidget() {},
			setStatus() {},
			setFooter() {},
		},
	} as any;
	const emit = async (event: string, data: any = {}) => {
		for (const handler of registry.get(event) ?? []) await handler(data, ctx);
	};
	localApi.appendEntry = (customType: string, data: any) =>
		manager.appendCustomEntry(customType, data);
	localApi.sendMessage = (message: any, options: any = {}) => {
		messages.push({ message, options });
		// Idle non-triggering sendMessage appends synchronously in Pi 0.99.1.
		manager.appendCustomMessageEntry(
			message.customType,
			message.content,
			message.display ?? true,
			message.details,
		);
		if (options.triggerTurn) void emit("agent_start");
	};
	const input = (event: InputEvent) => runOrderedInput(registry, event, ctx);
	return {
		api: localApi,
		ctx,
		manager,
		registry,
		messages,
		tools,
		commands: localCommands,
		userMessages: injectedUserMessages,
		state,
		notices,
		input,
		emit,
	};
}

export const api = createApi();
subagentsModule.default(api);

const harnesses: Harness[] = [];
type NativeTestSeam = NonNullable<
	Parameters<typeof testApi.setNativeTestSeam>[0]
>;

export function useHerdr(
	options: Parameters<typeof fakeHerdr>[0],
	seamOverrides: Partial<NativeTestSeam> = {},
): Harness {
	const herdr = fakeHerdr(options);
	harnesses.push(herdr);
	// Watch overrides extend (never replace) the fake Herdr watch seam.
	const { watch, ...overrides } = seamOverrides;
	testApi.setNativeTestSeam({
		operations: herdr.operations,
		nativeOperations,
		watch: {
			send: herdr.send,
			inspectPane: async () => ({
				kind: "present",
				agentStatus: "done",
				observedAt: Date.now(),
			}),
			intervalMs: 20,
			terminationGraceMs: 3_000,
			...watch,
		},
		terminalAvailable: true,
		interruptGraceMs: 400,
		deliveryRetryMs: 50,
		...overrides,
	});
	return herdr;
}

/** Run the extension's session_shutdown handlers as the parent would. */
export async function shutdownParent(reason: string): Promise<void> {
	for (const handler of handlers.get("session_shutdown") ?? [])
		await handler({ reason }, {});
}

/**
 * Run the extension's session_start handlers for a (re)started parent. Only
 * their recovery steps matter here: the later model-catalog refresh needs a
 * full model registry that this harness does not model, so it may reject.
 */
export async function startParentSession(project: string): Promise<void> {
	for (const handler of handlers.get("session_start") ?? [])
		await Promise.resolve(
			handler({ reason: "startup" }, ctxFor(project)),
		).catch(() => undefined);
}

afterEach(() => testApi.setNativeTestSeam(undefined));
after(async () => {
	for (const herdr of harnesses)
		for (const child of herdr.children) killGroup(child.pid);
	for (const handler of handlers.get("session_shutdown") ?? [])
		await handler({ reason: "reload" }, {});
});

export function ctxFor(project: string) {
	const { sessionDir, sessionFile } = parentSession(project);
	return {
		sessionManager: {
			getSessionFile: () => sessionFile,
			getSessionId: () => "parent",
			getSessionDir: () => sessionDir,
		},
		cwd: project,
		model: { provider: "fake", id: "parent" },
		modelRegistry: {
			find: (provider: string, id: string) =>
				provider === "anthropic" && id === "claude-x" ? {} : undefined,
		},
	};
}

export async function waitForMessage(
	match: (message: any) => boolean,
	timeoutMs = 15_000,
): Promise<any> {
	let found: any;
	await waitFor(() => {
		found = sent.find(match);
		return !!found;
	}, timeoutMs);
	return found;
}

export const resultFor = (name: string) =>
	waitForMessage(
		(message) =>
			message.customType === "subagent_result" &&
			message.details?.name === name,
	);

export function fixtureEvents(log: string): any[] {
	try {
		return readFileSync(`${log}.events`, "utf8")
			.trim()
			.split("\n")
			.filter(Boolean)
			.map((line) => JSON.parse(line));
	} catch {
		return [];
	}
}

type StartParams = Parameters<typeof testApi.startSubagentRun>[1];
type StartContext = Parameters<typeof testApi.startSubagentRun>[2];

export async function start(
	project: string,
	params: StartParams,
): Promise<any> {
	const context: StartContext = ctxFor(project);
	const started = await testApi.startSubagentRun(api, params, context);
	assert.equal(
		started.details.status,
		"started",
		JSON.stringify(started.content),
	);
	return started;
}

export function markerV2(path: string): NativeSessionMarker {
	const marker = readNativeSessionMarker(path);
	assert.ok(marker?.version === 2, `expected a v2 native marker at ${path}`);
	return marker;
}

export const running = (name: string) =>
	[...testApi.runningSubagents.values()].find((child) => child.name === name);

export const resumeTool = () =>
	registered.find((tool) => tool.name === "subagent_resume");

export interface ResumeParams {
	sessionPath: string;
	name?: string;
	message?: string;
	autoExit?: boolean;
}

export const resume = (project: string, params: ResumeParams) =>
	resumeTool().execute(
		"call",
		params,
		new AbortController().signal,
		() => {},
		ctxFor(project),
	);
