// This content is generated by AI (Kiro)
import "./isolated-agent-dir.ts";
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { execFileSync, spawn, spawnSync } from "node:child_process";
import { randomUUID } from "node:crypto";
import {
	chmodSync,
	existsSync,
	mkdirSync,
	readFileSync,
	rmSync,
	statSync,
	symlinkSync,
	writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import {
	claudeAdapter,
	claudeCommand,
	claudeTools,
	prepareClaudeRun,
	readClaudeState,
	claudeHookPath,
} from "../pi-extension/subagents/claude.ts";
import {
	cleanupKiroRun,
	kiroAdapter,
	kiroCommand,
	kiroHookPath,
	kiroTools,
	prepareKiroRun,
	readKiroState,
	assertKiroAvailable,
} from "../pi-extension/subagents/kiro.ts";
import {
	createNativeDriver,
	nativeDriverOutcome,
	nativePrompt,
	tickNativeDriver,
} from "../pi-extension/subagents/native-turns.ts";
import {
	cancelMarkerFile,
	confirmProcessExit,
	errorReceiptFile,
	readOwnership,
	readProcessReceipt,
	readProcessRunState,
	scanOwnedProcesses,
	supervisedCommand,
	terminateProcessRun,
	type ProcessInspector,
	type ProcessRun,
} from "../pi-extension/subagents/process-run.ts";
import { stageScript } from "../pi-extension/subagents/terminal.ts";
import {
	readNativeSessionMarker,
	resolveNativeLaunchSpec,
	waitForNativeCompletion,
	type NativeRoleDefinition,
	type NativeRun,
} from "../pi-extension/subagents/native-harness.ts";
import { launchNativeSubagent } from "../pi-extension/subagents/launch.ts";
import { getSubagentSessionPolicyFile } from "../pi-extension/subagents/session.ts";
import { createLifecycle } from "../pi-extension/subagents/lifecycle.ts";
import * as subagentsModule from "../pi-extension/subagents/index.ts";
import type { JsonObject } from "../pi-extension/subagents/type-guards.ts";
import {
	UUID,
	fakeHerdr,
	initRepo,
	killGroup,
	linux,
	nativeOperations,
	nativeRequest,
	processRunIn,
	role,
	runHook,
	scratch,
	waitFor,
	watchDeps,
} from "./native-fixtures.ts";

const testApi = subagentsModule.__test__;
/** Run a supervised command the way a Herdr pane does: `bash <script>`. */
function runSupervised(
	dir: string,
	command: string,
	run: ProcessRun,
	options: { detached?: boolean; sync?: boolean } = {},
) {
	const script = stageScript(supervisedCommand(command, run), {
		scriptPath: join(dir, `${run.id}.sh`),
	});
	if (options.sync) return { script, result: spawnSync("bash", [script]) };
	const child = spawn("bash", [script], {
		detached: options.detached ?? true,
		stdio: "ignore",
	});
	child.unref();
	return { script, child };
}

describe("native harness capability validation", () => {
	it("maps Claude tools strictly", () => {
		assert.equal(
			claudeTools("read, grep, find, write, edit, bash"),
			"Read,Grep,Glob,Write,Edit,Bash",
		);
		assert.equal(claudeTools("find,ls"), "Glob");
		assert.throws(() => claudeTools("ls"), /find with ls/);
		assert.throws(() => claudeTools("read,web_search"), /web_search/);
		assert.throws(() => claudeTools(undefined), /explicit tools allowlist/);
	});

	it("maps Kiro tools strictly", () => {
		assert.deepEqual(kiroTools("read, ls, grep, find, bash"), [
			"fs_read",
			"grep",
			"glob",
			"execute_bash",
		]);
		assert.deepEqual(kiroTools("write,edit"), ["fs_write"]);
		assert.throws(() => kiroTools("write"), /write and edit together/);
		assert.throws(() => kiroTools("ls"), /read with ls/);
		assert.throws(() => kiroTools("read,subagent"), /subagent/);
	});

	it("rejects unrepresentable role capabilities with actionable errors", () => {
		const cases: Array<[Partial<NativeRoleDefinition>, RegExp]> = [
			[{ spawning: true }, /explicit spawn-agents allowlist/],
			[{ spawning: false, spawnAgents: "scout" }, /spawning is false/],
			[{ spawnAgents: "native-worker" }, /itself/],
			[{ spawnAgents: "bad name" }, /invalid spawn-agents/],
			[{ spawnAgents: "scout", persistent: true }, /persistent specialist/],
			[{ tools: "read,caller_ping" }, /caller_ping/],
			[{ tools: "read,subagent_send" }, /Pi orchestration tools/],
			[{ tools: "read,subagent" }, /spawn-agents allowlist instead/],
			[{ tools: undefined }, /explicit tools allowlist/],
			[{ model: "task:everything" }, /supported task categories/],
			[{ model: "opus,opus" }, /duplicate/],
			[{ model: "bad model" }, /native CLI model IDs/],
			[{ thinking: "minimal" }, /thinking level minimal/],
			[{ sessionMode: "sideways" }, /session-mode sideways/],
			[{ cli: "kiro", tools: "read", systemPromptMode: "replace" }, /append/],
		];
		for (const [overrides, pattern] of cases) {
			assert.throws(
				() => resolveNativeLaunchSpec(role(overrides)),
				pattern,
				JSON.stringify(overrides),
			);
		}
	});

	it("accepts second-stage capabilities and resolves the session mode", () => {
		const persistent = resolveNativeLaunchSpec(role({ persistent: true }));
		assert.equal(persistent.mode, "persistent");
		assert.equal(
			resolveNativeLaunchSpec(role({ autoExit: undefined })).mode,
			"interactive",
		);
		assert.equal(resolveNativeLaunchSpec(role()).mode, "autonomous");
		assert.equal(
			resolveNativeLaunchSpec(role(), { persistent: true }).mode,
			"persistent",
		);
		assert.equal(
			resolveNativeLaunchSpec(role({ sessionMode: "lineage-only" }))
				.sessionMode,
			"lineage-only",
		);
		assert.equal(
			resolveNativeLaunchSpec(role(), { fork: true }).sessionMode,
			"fork",
		);
		assert.deepEqual(
			resolveNativeLaunchSpec(role({ skills: "tdd, review,tdd" })).skills,
			["tdd", "review"],
		);
		assert.deepEqual(
			resolveNativeLaunchSpec(role({ spawnAgents: "scout, reviewer" }))
				.spawnAgents,
			["scout", "reviewer"],
		);
		assert.deepEqual(
			resolveNativeLaunchSpec(role({ model: "TASK:Coding" })).modelRequest,
			{ kind: "task", category: "coding" },
		);
		const list = resolveNativeLaunchSpec(role({ model: "opus, sonnet" }));
		assert.deepEqual(list.modelRequest, {
			kind: "list",
			models: ["opus", "sonnet"],
		});
		assert.equal(list.model, "opus");
	});

	it("applies per-call overrides and identity channels", () => {
		const forced = resolveNativeLaunchSpec(role({ sessionMode: "fork" }), {
			fork: false,
			model: "sonnet",
			thinking: "high",
			tools: "read",
		});
		assert.equal(forced.sessionMode, "standalone");
		assert.deepEqual(forced.nativeTools, ["Read"]);
		assert.equal(forced.model, "sonnet");
		assert.equal(forced.thinking, "high");
		// Claude without system-prompt mode folds the body into the task wrapper.
		assert.equal(forced.identity, null);
		assert.equal(forced.identityText, "You are a native worker.");
		assert.equal(forced.roleBlock, "You are a native worker.");
		const appended = resolveNativeLaunchSpec(
			role({ systemPromptMode: "append" }),
		);
		assert.equal(appended.identity, "You are a native worker.");
		assert.equal(appended.roleBlock, "");
		const kiro = resolveNativeLaunchSpec(role({ cli: "kiro", tools: "read" }));
		assert.deepEqual(kiro.nativeTools, ["fs_read"]);
		assert.equal(kiro.identity, "You are a native worker.");
		assert.equal(kiro.promptMode, "append");
	});

	it("rejects an unsupported Kiro CLI version before launch", () => {
		assert.throws(
			() => assertKiroAvailable(() => "kiro-cli 2.27.0"),
			/requires kiro-cli 2\.24-2\.26/,
		);
		assert.throws(
			() => assertKiroAvailable(() => "kiro-cli 2.23.9"),
			/requires kiro-cli 2\.24-2\.26/,
		);
		assert.doesNotThrow(() => assertKiroAvailable(() => "kiro-cli 2.24.7\n"));
		assert.doesNotThrow(() => assertKiroAvailable(() => "kiro-cli 2.26.1\n"));
	});
});

describe("native command construction", () => {
	it("builds a strict interactive Claude command", () => {
		const dir = scratch("claude-command");
		const run = prepareClaudeRun({
			runDir: join(dir, "run"),
			processRun: processRunIn(join(dir, "run")),
			cwd: join(dir, "it's here"),
			sessionId: "33333333-3333-4333-8333-333333333333",
		});
		const token = "99999999-9999-4999-8999-999999999999";
		const command = claudeCommand(
			run,
			nativePrompt("Fix 'quoted' task", token),
			{
				tools: "Read,Bash",
				model: "sonnet",
				thinking: "high",
				identity: "Be careful.",
				promptMode: "append",
			},
		);
		assert.ok(
			command.startsWith(`cd '${join(dir, "it'\\''s here")}' && claude `),
		);
		assert.match(
			command,
			/--permission-mode bypassPermissions --dangerously-skip-permissions --strict-mcp-config --tools 'Read,Bash' --settings '[^']+claude-settings\.json'/,
		);
		assert.doesNotMatch(command, /--mcp-config/, "no MCP servers by default");
		assert.match(command, /--model 'sonnet' --effort 'high'/);
		assert.match(command, /--append-system-prompt 'Be careful\.'/);
		assert.ok(
			command.endsWith(
				`--session-id '33333333-3333-4333-8333-333333333333' '[pi-subagent-turn:${token}] Fix '\\''quoted'\\'' task'`,
			),
			"the single-valued session option must precede the prompt",
		);
		assert.doesNotMatch(command, / -p | --print | --resume /);
		const settings = JSON.parse(readFileSync(run.settingsFile, "utf8"));
		assert.deepEqual(Object.keys(settings.hooks).sort(), [
			"SessionStart",
			"Stop",
			"StopFailure",
			"UserPromptSubmit",
		]);
		assert.match(
			settings.hooks.Stop[0].hooks[0].command,
			/claude-lifecycle\.py/,
		);
		assert.throws(
			() =>
				prepareClaudeRun({
					runDir: join(dir, "run"),
					processRun: processRunIn(join(dir, "run")),
					cwd: dir,
					sessionId: "33333333-3333-4333-8333-333333333333",
				}),
			/EEXIST/,
			"per-run hook files must be exclusively created",
		);
	});

	it("resumes the exact Claude session and loads only the owned bridge", () => {
		const dir = scratch("claude-resume-command");
		const run = prepareClaudeRun({
			runDir: join(dir, "run"),
			processRun: processRunIn(join(dir, "run")),
			cwd: dir,
			sessionId: "33333333-3333-4333-8333-333333333333",
			resume: true,
			mcpServer: {
				name: "pi-subagents",
				command: "python3",
				args: ["/bridge.py", "/cfg.json"],
			},
		});
		const command = claudeCommand(run, "[pi-subagent-turn:t] next", {
			tools: "Read",
		});
		assert.match(
			command,
			/--strict-mcp-config --tools 'Read' --settings '[^']+' --mcp-config '[^']+claude-mcp\.json'/,
		);
		assert.match(
			command,
			/--resume '33333333-3333-4333-8333-333333333333' '\[pi-subagent-turn:t\] next'$/,
		);
		assert.doesNotMatch(command, /--session-id/);
		const mcp = JSON.parse(readFileSync(run.mcpConfigFile!, "utf8"));
		assert.deepEqual(Object.keys(mcp.mcpServers), ["pi-subagents"]);
		assert.equal(statSync(run.mcpConfigFile!).mode & 0o777, 0o600);
	});

	it("builds a strict interactive Kiro V2 command", () => {
		const cwd = scratch("kiro-command");
		const run = prepareKiroRun({
			runDir: join(cwd, "..", "kiro-command-run"),
			processRun: processRunIn(join(cwd, "..", "kiro-command-run")),
			cwd,
			markerFile: join(cwd, "..", "marker.json"),
			tools: ["fs_read"],
		});
		const command = kiroCommand(run, "[pi-subagent-turn:t] Inspect", {
			model: "claude-sonnet-4.5",
			thinking: "low",
		});
		assert.equal(
			command,
			`cd '${cwd}' && kiro-cli chat --v2 --agent '${run.profileName}' --trust-all-tools --model 'claude-sonnet-4.5' --effort 'low' '[pi-subagent-turn:t] Inspect'`,
		);
		cleanupKiroRun(run);
	});

	it("recreates the saved Kiro agent name and session for resume", () => {
		const cwd = scratch("kiro-resume-command");
		const runDir = join(cwd, "..", "kiro-resume-run");
		const agentName = "pi-subagent-12345678-1234-4234-8234-123456789012";
		const run = prepareKiroRun({
			runDir,
			processRun: processRunIn(runDir),
			cwd,
			markerFile: join(runDir, "marker.json"),
			tools: ["fs_read"],
			resume: {
				agentName,
				sessionId: "66666666-6666-4666-8666-666666666666",
			},
		});
		assert.equal(run.profileName, agentName);
		assert.match(
			kiroCommand(run, "[pi-subagent-turn:t] x"),
			/--agent 'pi-subagent-12345678-1234-4234-8234-123456789012' --trust-all-tools --resume-id '66666666-6666-4666-8666-666666666666'/,
		);
		const config = JSON.parse(readFileSync(run.configFile, "utf8"));
		assert.equal(
			config.expected_session_id,
			"66666666-6666-4666-8666-666666666666",
		);
		// The saved profile name is recreated exclusively; a leftover profile
		// (changed by a human, so not cleaned up) makes resume fail closed.
		writeFileSync(run.profilePath, '{"edited":true}\n');
		assert.throws(
			() =>
				prepareKiroRun({
					runDir: join(runDir, "again"),
					processRun: processRunIn(join(runDir, "again")),
					cwd,
					markerFile: join(runDir, "marker.json"),
					tools: ["fs_read"],
					resume: {
						agentName,
						sessionId: "66666666-6666-4666-8666-666666666666",
					},
				}),
			/EEXIST/,
		);
		assert.throws(
			() =>
				prepareKiroRun({
					runDir: join(runDir, "bad"),
					processRun: processRunIn(join(runDir, "bad")),
					cwd,
					markerFile: join(runDir, "marker.json"),
					tools: ["fs_read"],
					resume: { agentName: "../escape", sessionId: "x" },
				}),
			/Invalid saved native Kiro agent name/,
		);
	});
});

describe("native process receipts", () => {
	it("records startup and a non-zero exit atomically", () => {
		const dir = scratch("receipt");
		const run = processRunIn(dir, "receipt-run");
		const { result } = runSupervised(dir, "exit 7", run, { sync: true });
		assert.equal(result?.status, 7);
		assert.equal(readProcessReceipt(run)?.exitCode, 7);
		assert.equal(existsSync(`${run.receiptFile}.tmp`), false);
	});

	it("validates receipt identity including the owner token", () => {
		const dir = scratch("receipt-exit");
		const run = processRunIn(dir, "receipt-run");
		const { result } = runSupervised(
			dir,
			"cd /definitely/missing && true",
			run,
			{ sync: true },
		);
		assert.equal(result?.status, 1);
		const receipt = readProcessReceipt(run);
		assert.equal(receipt?.exitCode, 1);
		assert.equal(receipt?.owner, run.ownerToken);
		assert.ok(Number.isInteger(receipt?.pid));
		assert.equal(readProcessReceipt({ ...run, id: "other" }), null);
		assert.equal(
			readProcessReceipt({ ...run, ownerToken: randomUUID() }),
			null,
			"a receipt from another run's owner is rejected",
		);
		writeFileSync(run.receiptFile, '{"version":1,"runId":"receipt-run"}');
		assert.equal(readProcessReceipt(run), null, "pid and owner are required");
	});

	it("refuses to start without the owner token and honors the cancel marker", () => {
		const dir = scratch("receipt-guards");
		const inline = processRunIn(dir, "inline-run");
		// `bash -c` cannot re-execute itself with the token: it must not start.
		const refused = spawnSync("bash", [
			"-c",
			supervisedCommand("touch ran", inline),
		]);
		assert.equal(refused.status, 125);
		assert.equal(readProcessReceipt(inline), null);

		const cancelled = processRunIn(dir, "cancel-run");
		writeFileSync(cancelMarkerFile(cancelled), "");
		const marker = join(dir, "ran");
		const { result } = runSupervised(dir, `touch '${marker}'`, cancelled, {
			sync: true,
		});
		assert.equal(result?.status, 125);
		assert.equal(existsSync(marker), false, "the native CLI never started");
		assert.equal(readProcessReceipt(cancelled)?.exitCode, 125);
	});

	it("verifies ownership before signalling the owned process group", async (t) => {
		if (!linux) return t.skip("ownership verification uses /proc");
		const dir = scratch("terminate");
		const run = processRunIn(dir, "term-run");
		runSupervised(dir, "sleep 30", run);
		await waitFor(() => readProcessReceipt(run) !== null);
		const pid = readProcessReceipt(run)!.pid;
		assert.equal(readOwnership(pid, run.ownerToken), "owned");
		assert.equal(readOwnership(pid, randomUUID()), "not-owned");
		const termination = terminateProcessRun(run);
		assert.equal(termination.kind, "signalled");
		assert.equal(termination.kind === "signalled" && termination.group, true);
		await waitFor(() => readProcessReceipt(run)?.exitCode !== undefined);
		assert.equal(readProcessReceipt(run)?.exitCode, 143);
		assert.equal(terminateProcessRun(run).kind, "nothing-owned");
		assert.equal(confirmProcessExit(run).kind, "confirmed");
	});

	it("signals only verified token holders outside an owned group", async (t) => {
		if (!linux) return t.skip("ownership verification uses /proc");
		const dir = scratch("terminate-shared");
		const run = processRunIn(dir, "shared-run");
		// Not detached: the wrapper shares this test process's group, which must
		// never be signalled; the verified wrapper and child are signalled.
		const { child } = runSupervised(dir, "sleep 30", run, { detached: false });
		await waitFor(() => readProcessReceipt(run) !== null);
		await waitFor(() => {
			const scan = scanOwnedProcesses(run);
			return scan.kind === "complete" && scan.pids.length >= 2;
		});
		const termination = terminateProcessRun(run);
		assert.equal(termination.kind, "signalled");
		assert.equal(termination.kind === "signalled" && termination.group, false);
		await waitFor(() => readProcessReceipt(run)?.exitCode !== undefined);
		assert.equal(readProcessReceipt(run)?.exitCode, 143);
		child?.unref();
	});

	it("never signals a reused PID that lacks the owner token", async (t) => {
		if (!linux) return t.skip("ownership verification uses /proc");
		const dir = scratch("pid-reuse");
		const run = processRunIn(dir, "reuse-run");
		// An unrelated live process now holds the PID recorded by the receipt.
		const unrelated = spawn("sleep", ["30"], {
			detached: true,
			stdio: "ignore",
		});
		unrelated.unref();
		writeFileSync(
			run.receiptFile,
			JSON.stringify({
				version: 1,
				runId: run.id,
				owner: run.ownerToken,
				pid: unrelated.pid,
			}),
		);
		try {
			assert.equal(readProcessRunState(run).kind, "gone");
			assert.equal(terminateProcessRun(run).kind, "nothing-owned");
			assert.equal(
				spawnSync("kill", ["-0", String(unrelated.pid)]).status,
				0,
				"the unrelated process must survive",
			);
			assert.equal(confirmProcessExit(run).kind, "confirmed");
		} finally {
			killGroup(unrelated.pid);
		}
	});

	it("fails closed when ownership cannot be verified", () => {
		const dir = scratch("unverifiable");
		const run = processRunIn(dir, "nolinux-run");
		writeFileSync(
			run.receiptFile,
			JSON.stringify({
				version: 1,
				runId: run.id,
				owner: run.ownerToken,
				pid: 424242,
			}),
		);
		const killed: number[] = [];
		const noProc: ProcessInspector = {
			procRoot: null,
			uid: 1000,
			isAlive: () => true,
			kill: (pid) => {
				killed.push(pid);
			},
		};
		assert.equal(readOwnership(424242, run.ownerToken, noProc), "unverifiable");
		assert.equal(
			terminateProcessRun(run, "SIGTERM", noProc).kind,
			"unverifiable",
		);
		assert.equal(killed.length, 0);
		assert.deepEqual(readProcessRunState(run, noProc), {
			kind: "running",
			pid: 424242,
			verified: false,
		});
		assert.equal(confirmProcessExit(run, noProc).kind, "unconfirmed");

		// A fake /proc: a mismatched environment is not owned; an unreadable
		// same-user environment is disclosed and never signalled.
		const proc = join(dir, "proc");
		mkdirSync(join(proc, "424242"), { recursive: true });
		writeFileSync(join(proc, "424242", "environ"), "PATH=/bin\0HOME=/x\0");
		mkdirSync(join(proc, "515151"), { recursive: true });
		writeFileSync(join(proc, "515151", "environ"), "");
		chmodSync(join(proc, "515151", "environ"), 0o000);
		// An unrelated process (its own group, parented by init).
		writeFileSync(
			join(proc, "515151", "stat"),
			"515151 (keyring) S 1 515151 1",
		);
		const fakeProc: ProcessInspector = {
			procRoot: proc,
			uid: statSync(proc).uid,
			isAlive: () => true,
			kill: (pid) => {
				killed.push(pid);
			},
		};
		assert.equal(readOwnership(424242, run.ownerToken, fakeProc), "not-owned");
		assert.equal(
			terminateProcessRun(run, "SIGTERM", fakeProc).kind,
			"nothing-owned",
		);
		assert.equal(killed.length, 0);
		const scan = scanOwnedProcesses(run, fakeProc);
		if (process.getuid?.() !== 0) {
			assert.deepEqual(scan, {
				kind: "complete",
				pids: [],
				related: [],
				unreadable: [515151],
				unreadableCount: 1,
			});
		}
	});

	it("fails closed when the wrapper is killed without an exit receipt", async () => {
		const dir = scratch("sigkill");
		const run = processRunIn(dir, "kill-run");
		const { child } = runSupervised(dir, "sleep 30", run);
		await waitFor(() => readProcessReceipt(run) !== null);
		killGroup(child?.pid);
		const nativeRun: NativeRun = {
			version: 1,
			harness: "claude",
			kind: "fresh",
			processRun: run,
			markerFile: join(dir, "marker.json"),
			runDir: dir,
			sessionKey: "kill-run",
			loadoutSha256: "",
			model: null,
			driver: createNativeDriver({
				mode: "autonomous",
				firstTurn: { id: "kill-run", kind: "initial", ackTimeoutMs: 60_000 },
			}),
			claude: prepareClaudeRun({
				runDir: join(dir, "claude"),
				processRun: run,
				cwd: dir,
				sessionId: "12121212-1212-4212-8212-121212121212",
			}),
		};
		const result = await waitForNativeCompletion(
			nativeRun,
			new AbortController().signal,
			{ intervalMs: 20, send() {}, terminate() {} },
		);
		assert.equal(result.reason, "error");
		assert.match(result.errorMessage ?? "", /disappeared/);
		if (linux) assert.equal(result.exit.kind, "confirmed");
	});
});

describe("native correlated completion", () => {
	function claudeFixture(mode: "autonomous" | "interactive" = "autonomous") {
		const dir = scratch("claude-hooks");
		const processRun = processRunIn(join(dir, "run"));
		const sessionId = "44444444-4444-4444-8444-444444444444";
		const run = prepareClaudeRun({
			runDir: join(dir, "run"),
			processRun,
			cwd: dir,
			sessionId,
		});
		const fire = (kind: string, extra: JsonObject = {}) =>
			runHook(claudeHookPath, run.configFile, {
				hook_event_name: kind,
				session_id: sessionId,
				cwd: dir,
				...extra,
			});
		const driver = createNativeDriver({
			mode,
			firstTurn: { id: "run", kind: "initial", ackTimeoutMs: 120_000 },
		});
		driver.turns[0].submittedAt = Date.now();
		const adapter = claudeAdapter(run);
		return { dir, run, processRun, sessionId, fire, driver, adapter };
	}

	it("completes only after a correlated Stop and graceful exit", () => {
		const { run, fire, driver, adapter } = claudeFixture();
		const token = driver.turns[0].token;
		const sent: string[] = [];
		assert.equal(fire("SessionStart").status, 0);
		// A late Stop without a submitted turn cannot produce a result.
		assert.equal(fire("Stop", { last_assistant_message: "stale" }).status, 0);
		assert.equal(readClaudeState(run)?.phase, "ready");
		tickNativeDriver(driver, adapter, (text) => sent.push(text));
		assert.equal(sent.length, 0);
		fire("UserPromptSubmit", { prompt: nativePrompt("task", token) });
		tickNativeDriver(driver, adapter, (text) => sent.push(text));
		assert.equal(sent.length, 0, "an active turn is not complete");
		fire("Stop", { last_assistant_message: "Final summary" });
		tickNativeDriver(driver, adapter, (text) => sent.push(text));
		assert.deepEqual(sent, ["/exit"]);
		assert.equal(
			nativeDriverOutcome(driver, adapter, { reason: "done", exitCode: 1 })
				.completed,
			false,
			"a non-zero exit is not success even after Stop",
		);
		const outcome = nativeDriverOutcome(driver, adapter, {
			reason: "done",
			exitCode: 0,
		});
		assert.equal(outcome.completed, true);
		assert.equal(outcome.summary, "Final summary");
		assert.equal(outcome.neverStarted, false);
	});

	it("rejects untagged or superseding turns in autonomous runs", () => {
		const { run, fire, driver, adapter } = claudeFixture();
		fire("UserPromptSubmit", { prompt: "human input" });
		fire("Stop", { last_assistant_message: "unattributed" });
		assert.equal(readClaudeState(run)?.phase, "untracked");
		assert.throws(
			() => tickNativeDriver(driver, adapter, () => {}),
			/superseded/,
		);
		assert.equal(
			nativeDriverOutcome(driver, adapter, { reason: "done", exitCode: 0 })
				.completed,
			false,
		);
	});

	it("records a correlated StopFailure as a failed turn that may have done work", () => {
		const { fire, driver, adapter } = claudeFixture();
		const token = driver.turns[0].token;
		fire("UserPromptSubmit", { prompt: nativePrompt("task", token) });
		fire("StopFailure", { error: "rate_limit", error_details: "overloaded" });
		const sent: string[] = [];
		tickNativeDriver(driver, adapter, (text) => sent.push(text));
		assert.deepEqual(sent, ["/exit"]);
		const outcome = nativeDriverOutcome(driver, adapter, {
			reason: "done",
			exitCode: 0,
		});
		assert.equal(outcome.completed, false);
		assert.equal(
			outcome.neverStarted,
			false,
			"a StopFailure follows an active turn and never proves no work",
		);
		assert.match(outcome.summary, /rate_limit: overloaded/);
	});

	it("publishes a hook error when the native session identity changes", () => {
		const { run, processRun, fire } = claudeFixture();
		const result = fire("SessionStart", {
			session_id: "55555555-5555-4555-8555-555555555555",
		});
		assert.equal(result.status, 1);
		assert.equal(result.stdout, "", "hooks must never write model context");
		const error = JSON.parse(
			readFileSync(errorReceiptFile(processRun), "utf8"),
		);
		assert.match(error.errorMessage, /native session ID changed/);
		assert.equal(readClaudeState(run), null);
	});

	it("records Kiro identity from owned hooks and never correlates overlapping prompts", () => {
		const cwd = scratch("kiro-hooks");
		const runDir = join(cwd, "..", `${cwd.split("/").pop()}-run`);
		const processRun = processRunIn(runDir);
		const markerFile = join(runDir, "marker.json");
		writeFileSync(
			markerFile,
			JSON.stringify({
				type: "native_session",
				harness: "kiro",
				nativeSessionId: null,
			}),
		);
		const run = prepareKiroRun({
			runDir,
			processRun,
			cwd,
			markerFile,
			tools: ["fs_read"],
		});
		const session = "66666666-6666-4666-8666-666666666666";
		const fire = (kind: string, extra: JsonObject = {}) =>
			runHook(kiroHookPath, run.configFile, {
				hook_event_name: kind,
				session_id: session,
				cwd,
				...extra,
			});
		assert.equal(fire("agentSpawn").status, 0);
		assert.equal(
			JSON.parse(readFileSync(markerFile, "utf8")).nativeSessionId,
			session,
		);
		const token = "88888888-8888-4888-8888-888888888888";
		const prompt = nativePrompt("task", token);
		assert.equal(fire("userPromptSubmit", { prompt }).status, 0);
		assert.equal(readKiroState(run)?.token, token);
		// An overlapping prompt makes the eventual stop unattributable.
		assert.equal(fire("userPromptSubmit", { prompt }).status, 0);
		assert.equal(readKiroState(run)?.token, null);
		assert.equal(fire("stop", { assistant_response: "late" }).status, 0);
		const state = readKiroState(run);
		assert.equal(state?.phase, "untracked");
		assert.equal(state?.untracked_turns, 1);
		assert.equal(state?.untracked_summary, "late");
		assert.equal(existsSync(errorReceiptFile(processRun)), false);
		const adapter = kiroAdapter(run);
		assert.equal(adapter.readState()?.untrackedTurns, 1);
		cleanupKiroRun(run);
	});

	it("never treats Herdr idle/done status as completion", async () => {
		const dir = scratch("herdr-done");
		const run = processRunIn(dir, "live-run");
		// A live wrapper with no correlated turn evidence.
		writeFileSync(
			run.receiptFile,
			JSON.stringify({
				version: 1,
				runId: "live-run",
				owner: run.ownerToken,
				pid: process.pid,
			}),
		);
		const claudeRun = prepareClaudeRun({
			runDir: dir,
			processRun: run,
			cwd: dir,
			sessionId: "77777777-7777-4777-8777-777777777777",
		});
		const controller = new AbortController();
		let inspections = 0;
		const nativeRun: NativeRun = {
			version: 1,
			harness: "claude",
			kind: "fresh",
			processRun: run,
			markerFile: "",
			runDir: dir,
			sessionKey: "live-run",
			loadoutSha256: "",
			model: null,
			driver: createNativeDriver({
				mode: "autonomous",
				firstTurn: { id: "live-run", kind: "initial", ackTimeoutMs: 60_000 },
			}),
			claude: claudeRun,
		};
		nativeRun.driver.turns[0].submittedAt = Date.now();
		const waiting = waitForNativeCompletion(nativeRun, controller.signal, {
			intervalMs: 5,
			inspectEveryTicks: 1,
			inspector: {
				procRoot: null,
				uid: null,
				isAlive: () => true,
				kill: () => assert.fail("must not signal"),
			},
			send: () => assert.fail("must not send input without evidence"),
			terminate: () => assert.fail("must not terminate a healthy run"),
			inspectPane: async () => ({
				kind: "present",
				agentStatus: "done",
				observedAt: Date.now(),
			}),
			onPaneInspection: () => {
				if (++inspections === 20) controller.abort();
			},
		});
		await assert.rejects(waiting, /Aborted/);
	});
});

describe("Kiro owned profile cleanup", () => {
	function prepare(cwd: string) {
		const runDir = join(cwd, "..", `${cwd.split("/").pop()}-run`);
		return prepareKiroRun({
			runDir,
			processRun: processRunIn(runDir),
			cwd,
			markerFile: join(runDir, "marker.json"),
			tools: ["fs_read"],
			identity: "Role",
		});
	}

	it("removes an unchanged profile and only the directories it created", () => {
		const cwd = scratch("kiro-clean");
		const run = prepare(cwd);
		assert.equal(run.createdDirs.length, 2);
		const profile = JSON.parse(readFileSync(run.profilePath, "utf8"));
		assert.equal(profile.prompt, "Role");
		assert.deepEqual(profile.tools, ["fs_read"]);
		cleanupKiroRun(run);
		assert.equal(existsSync(join(cwd, ".kiro")), false);
	});

	it("retains a modified profile and pre-existing user configuration", () => {
		const cwd = scratch("kiro-user");
		mkdirSync(join(cwd, ".kiro", "agents"), { recursive: true });
		writeFileSync(join(cwd, ".kiro", "agents", "mine.json"), "{}");
		const run = prepare(cwd);
		assert.deepEqual(run.createdDirs, []);
		writeFileSync(run.profilePath, '{"edited":true}\n');
		cleanupKiroRun(run);
		assert.equal(readFileSync(run.profilePath, "utf8"), '{"edited":true}\n');
		assert.equal(existsSync(join(cwd, ".kiro", "agents", "mine.json")), true);
	});

	it("refuses symlinked profile directories without writing files", () => {
		const cwd = scratch("kiro-symlink");
		const target = scratch("kiro-symlink-target");
		symlinkSync(target, join(cwd, ".kiro"));
		assert.throws(() => prepare(cwd), /real local directory/);
		assert.deepEqual(
			spawnSync("ls", ["-A", target], { encoding: "utf8" }).stdout,
			"",
		);
	});
});

describe("native ordinary-pane launch", () => {
	for (const harness of ["claude", "kiro"] as const) {
		it(`launches ${harness} in a Herdr pane and delivers the correlated summary`, async () => {
			const project = scratch(`${harness}-pane`);
			writeFileSync(join(project, "AGENTS.md"), "Project rules\n");
			const log = join(project, "..", `${harness}-log.json`);
			const herdr = fakeHerdr({ log });
			const running = await launchNativeSubagent(
				nativeRequest(project, harness),
				herdr.operations,
				nativeOperations,
			);
			assert.deepEqual(herdr.events, ["create:Native worker", "ready", "run"]);
			assert.equal(running.surface, "pane-1");
			assert.equal(running.worktree, undefined);
			const marker = readNativeSessionMarker(running.sessionFile);
			assert.equal(marker?.type, "native_session");
			assert.equal(marker?.harness, harness);
			assert.equal(marker?.version, 2);
			if (marker?.version === 2) {
				assert.equal(marker.loadout.mode, "autonomous");
				assert.equal(marker.loadout.model, "fixture-model");
				assert.match(marker.loadoutSha256, /^[0-9a-f]{64}$/);
			}
			assert.equal(
				existsSync(getSubagentSessionPolicyFile(running.sessionFile)),
				false,
				"native runs must not masquerade as Pi sessions",
			);
			const script = readFileSync(running.launchScriptFile, "utf8");
			assert.match(script, /__pi_write_receipt/);
			assert.match(
				script,
				harness === "claude"
					? /claude --permission-mode/
					: /kiro-cli chat --v2/,
			);

			const result = await testApi.watchNativeSubagent(
				running,
				new AbortController().signal,
				watchDeps(herdr),
			);
			assert.equal(result.exitCode, 0, result.summary);
			assert.equal(
				result.summary,
				harness === "claude" ? "Claude fixture result" : "Kiro fixture result",
			);
			assert.equal(result.errorMessage, undefined);
			assert.equal(result.native?.harness, harness);
			assert.match(result.native?.sessionId ?? "", UUID);
			assert.equal(result.worktree, undefined);
			assert.equal(running.lifecycle.process.kind, "completed");
			assert.deepEqual(herdr.closed, [], "pane closes only after delivery");

			const launched = JSON.parse(readFileSync(log, "utf8"));
			if (harness === "claude") {
				assert.equal(launched.tools, "Read,Bash");
				assert.equal(
					launched.args[launched.args.indexOf("--model") + 1],
					"fixture-model",
				);
				assert.match(
					launched.args.at(-1),
					/Complete your task autonomously[\s\S]*You are a native worker\.|You are a native worker\.[\s\S]*Complete your task autonomously/,
				);
			} else {
				assert.deepEqual(launched.profile.tools, ["fs_read"]);
				assert.deepEqual(launched.profile.resources, ["file://AGENTS.md"]);
				assert.equal(launched.profile.prompt, "You are a native worker.");
				assert.equal(
					existsSync(join(project, ".kiro")),
					false,
					"owned profile cleaned",
				);
			}

			const presentation = testApi.resolveResultPresentation(
				result,
				"Native worker",
			);
			assert.match(presentation, /Native session: /);
			assert.match(presentation, /Native turns: initial=completed/);
			assert.match(presentation, /Resume: subagent_resume\(\{ sessionPath: /);
			assert.doesNotMatch(presentation, /Resume: pi --session/);
		});
	}

	it("fails closed and terminates when human input supersedes the tagged turn", async () => {
		const project = scratch("claude-untagged");
		const herdr = fakeHerdr({
			mode: "untagged",
			log: join(project, "..", "u.json"),
		});
		const running = await launchNativeSubagent(
			nativeRequest(project, "claude"),
			herdr.operations,
			nativeOperations,
		);
		const terminated: string[] = [];
		const result = await testApi.watchNativeSubagent(
			running,
			new AbortController().signal,
			watchDeps(herdr, terminated),
		);
		assert.notEqual(result.exitCode, 0);
		assert.match(result.errorMessage ?? "", /superseded/);
		assert.deepEqual(terminated, [running.native!.processRun.id]);
		assert.equal(running.lifecycle.process.kind, "failed");
	});

	it("fails closed when the process exits without a Stop receipt", async () => {
		const project = scratch("kiro-no-stop");
		const herdr = fakeHerdr({
			mode: "no-stop",
			log: join(project, "..", "n.json"),
		});
		const running = await launchNativeSubagent(
			nativeRequest(project, "kiro"),
			herdr.operations,
			nativeOperations,
		);
		const result = await testApi.watchNativeSubagent(
			running,
			new AbortController().signal,
			watchDeps(herdr),
		);
		assert.equal(result.exitCode, 1);
		assert.match(
			result.errorMessage ?? "",
			/without completing every correlated turn/,
		);
		assert.equal(existsSync(join(project, ".kiro")), false);
	});

	it("checks prerequisites before creating any pane", async () => {
		const project = scratch("kiro-missing");
		const herdr = fakeHerdr({ log: join(project, "..", "m.json") });
		await assert.rejects(
			launchNativeSubagent(nativeRequest(project, "kiro"), herdr.operations, {
				assertAvailable() {
					throw new Error("kiro-cli missing");
				},
				validate() {},
			}),
			/kiro-cli missing/,
		);
		assert.deepEqual(herdr.events, []);
	});

	it("closes its pane and removes the owned profile when validation fails", async () => {
		const project = scratch("kiro-invalid");
		const herdr = fakeHerdr({ log: join(project, "..", "i.json") });
		await assert.rejects(
			launchNativeSubagent(nativeRequest(project, "kiro"), herdr.operations, {
				assertAvailable() {},
				validate() {
					throw new Error("profile rejected");
				},
			}),
			/profile rejected/,
		);
		assert.deepEqual(herdr.closed, ["pane-1"]);
		assert.equal(existsSync(join(project, ".kiro")), false);
	});
});

describe("native worktree launch", () => {
	function gitProject() {
		const project = scratch("native-git");
		execFileSync("git", ["init", "-q", "-b", "main"], { cwd: project });
		for (const [key, value] of [
			["user.email", "test@example.com"],
			["user.name", "Test"],
			["commit.gpgsign", "false"],
		])
			execFileSync("git", ["config", key, value], { cwd: project });
		writeFileSync(join(project, "base.txt"), "base\n");
		execFileSync("git", ["add", "."], { cwd: project });
		execFileSync("git", ["commit", "-qm", "base"], { cwd: project });
		const baseSha = execFileSync("git", ["rev-parse", "HEAD"], {
			cwd: project,
			encoding: "utf8",
		}).trim();
		return { project, baseSha };
	}

	for (const harness of ["claude", "kiro"] as const) {
		it(`runs ${harness} in a managed worktree and retains it with handoff metadata`, async () => {
			const { project, baseSha } = gitProject();
			const worktreePath = join(project, "..", `${harness}-tree`);
			const herdr = fakeHerdr({
				log: join(project, "..", `${harness}-wt.json`),
				createWorktree(_name, cwd, branch, base) {
					herdr.events.push("worktree");
					assert.equal(cwd, project);
					assert.equal(base, baseSha);
					execFileSync(
						"git",
						["worktree", "add", "-q", "-b", branch, worktreePath, base],
						{ cwd: project },
					);
					return {
						path: worktreePath,
						branch,
						workspaceId: "workspace-1",
						paneId: "root-pane-1",
					};
				},
			});
			const request = nativeRequest(project, harness, {
				worktree: { branch: `native/${harness}` },
			});
			const running = await launchNativeSubagent(
				request,
				herdr.operations,
				nativeOperations,
			);
			assert.deepEqual(herdr.events, ["worktree", "ready", "run"]);
			assert.equal(running.surface, "root-pane-1");
			assert.equal(running.worktree?.sessionFile, running.sessionFile);
			const manifestFile = running.worktree!.manifestFile;
			const manifest = JSON.parse(readFileSync(manifestFile, "utf8"));
			assert.equal(manifest.state, "running");
			assert.equal(manifest.harness, harness);
			assert.equal(manifest.sessionFile, running.sessionFile);
			const marker = readNativeSessionMarker(running.sessionFile);
			assert.ok(marker?.version === 2);
			assert.equal(marker.loadout.worktree?.branch, `native/${harness}`);
			assert.equal(marker.loadout.worktree?.manifestFile, manifestFile);

			const result = await testApi.watchNativeSubagent(
				running,
				new AbortController().signal,
				watchDeps(herdr),
			);
			assert.equal(result.exitCode, 0, result.summary);
			assert.equal(result.worktree?.path, worktreePath);
			assert.equal(result.worktree?.branch, `native/${harness}`);
			assert.equal(result.worktree?.baseSha, baseSha);
			assert.equal(result.worktree?.clean, true);
			assert.deepEqual(
				result.worktree?.untrackedFiles,
				[],
				"owned Kiro profiles are removed before worktree state is captured",
			);
			assert.equal(existsSync(worktreePath), true, "worktree retained");
			assert.deepEqual(herdr.closed, [], "worktree root pane is retained");
			assert.equal(
				JSON.parse(readFileSync(manifestFile, "utf8")).state,
				"ready_for_review",
			);
			const presentation = testApi.resolveResultPresentation(
				result,
				"Native worker",
			);
			assert.match(presentation, /Worktree result retained for review/);
			assert.match(presentation, /Native marker: /);
		});
	}

	it("retains a failed worktree manifest when native launch fails after provisioning", async () => {
		const { project } = gitProject();
		const worktreePath = join(project, "..", "failed-tree");
		const herdr = fakeHerdr({
			log: join(project, "..", "f.json"),
			createWorktree(_name, cwd, branch, base) {
				execFileSync(
					"git",
					["worktree", "add", "-q", "-b", branch, worktreePath, base],
					{ cwd },
				);
				return {
					path: worktreePath,
					branch,
					workspaceId: "ws-2",
					paneId: "root-2",
				};
			},
		});
		await assert.rejects(
			launchNativeSubagent(
				nativeRequest(project, "kiro", { worktree: { branch: "native/fail" } }),
				herdr.operations,
				{
					assertAvailable() {},
					validate() {
						throw new Error("profile rejected");
					},
				},
			),
			/worktree retained at .*profile rejected/,
		);
		assert.deepEqual(herdr.closed, []);
		assert.equal(existsSync(join(worktreePath, ".kiro")), false);
		const manifest = JSON.parse(
			readFileSync(
				join(
					project,
					"..",
					`${project.split("/").pop()}-sessions`,
					"artifacts",
					"parent",
					"worktree-runs",
					"native-kiro.json",
				),
				"utf8",
			),
		);
		assert.equal(manifest.state, "failed");
	});
});

describe("native exit confirmation before cleanup", () => {
	it("retains the Kiro profile, pane, and worktree lease when termination is not confirmed", async (t) => {
		if (!linux) return t.skip("verified termination uses /proc");
		const project = scratch("kiro-unconfirmed");
		initRepo(project);
		const worktreePath = join(
			project,
			"..",
			`${project.split("/").pop()}-tree`,
		);
		const herdr = fakeHerdr({
			mode: "ignore-term",
			log: join(project, "..", "unconfirmed.json"),
			createWorktree(_name, cwd, branch, base) {
				execFileSync(
					"git",
					["worktree", "add", "-q", "-b", branch, worktreePath, base],
					{ cwd },
				);
				return {
					path: worktreePath,
					branch,
					workspaceId: "ws-u",
					paneId: "root-u",
				};
			},
		});
		const running = await launchNativeSubagent(
			nativeRequest(project, "kiro", {
				id: "native-unconfirmed",
				worktree: { branch: "native/unconfirmed" },
			}),
			herdr.operations,
			nativeOperations,
		);
		const profile = running.native.kiro!.profilePath;
		try {
			const result = await testApi.watchNativeSubagent(
				running,
				new AbortController().signal,
				{ ...watchDeps(herdr), terminationGraceMs: 400 },
			);
			assert.equal(result.exitCode, 1);
			assert.equal(result.native?.processExit, "unconfirmed");
			assert.match(
				result.errorMessage ?? "",
				/superseded[\s\S]*exit is unconfirmed/,
			);
			assert.match(
				result.native?.warning ?? "",
				/unresolved and treated as failed/,
			);
			assert.ok(result.native?.retained?.includes(profile));
			assert.equal(
				existsSync(profile),
				true,
				"a live Kiro process keeps its profile",
			);
			assert.equal(result.worktree?.clean, null, "Git state is not captured");
			assert.match(result.worktree?.gitError ?? "", /exit is unconfirmed/);
			const manifest = JSON.parse(
				readFileSync(running.worktree!.manifestFile, "utf8"),
			);
			assert.equal(manifest.state, "failed");
			assert.equal(manifest.processExit, "unconfirmed");
			assert.equal(running.lifecycle.process.kind, "failed");
			assert.ok(testApi.unresolvedNativeRuns().has(running.id));
			assert.deepEqual(
				testApi
					.reconcileUnresolvedNativeRuns()
					.map((entry) => entry.worktreePath),
				[worktreePath],
				"the worktree lease remains while the process lives",
			);
			const presentation = testApi.resolveResultPresentation(result, "Native");
			assert.match(presentation, /Warning: native process exit is unconfirmed/);
			assert.match(presentation, /Retained for inspection: /);
			assert.doesNotMatch(presentation, /Resume: pi --session/);
		} finally {
			for (const child of herdr.children) killGroup(child.pid);
		}
		await waitFor(() => testApi.reconcileUnresolvedNativeRuns().length === 0);
		assert.equal(
			existsSync(profile),
			false,
			"released after exit is confirmed",
		);
		assert.equal(testApi.unresolvedNativeRuns().has(running.id), false);
	});

	it("does not remove the profile when the parent aborts a running child", async () => {
		const project = scratch("kiro-abort");
		const herdr = fakeHerdr({
			mode: "hang",
			log: join(project, "..", "abort.json"),
		});
		const running = await launchNativeSubagent(
			nativeRequest(project, "kiro", { id: "native-abort" }),
			herdr.operations,
			nativeOperations,
		);
		const profile = running.native.kiro!.profilePath;
		const controller = new AbortController();
		try {
			await waitFor(
				() => readProcessReceipt(running.native.processRun) !== null,
			);
			const watching = testApi.watchNativeSubagent(
				running,
				controller.signal,
				watchDeps(herdr, []),
			);
			controller.abort();
			const result = await watching;
			assert.equal(result.error, "cancelled");
			assert.equal(result.native?.processExit, "unconfirmed");
			assert.equal(existsSync(profile), true);
			assert.equal(
				readProcessReceipt(running.native.processRun)?.exitCode,
				undefined,
				"parent shutdown does not terminate the child",
			);
		} finally {
			for (const child of herdr.children) killGroup(child.pid);
			await waitFor(() => testApi.reconcileUnresolvedNativeRuns().length === 0);
		}
		assert.equal(existsSync(profile), false);
	});

	it("terminates verified token holders after a lost receipt, then cleans up", async (t) => {
		if (!linux) return t.skip("verified termination uses /proc");
		const project = scratch("kiro-lost-receipt");
		const herdr = fakeHerdr({
			mode: "hang",
			log: join(project, "..", "lost.json"),
		});
		const running = await launchNativeSubagent(
			nativeRequest(project, "kiro", { id: "native-lost" }),
			herdr.operations,
			nativeOperations,
		);
		const processRun = running.native.processRun;
		try {
			const terminated: string[] = [];
			const watching = testApi.watchNativeSubagent(
				running,
				new AbortController().signal,
				watchDeps(herdr, terminated),
			);
			// Lose the receipt only after the watcher (20ms ticks) observed it.
			await waitFor(() => readProcessReceipt(processRun) !== null);
			await new Promise((resolve) => setTimeout(resolve, 200));
			rmSync(processRun.receiptFile);
			const result = await watching;
			assert.deepEqual(terminated, [processRun.id]);
			assert.equal(result.native?.processExit, "confirmed");
			assert.match(result.errorMessage ?? "", /lost its run receipt/);
			assert.equal(readProcessReceipt(processRun)?.exitCode, 143);
			assert.equal(existsSync(join(project, ".kiro")), false);
			assert.equal(testApi.unresolvedNativeRuns().has(running.id), false);
		} finally {
			for (const child of herdr.children) killGroup(child.pid);
		}
	});
});

describe("native script confidentiality", () => {
	it("stages launch scripts 0600 in newly created private directories", () => {
		const dir = scratch("script-perms");
		const script = stageScript("echo secret-task", {
			scriptPath: join(dir, "new", "nested", "run.sh"),
			scriptPreamble: "# preamble",
		});
		assert.equal(statSync(script).mode & 0o777, 0o600);
		assert.equal(statSync(join(dir, "new")).mode & 0o777, 0o700);
		assert.equal(statSync(join(dir, "new", "nested")).mode & 0o777, 0o700);
		assert.equal(
			spawnSync("bash", [script], { encoding: "utf8" }).stdout,
			"secret-task\n",
			"bash runs a script without the execute bit",
		);
		// An existing file is tightened; an existing directory is left alone.
		const shared = join(dir, "shared");
		mkdirSync(shared, { mode: 0o755 });
		chmodSync(shared, 0o755);
		writeFileSync(join(shared, "old.sh"), "", { mode: 0o755 });
		stageScript("true", { scriptPath: join(shared, "old.sh") });
		assert.equal(statSync(join(shared, "old.sh")).mode & 0o777, 0o600);
		assert.equal(statSync(shared).mode & 0o777, 0o755);
	});

	it("writes native launch scripts containing task text as 0600", async () => {
		const project = scratch("native-script-perms");
		const herdr = fakeHerdr({ log: join(project, "..", "perm.json") });
		const running = await launchNativeSubagent(
			nativeRequest(project, "claude", { id: "native-perms" }),
			herdr.operations,
			nativeOperations,
		);
		try {
			assert.match(
				readFileSync(running.launchScriptFile, "utf8"),
				/Implement the bounded change/,
			);
			assert.equal(statSync(running.launchScriptFile).mode & 0o777, 0o600);
			assert.equal(
				statSync(dirname(running.launchScriptFile)).mode & 0o777,
				0o700,
			);
			await testApi.watchNativeSubagent(
				running,
				new AbortController().signal,
				watchDeps(herdr),
			);
		} finally {
			for (const child of herdr.children) killGroup(child.pid);
		}
	});
});

describe("native result rendering", () => {
	function renderResult(details: JsonObject, content: string): string {
		const renderers = new Map<string, any>();
		// SAFETY: rendering uses only registration members of this stand-in.
		subagentsModule.default({
			on() {},
			registerTool() {},
			registerCommand() {},
			registerMessageRenderer(type: string, renderer: any) {
				renderers.set(type, renderer);
			},
			registerShortcut() {},
			events: { on() {}, emit() {} },
			getThinkingLevel: () => "medium",
			sendMessage() {},
			sendUserMessage() {},
		} as any);
		const theme = {
			fg: (_color: string, text: string) => text,
			bg: (_color: string, text: string) => text,
			bold: (text: string) => text,
		};
		return renderers
			.get("subagent_result")(
				{ content, details: { ...details, resultContent: content } },
				{ expanded: true },
				theme,
			)
			.render(200)
			.join("\n");
	}

	it("never renders a pi --session resume command for native markers", () => {
		const markerFile = "/tmp/artifacts/p/native-sessions/abc.json";
		const rendered = renderResult(
			{
				name: "Native",
				exitCode: 0,
				elapsed: 3,
				sessionFile: markerFile,
				native: {
					harness: "kiro",
					sessionId: "11111111-1111-4111-8111-111111111111",
					markerFile,
					processExit: "confirmed",
				},
			},
			`Sub-agent "Native" completed (3s).\n\nDone.\n\nNative harness: Kiro (cli: kiro)\nNative session: x\nNative marker: ${markerFile}`,
		);
		assert.doesNotMatch(rendered, /pi --session/);
		assert.match(
			rendered,
			/Native marker: \/tmp\/artifacts\/p\/native-sessions\/abc\.json/,
		);
		assert.match(
			rendered,
			/Resume: unavailable \(spawn a new subagent\)/,
			"a marker without resume availability is never offered for resume",
		);
		assert.match(rendered, /Done\./);
		const resumable = renderResult(
			{
				name: "Native",
				exitCode: 0,
				elapsed: 3,
				sessionFile: markerFile,
				native: {
					harness: "claude",
					sessionId: "11111111-1111-4111-8111-111111111111",
					markerFile,
					processExit: "confirmed",
					resume: { available: true },
				},
			},
			"Done.",
		);
		assert.match(resumable, /Resume: subagent_resume with this marker/);
		assert.doesNotMatch(resumable, /pi --session/);
	});

	it("keeps Pi session rendering unchanged", () => {
		const rendered = renderResult(
			{ name: "Pi", exitCode: 0, elapsed: 3, sessionFile: "/tmp/s.jsonl" },
			'Sub-agent "Pi" completed (3s).\n\nDone.\n\nSession: /tmp/s.jsonl\nResume: pi --session /tmp/s.jsonl',
		);
		assert.match(rendered, /Session: \/tmp\/s\.jsonl/);
		assert.match(rendered, /Resume: {2}pi --session \/tmp\/s\.jsonl/);
		assert.doesNotMatch(rendered, /Native/);
	});
});

describe("native parent tool surfaces", () => {
	it("refuses interrupts without verified live ownership and v1 marker resume", async () => {
		const markerDir = scratch("resume-marker");
		const markerFile = join(markerDir, "marker.json");
		writeFileSync(
			markerFile,
			JSON.stringify({ version: 1, type: "native_session", harness: "claude" }),
		);
		const processRun = processRunIn(markerDir);
		testApi.runningSubagents.set("native-x", {
			id: "native-x",
			name: "Native X",
			task: "t",
			surface: "pane-x",
			startTime: Date.now(),
			sessionFile: markerFile,
			interactive: false,
			runtimePlan: undefined,
			lifecycle: createLifecycle(Date.now()),
			native: {
				version: 1,
				harness: "claude",
				kind: "fresh",
				processRun,
				markerFile,
				runDir: markerDir,
				sessionKey: "native-x",
				loadoutSha256: "",
				model: null,
				driver: createNativeDriver({
					mode: "autonomous",
					firstTurn: { id: "native-x", kind: "initial", ackTimeoutMs: 1000 },
				}),
			},
		});
		try {
			const interrupted = testApi.handleSubagentInterrupt(
				{ name: "Native X" },
				() => assert.fail("must not send Escape without a live owned run"),
			);
			assert.match(
				interrupted.details.error ?? "",
				/process is not running[\s\S]*Nothing was sent/,
			);
		} finally {
			testApi.runningSubagents.delete("native-x");
		}

		const registered: any[] = [];
		// SAFETY: the resume tool only uses registration and messaging members,
		// all provided by this minimal ExtensionAPI stand-in.
		subagentsModule.default({
			on() {},
			registerTool(tool: any) {
				registered.push(tool);
			},
			registerCommand() {},
			registerMessageRenderer() {},
			registerShortcut() {},
			events: { on() {}, emit() {} },
			getThinkingLevel: () => "medium",
			sendMessage() {},
			sendUserMessage() {},
		} as any);
		const resume = registered.find((tool) => tool.name === "subagent_resume");
		const resumed = await resume.execute(
			"call",
			{ sessionPath: markerFile, message: "continue" },
			new AbortController().signal,
			() => {},
			{},
		);
		assert.equal(resumed.details.error, "native-resume-rejected");
		assert.match(
			resumed.content[0].text,
			/marker v1[\s\S]*Nothing was launched/,
		);
	});
});
