// This content is generated by AI (Kiro)
/**
 * Native interactive Claude Code TUI adapter. No -p/stream-JSON/SDK or
 * screen-extraction fallback: completion requires correlated Stop hook
 * receipts for the launched session plus process exit. Turn driving is shared
 * with Kiro in native-turns.ts.
 *
 * Ported from zhengfran/pi-interactive-subagents (MIT, Copyright (c) 2026
 * HazAT and contributors), `pi-extension/subagents/claude.ts`.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { errorReceiptFile, type ProcessRun } from "./process-run.ts";
import { shellQuote } from "./terminal.ts";
import { isNonEmptyString, isString } from "./type-guards.ts";
import type { NativeHookState, NativeTurnAdapter } from "./native-turns.ts";

export const claudeHookPath = join(
	dirname(fileURLToPath(import.meta.url)),
	"plugin/hooks/claude-lifecycle.py",
);
const UUID = /^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$/;
export const isNativeUuid = (value: any): value is string =>
	isString(value) && UUID.test(value);
/** Launch may wait on a human-only startup dialog (workspace trust, login). */
export const CLAUDE_START_ACK_MS = 120_000;
export const CLAUDE_FOLLOW_UP_ACK_MS = 30_000;
export const CLAUDE_EXIT_MS = 15_000;
export const NATIVE_EFFORT_LEVELS = [
	"low",
	"medium",
	"high",
	"xhigh",
	"max",
] as const;

const CLAUDE_TOOL_MAP = new Map([
	["read", "Read"],
	["write", "Write"],
	["edit", "Edit"],
	["bash", "Bash"],
	["grep", "Grep"],
	["find", "Glob"],
	["ls", "Glob"],
]);

/** Fail closed when a Pi tool allowlist cannot be represented natively. */
export function claudeTools(tools: string | undefined): string {
	if (!tools?.trim())
		throw new Error(
			"Claude roles require an explicit tools allowlist (read, write, edit, bash, grep, find, ls).",
		);
	const parsed = tools
		.split(",")
		.map((tool) => tool.trim())
		.filter(Boolean);
	const unknown = parsed.filter((tool) => !CLAUDE_TOOL_MAP.has(tool));
	if (!parsed.length || unknown.length)
		throw new Error(
			`Claude cannot safely map Pi tools: ${unknown.join(", ")}. Supported: ${[...CLAUDE_TOOL_MAP.keys()].join(", ")}.`,
		);
	// Claude has no directory-listing tool; Glob also searches recursively like
	// Pi's find. Do not silently grant an ls-only role recursive search.
	if (parsed.includes("ls") && !parsed.includes("find"))
		throw new Error(
			"Claude requires find with ls (both map to the native Glob tool).",
		);
	return [...new Set(parsed.map((tool) => CLAUDE_TOOL_MAP.get(tool)))].join(
		",",
	);
}

export interface ClaudeState {
	version: 1;
	run_id: string;
	session_id: string;
	phase: "ready" | "active" | "stopped" | "failed" | "untracked";
	token: string | null;
	summary?: string | null;
	error?: string | null;
	untracked_summary?: string | null;
	untracked_turns?: number;
}

export interface ClaudeRun {
	harness: "claude";
	id: string;
	cwd: string;
	sessionId: string;
	/** Reopen an existing native session with --resume instead of --session-id. */
	resume: boolean;
	settingsFile: string;
	configFile: string;
	stateFile: string;
	/** Owned MCP configuration carrying only the nested-spawn bridge. */
	mcpConfigFile?: string;
}

/**
 * Per-run, exclusively created hook settings/config/state. A shared settings
 * file would let a concurrent launch (or Claude's settings hot-reload) retarget
 * another child's hooks. User/global/project settings are never edited.
 */
export function prepareClaudeRun(options: {
	runDir: string;
	processRun: ProcessRun;
	cwd: string;
	sessionId: string;
	resume?: boolean;
	mcpServer?: { name: string; command: string; args: string[] };
}): ClaudeRun {
	if (!isNativeUuid(options.sessionId))
		throw new Error("Invalid native Claude session ID.");
	mkdirSync(options.runDir, { recursive: true, mode: 0o700 });
	const run: ClaudeRun = {
		harness: "claude",
		id: options.processRun.id,
		cwd: resolve(options.cwd),
		sessionId: options.sessionId,
		resume: options.resume === true,
		settingsFile: join(options.runDir, "claude-settings.json"),
		configFile: join(options.runDir, "hook-config.json"),
		stateFile: join(options.runDir, "state.json"),
	};
	writeFileSync(
		run.configFile,
		JSON.stringify({
			version: 1,
			run_id: run.id,
			expected_session_id: run.sessionId,
			state_file: run.stateFile,
			error_file: errorReceiptFile(options.processRun),
		}),
		{ flag: "wx", mode: 0o600 },
	);
	const command = `python3 ${shellQuote(claudeHookPath)} ${shellQuote(run.configFile)}`;
	const hook = [{ hooks: [{ type: "command", command, timeout: 10 }] }];
	writeFileSync(
		run.settingsFile,
		`${JSON.stringify(
			{
				hooks: {
					SessionStart: hook,
					UserPromptSubmit: hook,
					Stop: hook,
					StopFailure: hook,
				},
			},
			null,
			2,
		)}\n`,
		{ flag: "wx", mode: 0o600 },
	);
	if (options.mcpServer) {
		run.mcpConfigFile = join(options.runDir, "claude-mcp.json");
		writeFileSync(
			run.mcpConfigFile,
			`${JSON.stringify(
				{
					mcpServers: {
						[options.mcpServer.name]: {
							type: "stdio",
							command: options.mcpServer.command,
							args: options.mcpServer.args,
						},
					},
				},
				null,
				2,
			)}\n`,
			{ flag: "wx", mode: 0o600 },
		);
	}
	return run;
}

export function readClaudeState(run: ClaudeRun): ClaudeState | null {
	try {
		const data = JSON.parse(readFileSync(run.stateFile, "utf8"));
		if (
			data.version !== 1 ||
			data.run_id !== run.id ||
			data.session_id !== run.sessionId ||
			!["ready", "active", "stopped", "failed", "untracked"].includes(
				data.phase,
			) ||
			(data.token !== null && !isNativeUuid(data.token))
		)
			return null;
		if (
			data.phase === "stopped" &&
			(!isNonEmptyString(data.summary?.trim()) || !data.token)
		)
			return null;
		return data;
	} catch {
		return null;
	}
}

export function claudeCommand(
	run: ClaudeRun,
	taggedPrompt: string,
	options: {
		tools: string;
		model?: string | null;
		thinking?: string | null;
		identity?: string | null;
		promptMode?: "append" | "replace" | null;
	},
): string {
	// Autonomous children cannot answer approval prompts. Bypass approvals for
	// the explicit --tools allowlist only; unavailable tools stay unavailable.
	// --strict-mcp-config loads only the owned MCP configuration, if any: no
	// inherited user/project/plugin servers.
	const args = [
		"claude",
		"--permission-mode",
		"bypassPermissions",
		"--dangerously-skip-permissions",
		"--strict-mcp-config",
		"--tools",
		shellQuote(options.tools),
		"--settings",
		shellQuote(run.settingsFile),
	];
	if (run.mcpConfigFile)
		args.push("--mcp-config", shellQuote(run.mcpConfigFile));
	if (options.model) args.push("--model", shellQuote(options.model));
	if (options.thinking) args.push("--effort", shellQuote(options.thinking));
	if (options.identity)
		args.push(
			options.promptMode === "replace"
				? "--system-prompt"
				: "--append-system-prompt",
			shellQuote(options.identity),
		);
	// Single-valued option last, so no variadic option can consume the prompt.
	args.push(
		run.resume ? "--resume" : "--session-id",
		shellQuote(run.sessionId),
	);
	args.push(shellQuote(taggedPrompt));
	return `cd ${shellQuote(run.cwd)} && ${args.join(" ")}`;
}

export function claudeAdapter(run: ClaudeRun): NativeTurnAdapter {
	return {
		harness: "claude",
		label: "Claude Code",
		exitCommand: "/exit",
		exitTimeoutMs: CLAUDE_EXIT_MS,
		followUpAckTimeoutMs: CLAUDE_FOLLOW_UP_ACK_MS,
		readState(): NativeHookState | null {
			const state = readClaudeState(run);
			if (!state) return null;
			return {
				sessionId: state.session_id,
				phase: state.phase,
				token: state.token,
				summary: state.summary ?? null,
				error: state.error ?? null,
				untrackedSummary: state.untracked_summary ?? null,
				untrackedTurns: state.untracked_turns ?? 0,
			};
		},
	};
}
