// This content is generated by AI (Kiro)
/**
 * Native interactive Claude Code TUI harness (fresh autonomous runs only).
 * No -p/stream-JSON/SDK or screen-extraction fallback: completion requires a
 * correlated Stop hook receipt for the launched session plus process exit.
 *
 * Ported from zhengfran/pi-interactive-subagents (MIT, Copyright (c) 2026
 * HazAT and contributors), `pi-extension/subagents/claude.ts`. Follow-up
 * queues and native resume were removed for this first stage.
 */
import { randomUUID } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { errorReceiptFile, type ProcessRun } from "./process-run.ts";
import { shellQuote } from "./terminal.ts";
import { isNonEmptyString, isString } from "./type-guards.ts";

export const claudeHookPath = join(
	dirname(fileURLToPath(import.meta.url)),
	"plugin/hooks/claude-lifecycle.py",
);
const UUID = /^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$/;
export const isNativeUuid = (value: any): value is string =>
	isString(value) && UUID.test(value);
/** Launch may wait on a human-only startup dialog (workspace trust, login). */
export const CLAUDE_START_ACK_MS = 120_000;
export const CLAUDE_EXIT_MS = 15_000;
export const NATIVE_EFFORT_LEVELS = [
	"low",
	"medium",
	"high",
	"xhigh",
	"max",
] as const;

export function nativePrompt(task: string, token: string): string {
	return `[pi-subagent-turn:${token}] ${task}`;
}

const CLAUDE_TOOL_MAP = new Map([
	["read", "Read"],
	["write", "Write"],
	["edit", "Edit"],
	["bash", "Bash"],
	["grep", "Grep"],
	["find", "Glob"],
	["ls", "Glob"],
]);

/** Correlated native outcome; only `completed` results are successes. */
export interface NativeTurnOutcome {
	completed: boolean;
	summary: string;
}

/** Fail closed when a Pi tool allowlist cannot be represented natively. */
export function claudeTools(tools: string | undefined): string {
	if (!tools?.trim())
		throw new Error(
			"Claude roles require an explicit tools allowlist (read, write, edit, bash, grep, find, ls).",
		);
	const parsed = tools
		.split(",")
		.map((tool) => tool.trim())
		.filter(Boolean);
	const unknown = parsed.filter((tool) => !CLAUDE_TOOL_MAP.has(tool));
	if (!parsed.length || unknown.length)
		throw new Error(
			`Claude cannot safely map Pi tools: ${unknown.join(", ")}. Supported: ${[...CLAUDE_TOOL_MAP.keys()].join(", ")}.`,
		);
	// Claude has no directory-listing tool; Glob also searches recursively like
	// Pi's find. Do not silently grant an ls-only role recursive search.
	if (parsed.includes("ls") && !parsed.includes("find"))
		throw new Error(
			"Claude requires find with ls (both map to the native Glob tool).",
		);
	return [...new Set(parsed.map((tool) => CLAUDE_TOOL_MAP.get(tool)))].join(
		",",
	);
}

export interface ClaudeState {
	version: 1;
	run_id: string;
	session_id: string;
	phase: "ready" | "active" | "stopped" | "failed" | "untracked";
	token: string | null;
	summary?: string | null;
	error?: string | null;
}

export interface ClaudeRun {
	harness: "claude";
	id: string;
	cwd: string;
	sessionId: string;
	settingsFile: string;
	configFile: string;
	stateFile: string;
	expectedToken: string;
	submittedAt: number;
	ackTimeoutMs: number;
	acknowledged: boolean;
	quittingAt?: number;
}

/**
 * Per-run, exclusively created hook settings/config/state. A shared settings
 * file would let a concurrent launch (or Claude's settings hot-reload) retarget
 * another child's hooks. User/global/project settings are never edited.
 */
export function prepareClaudeRun(options: {
	runDir: string;
	processRun: ProcessRun;
	cwd: string;
	sessionId: string;
	now?: number;
}): ClaudeRun {
	if (!isNativeUuid(options.sessionId))
		throw new Error("Invalid native Claude session ID.");
	mkdirSync(options.runDir, { recursive: true, mode: 0o700 });
	const run: ClaudeRun = {
		harness: "claude",
		id: options.processRun.id,
		cwd: resolve(options.cwd),
		sessionId: options.sessionId,
		settingsFile: join(options.runDir, "claude-settings.json"),
		configFile: join(options.runDir, "hook-config.json"),
		stateFile: join(options.runDir, "state.json"),
		expectedToken: randomUUID(),
		submittedAt: options.now ?? Date.now(),
		ackTimeoutMs: CLAUDE_START_ACK_MS,
		acknowledged: false,
	};
	writeFileSync(
		run.configFile,
		JSON.stringify({
			version: 1,
			run_id: run.id,
			expected_session_id: run.sessionId,
			state_file: run.stateFile,
			error_file: errorReceiptFile(options.processRun),
		}),
		{ flag: "wx", mode: 0o600 },
	);
	const command = `python3 ${shellQuote(claudeHookPath)} ${shellQuote(run.configFile)}`;
	const hook = [{ hooks: [{ type: "command", command, timeout: 10 }] }];
	writeFileSync(
		run.settingsFile,
		`${JSON.stringify(
			{
				hooks: {
					SessionStart: hook,
					UserPromptSubmit: hook,
					Stop: hook,
					StopFailure: hook,
				},
			},
			null,
			2,
		)}\n`,
		{ flag: "wx", mode: 0o600 },
	);
	return run;
}

export function readClaudeState(run: ClaudeRun): ClaudeState | null {
	try {
		const data = JSON.parse(readFileSync(run.stateFile, "utf8"));
		if (
			data.version !== 1 ||
			data.run_id !== run.id ||
			data.session_id !== run.sessionId ||
			!["ready", "active", "stopped", "failed", "untracked"].includes(
				data.phase,
			) ||
			(data.token !== null && !isNativeUuid(data.token))
		)
			return null;
		if (
			data.phase === "stopped" &&
			(!isNonEmptyString(data.summary?.trim()) || !data.token)
		)
			return null;
		return data;
	} catch {
		return null;
	}
}

export function claudeCommand(
	run: ClaudeRun,
	task: string,
	options: {
		tools: string;
		model?: string | null;
		thinking?: string | null;
		identity?: string | null;
		promptMode?: "append" | "replace" | null;
	},
): string {
	// Autonomous children cannot answer approval prompts. Bypass approvals for
	// the explicit --tools allowlist only; unavailable tools stay unavailable.
	// --strict-mcp-config without --mcp-config loads zero MCP servers, including
	// inherited user/project/plugin configuration.
	const args = [
		"claude",
		"--permission-mode",
		"bypassPermissions",
		"--dangerously-skip-permissions",
		"--strict-mcp-config",
		"--tools",
		shellQuote(options.tools),
		"--settings",
		shellQuote(run.settingsFile),
	];
	if (options.model) args.push("--model", shellQuote(options.model));
	if (options.thinking) args.push("--effort", shellQuote(options.thinking));
	if (options.identity)
		args.push(
			options.promptMode === "replace"
				? "--system-prompt"
				: "--append-system-prompt",
			shellQuote(options.identity),
		);
	// Single-valued option last, so no variadic option can consume the prompt.
	args.push("--session-id", shellQuote(run.sessionId));
	args.push(shellQuote(nativePrompt(task, run.expectedToken)));
	return `cd ${shellQuote(run.cwd)} && ${args.join(" ")}`;
}

/**
 * Exit an autonomous run with /exit once its correlated turn has stopped so
 * native history persists before the process receipt reports exit. Human input
 * that supersedes the tagged turn makes completion ambiguous and fails closed.
 */
export function tickClaudeRun(
	run: ClaudeRun,
	send: (text: string) => void,
	now = Date.now(),
): void {
	if (run.quittingAt !== undefined) {
		if (now - run.quittingAt > CLAUDE_EXIT_MS)
			throw new Error(
				"Claude Code did not exit after /exit; native session persistence is unconfirmed.",
			);
		return;
	}
	const state = readClaudeState(run);
	if (state?.token === run.expectedToken && state.phase !== "ready")
		run.acknowledged = true;
	if (!run.acknowledged && now - run.submittedAt > run.ackTimeoutMs) {
		throw new Error(
			`Claude Code did not acknowledge the tagged prompt within ${Math.round(run.ackTimeoutMs / 1000)} seconds ` +
				"(hooks disabled, or a startup dialog such as workspace trust is waiting for a human). No dialog was answered.",
		);
	}
	if (!state) return;
	if (
		state.phase !== "ready" &&
		(!state.token || (run.acknowledged && state.token !== run.expectedToken))
	) {
		throw new Error(
			"Unexpected human input superseded the autonomous Claude turn; refusing ambiguous completion.",
		);
	}
	const current = state.token === run.expectedToken;
	if (current && (state.phase === "stopped" || state.phase === "failed")) {
		run.quittingAt = now;
		send("/exit");
	}
}

/** Only the current run's correlated final Stop plus a clean exit succeeds. */
export function claudeOutcome(
	run: ClaudeRun,
	exit: { reason: string; exitCode: number; errorMessage?: string },
): NativeTurnOutcome {
	const state = readClaudeState(run);
	const current = state?.token === run.expectedToken;
	if (
		exit.reason !== "error" &&
		exit.exitCode === 0 &&
		current &&
		state?.phase === "stopped" &&
		state.summary
	) {
		return { completed: true, summary: state.summary.trim() };
	}
	const reason =
		current && state?.phase === "failed"
			? `turn failed: ${state.error ?? "unknown error"}`
			: (exit.errorMessage ?? `shell exit ${exit.exitCode}`);
	return {
		completed: false,
		summary: `Claude Code exited without a correlated final Stop receipt (${reason}).`,
	};
}
