// This content is generated by AI (Kiro)
/**
 * Native interactive Kiro CLI 2.24-2.26 V2 adapter. No ACP/headless/screen-
 * extraction fallback: completion requires correlated stop hook receipts for
 * the owned profile plus process exit. Turn driving is shared with Claude in
 * native-turns.ts.
 *
 * Ported from zhengfran/pi-interactive-subagents (MIT, Copyright (c) 2026
 * HazAT and contributors), `pi-extension/subagents/kiro.ts`.
 */
import { execFileSync } from "node:child_process";
import { createHash, randomUUID } from "node:crypto";
import {
	existsSync,
	lstatSync,
	mkdirSync,
	readFileSync,
	rmdirSync,
	unlinkSync,
	writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { isNativeUuid } from "./claude.ts";
import { isNonEmptyString } from "./type-guards.ts";
import { errorReceiptFile, type ProcessRun } from "./process-run.ts";
import { shellQuote } from "./terminal.ts";
import type { NativeHookState, NativeTurnAdapter } from "./native-turns.ts";

export const kiroHookPath = join(
	dirname(fileURLToPath(import.meta.url)),
	"plugin/hooks/kiro-lifecycle.py",
);
const hash = (text: string) => createHash("sha256").update(text).digest("hex");
export const KIRO_ACK_MS = 30_000;
export const KIRO_EXIT_MS = 15_000;
export const KIRO_AGENT_NAME = /^pi-subagent-[0-9a-f-]{36}$/;

const KIRO_TOOL_MAP = new Map([
	["read", "fs_read"],
	["ls", "fs_read"],
	["write", "fs_write"],
	["edit", "fs_write"],
	["bash", "execute_bash"],
	["grep", "grep"],
	["find", "glob"],
]);

/** Fail closed when a Pi tool allowlist cannot be represented natively. */
export function kiroTools(tools: string | undefined): string[] {
	if (!tools?.trim())
		throw new Error(
			"Kiro roles require an explicit tools allowlist (read, write, edit, bash, grep, find, ls).",
		);
	const parsed = tools
		.split(",")
		.map((tool) => tool.trim())
		.filter(Boolean);
	const unknown = parsed.filter((tool) => !KIRO_TOOL_MAP.has(tool));
	if (!parsed.length || unknown.length)
		throw new Error(
			`Kiro cannot safely map Pi tools: ${unknown.join(", ")}. Supported: ${[...KIRO_TOOL_MAP.keys()].join(", ")}.`,
		);
	// Kiro's fs_write exposes both file creation and editing. Do not silently
	// grant a write-only or edit-only role the other capability.
	if (parsed.includes("write") !== parsed.includes("edit"))
		throw new Error(
			"Kiro requires write and edit together (one native fs_write tool).",
		);
	if (parsed.includes("ls") && !parsed.includes("read"))
		throw new Error("Kiro requires read with ls (one native fs_read tool).");
	return [...new Set(parsed.flatMap((tool) => KIRO_TOOL_MAP.get(tool) ?? []))];
}

export type ExecFile = (
	file: string,
	args: readonly string[],
	options: { timeout: number },
) => string;

const defaultExecFile: ExecFile = (file, args, options) =>
	execFileSync(file, args, {
		encoding: "utf8",
		timeout: options.timeout,
		stdio: "pipe",
	});

export function assertKiroAvailable(exec: ExecFile = defaultExecFile): void {
	let version: string;
	try {
		version = exec("kiro-cli", ["--version"], { timeout: 5000 }).trim();
	} catch (error) {
		throw new Error(
			`Kiro CLI is unavailable: ${error instanceof Error ? error.message : String(error)}. Install kiro-cli 2.24-2.26 and ensure it is on PATH.`,
		);
	}
	// Versions whose V2 flags, profile schema, hooks, and resume were verified.
	if (!/^kiro-cli 2\.2[4-6]\.\d+$/.test(version)) {
		throw new Error(
			`The native Kiro harness requires kiro-cli 2.24-2.26 (V2); found ${version || "an unknown version"}.`,
		);
	}
}

export function validateKiroProfile(
	run: KiroRun,
	exec: ExecFile = defaultExecFile,
): void {
	exec("kiro-cli", ["agent", "validate", "--path", run.profilePath], {
		timeout: 5000,
	});
}

export interface KiroState {
	version: 1;
	run_id: string;
	session_id: string;
	phase: "ready" | "active" | "stopped" | "untracked";
	token: string | null;
	summary?: string | null;
	untracked_summary?: string | null;
	untracked_turns?: number;
}

export interface KiroRun {
	harness: "kiro";
	id: string;
	cwd: string;
	profileName: string;
	profilePath: string;
	profileHash: string;
	createdDirs: string[];
	stateFile: string;
	configFile: string;
	/** Published by the owned hook, or the saved identity when resuming. */
	nativeSessionId?: string;
	/** Reopen this native session with --resume-id. */
	resumeSessionId?: string;
	cleanedUp?: boolean;
}

export function readKiroState(run: KiroRun): KiroState | null {
	try {
		const data = JSON.parse(readFileSync(run.stateFile, "utf8"));
		if (
			data.version !== 1 ||
			data.run_id !== run.id ||
			!isNativeUuid(data.session_id) ||
			(run.nativeSessionId && data.session_id !== run.nativeSessionId) ||
			!["ready", "active", "stopped", "untracked"].includes(data.phase) ||
			(data.token !== null && !isNativeUuid(data.token))
		)
			return null;
		if (
			data.phase === "stopped" &&
			(!isNonEmptyString(data.summary?.trim()) || !data.token)
		)
			return null;
		return data;
	} catch {
		return null;
	}
}

/**
 * Project instruction files Pi and Claude Code read from the working
 * directory. Only regular files directly in cwd are listed: no globs, `~`,
 * absolute paths, symlinks, steering, skills, or knowledge bases.
 */
export const kiroProjectInstructionFiles = ["AGENTS.md", "CLAUDE.md"] as const;
export function kiroProjectResources(cwd: string): string[] {
	return kiroProjectInstructionFiles
		.filter((file) => {
			try {
				return lstatSync(join(cwd, file)).isFile();
			} catch {
				return false;
			}
		})
		.map((file) => `file://${file}`);
}

/**
 * Owned transient workspace profile. Exclusive creation refuses collisions;
 * no existing, global, or user-owned configuration is edited. Resume must
 * recreate the saved native agent name, not only pass a new --agent.
 */
export function prepareKiroRun(options: {
	runDir: string;
	processRun: ProcessRun;
	cwd: string;
	markerFile: string;
	tools: string[];
	identity?: string | null;
	/** Saved profile name and session identity for native resume. */
	resume?: { agentName: string; sessionId: string };
	mcpServer?: { name: string; command: string; args: string[] };
}): KiroRun {
	mkdirSync(options.runDir, { recursive: true, mode: 0o700 });
	const cwd = resolve(options.cwd);
	const profileName =
		options.resume?.agentName ?? `pi-subagent-${randomUUID()}`;
	if (!KIRO_AGENT_NAME.test(profileName))
		throw new Error("Invalid saved native Kiro agent name.");
	if (options.resume && !isNativeUuid(options.resume.sessionId))
		throw new Error("Invalid saved native Kiro session ID.");
	const run: KiroRun = {
		harness: "kiro",
		id: options.processRun.id,
		cwd,
		profileName,
		profilePath: join(cwd, ".kiro", "agents", `${profileName}.json`),
		profileHash: "",
		createdDirs: [],
		stateFile: join(options.runDir, "state.json"),
		configFile: join(options.runDir, "hook-config.json"),
	};
	if (options.resume) {
		run.nativeSessionId = options.resume.sessionId;
		run.resumeSessionId = options.resume.sessionId;
	}
	try {
		for (const dir of [join(cwd, ".kiro"), join(cwd, ".kiro", "agents")]) {
			if (existsSync(dir)) {
				const stat = lstatSync(dir);
				if (stat.isSymbolicLink() || !stat.isDirectory())
					throw new Error(
						`Kiro profile directory must be a real local directory: ${dir}`,
					);
			} else {
				mkdirSync(dir);
				run.createdDirs.push(dir);
			}
		}
		writeFileSync(
			run.configFile,
			JSON.stringify({
				version: 1,
				run_id: run.id,
				cwd,
				expected_session_id: options.resume?.sessionId ?? null,
				session_file: options.markerFile,
				state_file: run.stateFile,
				error_file: errorReceiptFile(options.processRun),
			}),
			{ flag: "wx", mode: 0o600 },
		);
		const command = `python3 ${shellQuote(kiroHookPath)} ${shellQuote(run.configFile)}`;
		const mcpServers = options.mcpServer
			? {
					[options.mcpServer.name]: {
						command: options.mcpServer.command,
						args: options.mcpServer.args,
					},
				}
			: {};
		const tools = options.mcpServer
			? [...options.tools, `@${options.mcpServer.name}`]
			: options.tools;
		const profile = `${JSON.stringify(
			{
				name: profileName,
				description: "Owned pi-herdr-agents native subagent profile",
				prompt: options.identity ?? undefined,
				tools,
				allowedTools: [],
				resources: kiroProjectResources(cwd),
				mcpServers,
				includeMcpJson: false,
				hooks: {
					agentSpawn: [{ command }],
					userPromptSubmit: [{ command }],
					stop: [{ command }],
				},
			},
			null,
			2,
		)}\n`;
		writeFileSync(run.profilePath, profile, { flag: "wx", mode: 0o600 });
		run.profileHash = hash(profile);
		return run;
	} catch (error) {
		cleanupKiroRun(run);
		throw error;
	}
}

/**
 * Remove only the transient profile this run created, and only while its
 * content is unchanged. Directories are removed only when this run created
 * them and they are empty; user-owned or modified files are always retained.
 */
export function cleanupKiroRun(run: KiroRun): void {
	if (run.cleanedUp) return;
	run.cleanedUp = true;
	try {
		if (
			run.profileHash &&
			!lstatSync(run.profilePath).isSymbolicLink() &&
			hash(readFileSync(run.profilePath, "utf8")) === run.profileHash
		)
			unlinkSync(run.profilePath);
	} catch {
		// Missing or unreadable profiles are left for manual inspection.
	}
	for (const dir of [...run.createdDirs].reverse()) {
		try {
			rmdirSync(dir);
		} catch {
			// Non-empty or already removed directories are retained.
		}
	}
}

export function kiroCommand(
	run: KiroRun,
	taggedPrompt: string,
	options?: { model?: string | null; thinking?: string | null },
): string {
	// Autonomous children cannot answer approval prompts. The generated profile
	// still limits which tools exist; this only trusts that explicit set.
	const args = [
		"kiro-cli",
		"chat",
		"--v2",
		"--agent",
		shellQuote(run.profileName),
		"--trust-all-tools",
	];
	if (run.resumeSessionId)
		args.push("--resume-id", shellQuote(run.resumeSessionId));
	if (options?.model) args.push("--model", shellQuote(options.model));
	if (options?.thinking) args.push("--effort", shellQuote(options.thinking));
	args.push(shellQuote(taggedPrompt));
	return `cd ${shellQuote(run.cwd)} && ${args.join(" ")}`;
}

export function kiroAdapter(run: KiroRun): NativeTurnAdapter {
	return {
		harness: "kiro",
		label: "Kiro",
		exitCommand: "/quit",
		exitTimeoutMs: KIRO_EXIT_MS,
		followUpAckTimeoutMs: KIRO_ACK_MS,
		readState(): NativeHookState | null {
			const state = readKiroState(run);
			if (!state) return null;
			run.nativeSessionId ??= state.session_id;
			return {
				sessionId: state.session_id,
				phase: state.phase,
				token: state.token,
				summary: state.summary ?? null,
				error: null,
				untrackedSummary: state.untracked_summary ?? null,
				untrackedTurns: state.untracked_turns ?? 0,
			};
		},
	};
}
