// This content is generated by AI (Kiro)
/**
 * Native interactive Kiro CLI 2.24 V2 harness (fresh autonomous runs only).
 * No ACP/headless/screen-extraction fallback: completion requires a
 * correlated stop hook receipt for the owned profile plus process exit.
 *
 * Ported from zhengfran/pi-interactive-subagents (MIT, Copyright (c) 2026
 * HazAT and contributors), `pi-extension/subagents/kiro.ts`. Follow-up
 * queues and native resume were removed for this first stage.
 */
import { execFileSync } from "node:child_process";
import { createHash, randomUUID } from "node:crypto";
import {
	existsSync,
	lstatSync,
	mkdirSync,
	readFileSync,
	rmdirSync,
	unlinkSync,
	writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
	isNativeUuid,
	nativePrompt,
	type NativeTurnOutcome,
} from "./claude.ts";
import { isNonEmptyString } from "./type-guards.ts";
import { errorReceiptFile, type ProcessRun } from "./process-run.ts";
import { shellQuote } from "./terminal.ts";

export const kiroHookPath = join(
	dirname(fileURLToPath(import.meta.url)),
	"plugin/hooks/kiro-lifecycle.py",
);
const hash = (text: string) => createHash("sha256").update(text).digest("hex");
export const KIRO_ACK_MS = 30_000;
export const KIRO_EXIT_MS = 15_000;

const KIRO_TOOL_MAP = new Map([
	["read", "fs_read"],
	["ls", "fs_read"],
	["write", "fs_write"],
	["edit", "fs_write"],
	["bash", "execute_bash"],
	["grep", "grep"],
	["find", "glob"],
]);

/** Fail closed when a Pi tool allowlist cannot be represented natively. */
export function kiroTools(tools: string | undefined): string[] {
	if (!tools?.trim())
		throw new Error(
			"Kiro roles require an explicit tools allowlist (read, write, edit, bash, grep, find, ls).",
		);
	const parsed = tools
		.split(",")
		.map((tool) => tool.trim())
		.filter(Boolean);
	const unknown = parsed.filter((tool) => !KIRO_TOOL_MAP.has(tool));
	if (!parsed.length || unknown.length)
		throw new Error(
			`Kiro cannot safely map Pi tools: ${unknown.join(", ")}. Supported: ${[...KIRO_TOOL_MAP.keys()].join(", ")}.`,
		);
	// Kiro's fs_write exposes both file creation and editing. Do not silently
	// grant a write-only or edit-only role the other capability.
	if (parsed.includes("write") !== parsed.includes("edit"))
		throw new Error(
			"Kiro requires write and edit together (one native fs_write tool).",
		);
	if (parsed.includes("ls") && !parsed.includes("read"))
		throw new Error("Kiro requires read with ls (one native fs_read tool).");
	return [...new Set(parsed.flatMap((tool) => KIRO_TOOL_MAP.get(tool) ?? []))];
}

export type ExecFile = (
	file: string,
	args: readonly string[],
	options: { timeout: number },
) => string;

const defaultExecFile: ExecFile = (file, args, options) =>
	execFileSync(file, args, {
		encoding: "utf8",
		timeout: options.timeout,
		stdio: "pipe",
	});

export function assertKiroAvailable(exec: ExecFile = defaultExecFile): void {
	let version: string;
	try {
		version = exec("kiro-cli", ["--version"], { timeout: 5000 }).trim();
	} catch (error) {
		throw new Error(
			`Kiro CLI is unavailable: ${error instanceof Error ? error.message : String(error)}. Install kiro-cli 2.24.x and ensure it is on PATH.`,
		);
	}
	if (!/^kiro-cli 2\.24\.\d+$/.test(version)) {
		throw new Error(
			`The native Kiro harness requires kiro-cli 2.24.x (V2); found ${version || "an unknown version"}.`,
		);
	}
}

export function validateKiroProfile(
	run: KiroRun,
	exec: ExecFile = defaultExecFile,
): void {
	exec("kiro-cli", ["agent", "validate", "--path", run.profilePath], {
		timeout: 5000,
	});
}

export interface KiroState {
	version: 1;
	run_id: string;
	session_id: string;
	phase: "ready" | "active" | "stopped" | "untracked";
	token: string | null;
	summary?: string | null;
}

export interface KiroRun {
	harness: "kiro";
	id: string;
	cwd: string;
	profileName: string;
	profilePath: string;
	profileHash: string;
	createdDirs: string[];
	stateFile: string;
	configFile: string;
	expectedToken: string;
	nativeSessionId?: string;
	submittedAt: number;
	acknowledged: boolean;
	quittingAt?: number;
	cleanedUp?: boolean;
}

export function readKiroState(run: KiroRun): KiroState | null {
	try {
		const data = JSON.parse(readFileSync(run.stateFile, "utf8"));
		if (
			data.version !== 1 ||
			data.run_id !== run.id ||
			!isNativeUuid(data.session_id) ||
			(run.nativeSessionId && data.session_id !== run.nativeSessionId) ||
			!["ready", "active", "stopped", "untracked"].includes(data.phase) ||
			(data.token !== null && !isNativeUuid(data.token))
		)
			return null;
		if (
			data.phase === "stopped" &&
			(!isNonEmptyString(data.summary?.trim()) || !data.token)
		)
			return null;
		return data;
	} catch {
		return null;
	}
}

/**
 * Project instruction files Pi and Claude Code read from the working
 * directory. Only regular files directly in cwd are listed: no globs, `~`,
 * absolute paths, symlinks, steering, skills, or knowledge bases.
 */
export const kiroProjectInstructionFiles = ["AGENTS.md", "CLAUDE.md"] as const;
export function kiroProjectResources(cwd: string): string[] {
	return kiroProjectInstructionFiles
		.filter((file) => {
			try {
				return lstatSync(join(cwd, file)).isFile();
			} catch {
				return false;
			}
		})
		.map((file) => `file://${file}`);
}

/**
 * Owned transient workspace profile. Exclusive creation refuses collisions;
 * no existing, global, or user-owned configuration is edited.
 */
export function prepareKiroRun(options: {
	runDir: string;
	processRun: ProcessRun;
	cwd: string;
	markerFile: string;
	tools: string[];
	identity?: string | null;
	now?: number;
}): KiroRun {
	mkdirSync(options.runDir, { recursive: true, mode: 0o700 });
	const cwd = resolve(options.cwd);
	const profileName = `pi-subagent-${randomUUID()}`;
	const run: KiroRun = {
		harness: "kiro",
		id: options.processRun.id,
		cwd,
		profileName,
		profilePath: join(cwd, ".kiro", "agents", `${profileName}.json`),
		profileHash: "",
		createdDirs: [],
		stateFile: join(options.runDir, "state.json"),
		configFile: join(options.runDir, "hook-config.json"),
		expectedToken: randomUUID(),
		submittedAt: options.now ?? Date.now(),
		acknowledged: false,
	};
	try {
		for (const dir of [join(cwd, ".kiro"), join(cwd, ".kiro", "agents")]) {
			if (existsSync(dir)) {
				const stat = lstatSync(dir);
				if (stat.isSymbolicLink() || !stat.isDirectory())
					throw new Error(
						`Kiro profile directory must be a real local directory: ${dir}`,
					);
			} else {
				mkdirSync(dir);
				run.createdDirs.push(dir);
			}
		}
		writeFileSync(
			run.configFile,
			JSON.stringify({
				version: 1,
				run_id: run.id,
				cwd,
				expected_session_id: null,
				session_file: options.markerFile,
				state_file: run.stateFile,
				error_file: errorReceiptFile(options.processRun),
			}),
			{ flag: "wx", mode: 0o600 },
		);
		const command = `python3 ${shellQuote(kiroHookPath)} ${shellQuote(run.configFile)}`;
		const profile = `${JSON.stringify(
			{
				name: profileName,
				description: "Owned pi-herdr-agents native subagent profile",
				prompt: options.identity ?? undefined,
				tools: options.tools,
				allowedTools: [],
				resources: kiroProjectResources(cwd),
				mcpServers: {},
				includeMcpJson: false,
				hooks: {
					agentSpawn: [{ command }],
					userPromptSubmit: [{ command }],
					stop: [{ command }],
				},
			},
			null,
			2,
		)}\n`;
		writeFileSync(run.profilePath, profile, { flag: "wx", mode: 0o600 });
		run.profileHash = hash(profile);
		return run;
	} catch (error) {
		cleanupKiroRun(run);
		throw error;
	}
}

/**
 * Remove only the transient profile this run created, and only while its
 * content is unchanged. Directories are removed only when this run created
 * them and they are empty; user-owned or modified files are always retained.
 */
export function cleanupKiroRun(run: KiroRun): void {
	if (run.cleanedUp) return;
	run.cleanedUp = true;
	try {
		if (
			run.profileHash &&
			!lstatSync(run.profilePath).isSymbolicLink() &&
			hash(readFileSync(run.profilePath, "utf8")) === run.profileHash
		)
			unlinkSync(run.profilePath);
	} catch {
		// Missing or unreadable profiles are left for manual inspection.
	}
	for (const dir of [...run.createdDirs].reverse()) {
		try {
			rmdirSync(dir);
		} catch {
			// Non-empty or already removed directories are retained.
		}
	}
}

export function kiroCommand(
	run: KiroRun,
	task: string,
	options?: { model?: string | null; thinking?: string | null },
): string {
	// Autonomous children cannot answer approval prompts. The generated profile
	// still limits which tools exist; this only trusts that explicit set.
	const args = [
		"kiro-cli",
		"chat",
		"--v2",
		"--agent",
		shellQuote(run.profileName),
		"--trust-all-tools",
	];
	if (options?.model) args.push("--model", shellQuote(options.model));
	if (options?.thinking) args.push("--effort", shellQuote(options.thinking));
	args.push(shellQuote(nativePrompt(task, run.expectedToken)));
	return `cd ${shellQuote(run.cwd)} && ${args.join(" ")}`;
}

/** Quit gracefully after the correlated turn stops so native history flushes. */
export function tickKiroRun(
	run: KiroRun,
	send: (text: string) => void,
	now = Date.now(),
): void {
	if (run.quittingAt !== undefined) {
		if (now - run.quittingAt > KIRO_EXIT_MS)
			throw new Error(
				"Kiro did not exit after /quit; native session persistence is unconfirmed.",
			);
		return;
	}
	const state = readKiroState(run);
	if (!state) {
		if (now - run.submittedAt > KIRO_ACK_MS)
			throw new Error(
				`Kiro did not publish a valid native hook receipt within ${KIRO_ACK_MS / 1000} seconds.`,
			);
		return;
	}
	run.nativeSessionId ??= state.session_id;
	if (
		state.token === run.expectedToken &&
		(state.phase === "active" || state.phase === "stopped")
	)
		run.acknowledged = true;
	if (!run.acknowledged && now - run.submittedAt > KIRO_ACK_MS)
		throw new Error(
			`Kiro did not acknowledge the submitted turn within ${KIRO_ACK_MS / 1000} seconds.`,
		);
	if (
		state.phase !== "ready" &&
		(!state.token || (run.acknowledged && state.token !== run.expectedToken))
	) {
		throw new Error(
			"Unexpected human input superseded the autonomous Kiro turn; refusing ambiguous completion.",
		);
	}
	if (state.phase === "stopped" && state.token === run.expectedToken) {
		run.quittingAt = now;
		send("/quit");
	}
}

/** Only the current run's correlated final stop plus a clean exit succeeds. */
export function kiroOutcome(
	run: KiroRun,
	exit: { reason: string; exitCode: number; errorMessage?: string },
): NativeTurnOutcome {
	const state = readKiroState(run);
	if (
		exit.reason !== "error" &&
		exit.exitCode === 0 &&
		state?.phase === "stopped" &&
		state.token === run.expectedToken &&
		state.summary
	) {
		return { completed: true, summary: state.summary.trim() };
	}
	return {
		completed: false,
		summary: `Kiro exited without completing the correlated turn (${exit.errorMessage ?? `shell exit ${exit.exitCode}`}).`,
	};
}
