// This content is generated by AI (Kiro)
/**
 * Harness-neutral native turn driver shared by the Claude Code and Kiro
 * adapters. It owns correlated tagged turns, the follow-up queue, verified
 * idle points, interrupts, and the graceful-exit policy for autonomous,
 * interactive, and persistent native runs.
 *
 * Input is typed into a native TUI only at a verified idle point: the latest
 * tagged turn's correlated Stop/StopFailure receipt, or (interactive runs
 * only) a completed human-driven turn. Busy TUIs, startup dialogs, and
 * interrupted turns without a receipt never receive parent input.
 *
 * The queued follow-up approach is ported from zhengfran/pi-interactive-subagents
 * (MIT, Copyright (c) 2026 HazAT and contributors), `claude.ts` and `kiro.ts`.
 */
import { randomUUID } from "node:crypto";
import { sanitizeTypedText } from "./native-context.ts";
import type { NativeHarnessName, NativeRunMode } from "./native-session.ts";

export interface NativeHookState {
	sessionId: string;
	phase: "ready" | "active" | "stopped" | "failed" | "untracked";
	token: string | null;
	summary: string | null;
	error: string | null;
	/** Final text of the latest human-driven (untagged) turn, if recorded. */
	untrackedSummary: string | null;
	untrackedTurns: number;
}

/** What varies between native CLIs for turn driving. */
export interface NativeTurnAdapter {
	harness: NativeHarnessName;
	label: string;
	exitCommand: string;
	exitTimeoutMs: number;
	followUpAckTimeoutMs: number;
	/** Correlated, validated hook state for this run, or null. */
	readState(): NativeHookState | null;
}

export type NativeTurnKind =
	| "initial"
	| "resume"
	| "follow-up"
	| "task"
	| "nested-result";

export type NativeTurnOutcomeKind =
	| "completed"
	| "failed"
	| "interrupted"
	| "superseded"
	| "unacknowledged"
	| "not-delivered";

export interface NativeTurn {
	/** Follow-up, task, or nested-request ID; the run ID for the first turn. */
	id: string;
	kind: NativeTurnKind;
	/** Per-turn correlation token carried in the typed prompt tag. */
	token: string;
	/** Exact single-line text typed after the tag (follow-up turns only). */
	typed?: string;
	submittedAt?: number;
	ackTimeoutMs: number;
	acknowledged: boolean;
	outcome?: NativeTurnOutcomeKind;
	summary?: string;
	error?: string;
}

export interface NativeDriver {
	version: 1;
	mode: NativeRunMode;
	/** Submitted turns in order; the last one is current. */
	turns: NativeTurn[];
	/** Accepted turns not yet typed, delivered one per verified idle point. */
	queue: NativeTurn[];
	/** Accepted turns that were never typed, kept as evidence. */
	undelivered: NativeTurn[];
	maxQueue: number;
	quittingAt?: number;
	/** Parent requested a graceful end (persistent stop). */
	stopRequested?: boolean;
	/** Interactive only: no further parent input is typed. */
	inputSuspended?: string;
	interrupt?: { token: string; requestedAt: number; graceMs: number };
	/** Nested children whose results are still owed to this run. */
	outstandingNested: number;
	lastState?: NativeHookState | null;
}

export type NativeFailureKind =
	| "superseded"
	| "not-acknowledged"
	| "interrupted"
	| "exit-timeout";

export class NativeTurnFailure extends Error {
	readonly kind: NativeFailureKind;
	constructor(message: string, kind: NativeFailureKind) {
		super(message);
		this.name = "NativeTurnFailure";
		this.kind = kind;
	}
}

export const NATIVE_MAX_QUEUED_TURNS = 4;
export const NATIVE_INTERRUPT_GRACE_MS = 10_000;

export function nativePrompt(text: string, token: string): string {
	return `[pi-subagent-turn:${token}] ${text}`;
}

export function createNativeDriver(options: {
	mode: NativeRunMode;
	firstTurn: { id: string; kind: "initial" | "resume"; ackTimeoutMs: number };
	maxQueue?: number;
}): NativeDriver {
	return {
		version: 1,
		mode: options.mode,
		turns: [
			{
				id: options.firstTurn.id,
				kind: options.firstTurn.kind,
				token: randomUUID(),
				ackTimeoutMs: options.firstTurn.ackTimeoutMs,
				acknowledged: false,
			},
		],
		queue: [],
		undelivered: [],
		maxQueue: options.maxQueue ?? NATIVE_MAX_QUEUED_TURNS,
		outstandingNested: 0,
	};
}

export function currentNativeTurn(driver: NativeDriver): NativeTurn {
	// SAFETY: createNativeDriver always seeds the first turn and turns only grow.
	return driver.turns[driver.turns.length - 1]!;
}

function settle(
	turn: NativeTurn,
	outcome: NativeTurnOutcomeKind,
	detail: { summary?: string | null; error?: string | null } = {},
	onSettled?: (turn: NativeTurn) => void,
): void {
	if (turn.outcome) return;
	turn.outcome = outcome;
	if (detail.summary) turn.summary = detail.summary.trim();
	if (detail.error) turn.error = detail.error;
	onSettled?.(turn);
}

export type EnqueueResult =
	| { ok: true; turn: NativeTurn; position: number; truncated: boolean }
	| { ok: false; error: string };

/** Accept one follow-up turn for delivery at the next verified idle point. */
export function enqueueNativeTurn(
	driver: NativeDriver,
	request: { id: string; kind: NativeTurnKind; text: string },
	adapter: Pick<NativeTurnAdapter, "followUpAckTimeoutMs" | "label">,
): EnqueueResult {
	if (driver.quittingAt !== undefined || driver.stopRequested)
		return { ok: false, error: "the native session is ending" };
	if (driver.inputSuspended)
		return {
			ok: false,
			error: `parent input is suspended (${driver.inputSuspended})`,
		};
	if (driver.queue.length >= driver.maxQueue)
		return {
			ok: false,
			error: `${driver.queue.length} follow-up(s) are already queued (limit ${driver.maxQueue})`,
		};
	const typed = sanitizeTypedText(request.text);
	if (!typed.text) return { ok: false, error: "the message is empty" };
	const turn: NativeTurn = {
		id: request.id,
		kind: request.kind,
		token: randomUUID(),
		typed: typed.text,
		ackTimeoutMs: adapter.followUpAckTimeoutMs,
		acknowledged: false,
	};
	driver.queue.push(turn);
	return {
		ok: true,
		turn,
		position: driver.queue.length,
		truncated: typed.truncated,
	};
}

export type InterruptRequest =
	| { ok: true; turn: NativeTurn }
	| { ok: false; error: string };

/**
 * Record an interrupt for the active tagged turn before any key is sent, so a
 * racing Stop receipt can never turn it into a success. Requires a correlated
 * receipt showing that exact turn in progress. The next tick settles the turn
 * as interrupted; clear `driver.interrupt` if the key could not be sent.
 */
export function requestNativeInterrupt(
	driver: NativeDriver,
	state: NativeHookState | null,
	now = Date.now(),
	graceMs = NATIVE_INTERRUPT_GRACE_MS,
): InterruptRequest {
	const turn = currentNativeTurn(driver);
	if (driver.quittingAt !== undefined || driver.stopRequested)
		return { ok: false, error: "the native session is already ending" };
	if (driver.interrupt)
		return { ok: false, error: "an interrupt is already pending" };
	if (
		turn.outcome ||
		!turn.acknowledged ||
		state?.phase !== "active" ||
		state.token !== turn.token
	)
		return {
			ok: false,
			error:
				"no tagged turn is verifiably in progress (it is not yet acknowledged by a native hook receipt, already stopped, or superseded)",
		};
	driver.interrupt = { token: turn.token, requestedAt: now, graceMs };
	return { ok: true, turn };
}

function acknowledgementError(
	adapter: NativeTurnAdapter,
	turn: NativeTurn,
): string {
	const seconds = Math.round(turn.ackTimeoutMs / 1000);
	return turn.kind === "initial" || turn.kind === "resume"
		? `${adapter.label} did not acknowledge the tagged prompt within ${seconds} seconds (hooks disabled, the native session could not be opened, or a startup dialog such as workspace trust is waiting for a human). No dialog was answered.`
		: `${adapter.label} did not acknowledge the tagged follow-up within ${seconds} seconds; it was typed at a verified idle point, so the native input was lost or merged. No retry was typed.`;
}

/**
 * Advance the driver from correlated hook evidence. Throws NativeTurnFailure
 * when completion would be ambiguous; the caller then terminates only
 * verified owned processes.
 */
export function tickNativeDriver(
	driver: NativeDriver,
	adapter: NativeTurnAdapter,
	send: (text: string) => void,
	now = Date.now(),
	onSettled?: (turn: NativeTurn) => void,
): void {
	if (driver.quittingAt !== undefined) {
		if (now - driver.quittingAt > adapter.exitTimeoutMs)
			throw new NativeTurnFailure(
				`${adapter.label} did not exit after ${adapter.exitCommand}; native session persistence is unconfirmed.`,
				"exit-timeout",
			);
		return;
	}
	const current = currentNativeTurn(driver);
	const state = adapter.readState();
	driver.lastState = state;
	if (
		!current.acknowledged &&
		state?.token === current.token &&
		state.phase !== "ready"
	)
		current.acknowledged = true;
	if (
		!current.acknowledged &&
		!current.outcome &&
		current.submittedAt !== undefined &&
		now - current.submittedAt > current.ackTimeoutMs
	) {
		if (driver.mode === "interactive" && current.kind !== "initial") {
			settle(
				current,
				"unacknowledged",
				{ error: acknowledgementError(adapter, current) },
				onSettled,
			);
			driver.inputSuspended =
				"a typed follow-up was not acknowledged; the human may have partially typed input";
		} else
			throw new NativeTurnFailure(
				acknowledgementError(adapter, current),
				"not-acknowledged",
			);
	}
	// A recorded interrupt settles its turn before any receipt is read, so a
	// Stop racing the interrupt key can never be counted as a success.
	if (driver.interrupt?.token === current.token)
		settle(
			current,
			"interrupted",
			{ error: "interrupted by the parent before its correlated Stop" },
			onSettled,
		);
	if (!state) return;

	const untagged =
		state.phase !== "ready" &&
		(!state.token || (current.acknowledged && state.token !== current.token));
	if (untagged) {
		if (driver.mode !== "interactive")
			throw new NativeTurnFailure(
				`Unexpected human input superseded the ${driver.mode} ${adapter.label} turn; refusing ambiguous completion.`,
				"superseded",
			);
		if (current.acknowledged)
			settle(
				current,
				"superseded",
				{
					error:
						"human input superseded the tagged turn before its correlated Stop",
				},
				onSettled,
			);
	}

	const correlatedStop =
		state.token === current.token &&
		(state.phase === "stopped" || state.phase === "failed");
	if (correlatedStop) {
		if (state.phase === "stopped")
			settle(current, "completed", { summary: state.summary }, onSettled);
		else {
			settle(
				current,
				"failed",
				{ error: state.error ?? "native turn failed" },
				onSettled,
			);
		}
	}

	// A typed turn awaiting its acknowledgement is never idle: typing again
	// before the receipt would stack prompts in the native input.
	const awaitingAck = !current.acknowledged && !current.outcome;
	const idle =
		!awaitingAck &&
		(correlatedStop ||
			(driver.mode === "interactive" && state.phase === "untracked"));
	if (!idle) {
		if (
			driver.interrupt &&
			driver.mode !== "interactive" &&
			now - driver.interrupt.requestedAt > driver.interrupt.graceMs
		)
			throw new NativeTurnFailure(
				`The ${adapter.label} turn was interrupted, and no native hook receipt proved the turn ended within ${Math.round(driver.interrupt.graceMs / 1000)} seconds. The owned native process is terminated; the native session remains available to subagent_resume if the CLI persisted it.`,
				"interrupted",
			);
		return;
	}
	driver.interrupt = undefined;
	if (driver.inputSuspended) return;

	const blocked =
		driver.mode === "autonomous" && current.outcome !== "completed";
	if (driver.queue.length > 0 && !blocked) {
		// SAFETY: the queue was checked non-empty above.
		const next = driver.queue.shift()!;
		next.submittedAt = now;
		driver.turns.push(next);
		send(nativePrompt(next.typed ?? "", next.token));
		return;
	}
	if (blocked)
		for (const queued of driver.queue.splice(0)) {
			settle(
				queued,
				"not-delivered",
				{ error: "an earlier tagged turn did not complete" },
				onSettled,
			);
			driver.undelivered.push(queued);
		}
	if (
		driver.stopRequested ||
		(driver.mode === "autonomous" &&
			(driver.outstandingNested === 0 || blocked))
	) {
		driver.quittingAt = now;
		send(adapter.exitCommand);
	}
}

/** Whether a persistent run is at a verified idle point accepting a task. */
export function isNativeDriverIdle(driver: NativeDriver): boolean {
	const current = currentNativeTurn(driver);
	return (
		driver.quittingAt === undefined &&
		!driver.stopRequested &&
		!driver.interrupt &&
		driver.queue.length === 0 &&
		!!current.outcome &&
		current.outcome !== "unacknowledged"
	);
}

export interface NativeRunOutcome {
	completed: boolean;
	summary: string;
	interrupted: boolean;
	/** Every tagged turn in order, including undelivered follow-ups. */
	turns: NativeTurn[];
	humanTurns: number;
	lastHumanSummary: string | null;
	/**
	 * Positive evidence that the first tagged turn never started: this run's
	 * own correlated session receipt proves its hooks were active, yet no
	 * prompt-submit receipt, human turn, or later turn was ever recorded. A
	 * missing receipt alone is not evidence (hooks may not have run), and a
	 * failed turn (including a correlated StopFailure) may have done work.
	 * The caller must also require a confirmed exit and no hook error.
	 */
	neverStarted: boolean;
}

/** Final correlated outcome once the native process has exited. */
export function nativeDriverOutcome(
	driver: NativeDriver,
	adapter: NativeTurnAdapter,
	exit: { reason: string; exitCode: number; errorMessage?: string },
	/**
	 * Called for every turn this final outcome settles, exactly like ticks:
	 * a Stop written just before a fast exit must reach the same queue.
	 */
	onSettled?: (turn: NativeTurn) => void,
): NativeRunOutcome {
	const state = adapter.readState();
	const current = currentNativeTurn(driver);
	// The process can exit between ticks: the final receipt still proves the
	// turn started, which forbids treating it as never acknowledged.
	if (
		!current.acknowledged &&
		state?.token === current.token &&
		state.phase !== "ready"
	)
		current.acknowledged = true;
	if (driver.interrupt?.token === current.token)
		settle(
			current,
			"interrupted",
			{
				error: "interrupted by the parent before its correlated Stop",
			},
			onSettled,
		);
	if (
		!current.outcome &&
		state?.token === current.token &&
		(state.phase === "stopped" || state.phase === "failed")
	) {
		settle(
			current,
			state.phase === "stopped" ? "completed" : "failed",
			state.phase === "stopped"
				? { summary: state.summary }
				: { error: state.error },
			onSettled,
		);
	}
	for (const turn of driver.turns)
		if (!turn.outcome)
			settle(
				turn,
				turn.acknowledged ? "failed" : "unacknowledged",
				{
					error: turn.acknowledged
						? "the process exited before this turn's correlated Stop"
						: "no correlated native hook receipt acknowledged this turn",
				},
				onSettled,
			);
	for (const queued of driver.queue.splice(0)) {
		settle(
			queued,
			"not-delivered",
			{
				error: "the native session ended before this follow-up was typed",
			},
			onSettled,
		);
		driver.undelivered.push(queued);
	}
	const turns = [...driver.turns, ...driver.undelivered];
	const clean = exit.reason !== "error" && exit.exitCode === 0;
	const incomplete = turns.find((turn) => turn.outcome !== "completed");
	const completed = clean && !incomplete;
	const lastCompleted = [...turns]
		.reverse()
		.find((turn) => turn.outcome === "completed");
	const first = driver.turns[0];
	// A supervision failure (supersession, lost receipt, hook error) explains
	// the incomplete turn, so it leads; the turn detail follows.
	const turnDetail = incomplete
		? `${incomplete.kind} turn ${incomplete.outcome}${incomplete.error ? `: ${incomplete.error}` : ""}`
		: undefined;
	const reason =
		[exit.errorMessage, turnDetail].filter(Boolean).join("; ") ||
		`shell exit ${exit.exitCode}`;
	return {
		completed,
		summary: completed
			? (lastCompleted?.summary ?? "")
			: `${adapter.label} exited without completing every correlated turn (${reason}).`,
		interrupted: turns.some((turn) => turn.outcome === "interrupted"),
		turns,
		humanTurns: state?.untrackedTurns ?? 0,
		lastHumanSummary: state?.untrackedSummary ?? null,
		neverStarted:
			driver.turns.length === 1 &&
			!first.acknowledged &&
			first.outcome === "unacknowledged" &&
			state?.phase === "ready" &&
			state.token === null &&
			state.untrackedTurns === 0,
	};
}
