// This content is generated by AI (Kiro)
/**
 * Native harness seam for roles declaring `cli: claude` or `cli: kiro`.
 *
 * Only execution varies here: capability validation, pre-resource launch
 * planning (models, skills, inherited context), native command/hook
 * preparation, correlated turn evidence, process receipts, session leases,
 * and owned-file cleanup. Herdr pane/worktree provisioning and parent result
 * delivery stay in the common launch and watch paths.
 *
 * The receipt and correlation approach is ported from
 * zhengfran/pi-interactive-subagents (MIT, Copyright (c) 2026 HazAT and
 * contributors), `pi-extension/subagents/poll.ts`.
 */
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { randomUUID } from "node:crypto";
import {
	CLAUDE_START_ACK_MS,
	NATIVE_EFFORT_LEVELS,
	claudeAdapter,
	claudeCommand,
	claudeTools,
	isClaudeWorkspaceTrustPrompt,
	prepareClaudeRun,
	type ClaudeRun,
} from "./claude.ts";
import { isNonEmptyString } from "./type-guards.ts";
import {
	KIRO_ACK_MS,
	assertKiroAvailable,
	cleanupKiroRun,
	kiroAdapter,
	kiroCommand,
	kiroMcpServers,
	kiroMcpToolPatterns,
	kiroTools,
	prepareKiroRun,
	validateKiroProfile,
	type ExecFile,
	type KiroRun,
} from "./kiro.ts";
import {
	revalidateKiroMcpSelection,
	resolveKiroMcpSelection,
	type KiroMcpSelection,
} from "./kiro-mcp.ts";
import {
	confirmProcessExit,
	createProcessRun,
	defaultProcessInspector,
	errorReceiptFile,
	isProcessRunLive,
	readProcessRunState,
	writeCancelMarker,
	type ExitConfirmation,
	type ProcessInspector,
	type ProcessRun,
	type TerminationResult,
} from "./process-run.ts";
import type { PaneInspection } from "./lifecycle.ts";
import {
	MAX_INITIAL_PROMPT_BYTES,
	formatInheritedContextBlock,
	materializeSkills,
	parseSkillNames,
	readParentContextEntries,
	renderInheritedContext,
	sha256,
	writeSkillSnapshots,
	type InheritedContext,
	type InstalledSkill,
	type MaterializedSkill,
} from "./native-context.ts";
import {
	acquireNativeSessionLease,
	acquireRunLease,
	currentLeaseParent,
	handoffRunLease,
	nativeWorktreeLeaseFile,
	releaseRunLease,
	appendNativeRunRecord,
	inspectNativeSessionLease,
	loadoutSha256,
	readIdentityText,
	releaseNativeSessionLease,
	verifyNativeSessionMarker,
	writeNativeSessionMarker,
	type AnyNativeSessionMarker,
	type NativeLoadout,
	type NativeRunMode,
	type NativeSessionMarker,
	type NativeSessionMode,
	type NativeWorktreeBinding,
} from "./native-session.ts";
import {
	NativeTurnFailure,
	createNativeDriver,
	currentNativeTurn,
	nativeDriverOutcome,
	nativePrompt,
	tickNativeDriver,
	type NativeDriver,
	type NativeRunOutcome,
	type NativeTurn,
	type NativeTurnAdapter,
} from "./native-turns.ts";
import { prepareNativeBridge, type NativeBridge } from "./native-bridge.ts";
import {
	NATIVE_MODEL_ID,
	TASK_CATEGORIES,
	type NativeTaskPreferences,
	type TaskCategory,
} from "./model-config.ts";

export {
	readNativeSessionMarker,
	type AnyNativeSessionMarker,
	type NativeSessionMarker,
} from "./native-session.ts";

export const NATIVE_HARNESSES = ["claude", "kiro"] as const;
export type NativeHarnessName = (typeof NATIVE_HARNESSES)[number];

export function isNativeHarnessName(value: any): value is NativeHarnessName {
	return value === "claude" || value === "kiro";
}

export function nativeHarnessLabel(harness: NativeHarnessName): string {
	return harness === "claude" ? "Claude Code" : "Kiro";
}

/** Pi-only tools a native child can never receive. */
const PI_CHILD_TOOLS = new Set(["caller_ping", "subagent_done"]);
const PI_SPAWNING_TOOLS = new Set([
	"subagent",
	"subagent_interrupt",
	"subagents_list",
	"subagent_resume",
	"subagent_send",
	"subagent_stop",
	"subagents_write_task_models",
	"jev_router",
	"worktree_list",
	"worktree_remove",
]);
const ROLE_NAME = /^[A-Za-z0-9][A-Za-z0-9._-]{0,99}$/;

/** Role fields relevant to native harness capability validation. */
export interface NativeRoleDefinition {
	name: string;
	cli: NativeHarnessName;
	model?: string;
	tools?: string;
	skills?: string;
	thinking?: string;
	spawning?: boolean;
	/** Comma-separated roles this native child may delegate to. */
	spawnAgents?: string;
	/** Kiro only: exact personal MCP server names exposed through @server tools. */
	kiroMcpServers?: string;
	persistent?: boolean;
	autoExit?: boolean;
	interactive?: boolean;
	sessionMode?: string;
	systemPromptMode?: "append" | "replace";
	body?: string;
}

/** Per-call overrides that may conflict with native harness capabilities. */
export interface NativeLaunchOverrides {
	model?: string;
	thinking?: string;
	tools?: string;
	skills?: string;
	fork?: boolean;
	persistent?: boolean;
	interactive?: boolean;
}

export type NativeModelRequest =
	| { kind: "default" }
	| { kind: "exact"; model: string }
	| { kind: "list"; models: string[] }
	| { kind: "task"; category: TaskCategory };

export interface NativeLaunchSpec {
	harness: NativeHarnessName;
	role: string;
	/** Validated Pi-vocabulary allowlist that was mapped. */
	tools: string;
	/** Native tool names: Claude `--tools` entries or Kiro profile tools. */
	nativeTools: string[];
	/** Requested native model routing; resolved by planNativeLaunch. */
	modelRequest: NativeModelRequest;
	/** First native model candidate, never a Pi provider ref. */
	model: string | null;
	thinking: string | null;
	/** Identity passed through a native system-prompt channel, if any. */
	identity: string | null;
	/** The complete role body, recorded for exact resume. */
	identityText: string | null;
	promptMode: "append" | "replace" | null;
	/** Identity folded into the initial task when no prompt channel is used. */
	roleBlock: string;
	/** Session behavior: autonomous auto-exit, human-driven, or persistent. */
	mode: NativeRunMode;
	sessionMode: NativeSessionMode;
	skills: string[];
	/** Nested-spawn allowlist, or null when delegation is not granted. */
	spawnAgents: string[] | null;
	/** Exact personal Kiro MCP server names, or null on other harnesses. */
	kiroMcpServers: string[] | null;
}

export class NativeCapabilityError extends Error {
	readonly code = "native-harness-unsupported";
	constructor(role: string, harness: NativeHarnessName, reason: string) {
		super(
			`Role "${role}" uses the native ${nativeHarnessLabel(harness)} harness (cli: ${harness}), which ${reason}`,
		);
		this.name = "NativeCapabilityError";
	}
}

function parseModelRequest(
	model: string | null,
	fail: (reason: string) => never,
): NativeModelRequest {
	if (!model) return { kind: "default" };
	const task = model.match(/^task:(.*)$/i);
	if (task) {
		const category = task[1].trim().toLowerCase();
		// SAFETY: membership is checked against the fixed category set.
		if (!TASK_CATEGORIES.includes(category as TaskCategory))
			fail(
				`cannot use ${model}; supported task categories: ${TASK_CATEGORIES.join(", ")}.`,
			);
		// SAFETY: validated against TASK_CATEGORIES above.
		return { kind: "task", category: category as TaskCategory };
	}
	const candidates = model
		.split(",")
		.map((candidate) => candidate.trim())
		.filter(Boolean);
	if (candidates.length === 0) fail("has an empty model value.");
	for (const candidate of candidates)
		if (!NATIVE_MODEL_ID.test(candidate))
			fail(`cannot use model "${candidate}"; expected native CLI model IDs.`);
	if (new Set(candidates).size !== candidates.length)
		fail("has a duplicate native model candidate.");
	return candidates.length === 1
		? { kind: "exact", model: candidates[0] }
		: { kind: "list", models: candidates };
}

/**
 * Resolve and validate a native launch before any Herdr resource exists.
 * Without overrides this is also the discovery-time role validation.
 */
export function resolveNativeLaunchSpec(
	role: NativeRoleDefinition,
	overrides: NativeLaunchOverrides = {},
): NativeLaunchSpec {
	const fail = (reason: string): never => {
		throw new NativeCapabilityError(role.name, role.cli, reason);
	};
	const persistent = (overrides.persistent ?? role.persistent) === true;
	const requestedMode =
		overrides.fork === true
			? "fork"
			: overrides.fork === false
				? "standalone"
				: (role.sessionMode ?? "standalone");
	if (
		requestedMode !== "standalone" &&
		requestedMode !== "lineage-only" &&
		requestedMode !== "fork"
	)
		fail(`cannot use session-mode ${requestedMode}.`);
	// SAFETY: validated against the three session modes above.
	const sessionMode = requestedMode as NativeSessionMode;
	const mode: NativeRunMode = persistent
		? "persistent"
		: role.autoExit === true
			? "autonomous"
			: "interactive";

	const tools = (overrides.tools ?? role.tools)?.trim();
	const requested = (tools ?? "")
		.split(",")
		.map((tool) => tool.trim())
		.filter(Boolean);
	const piChildTools = requested.filter((tool) => PI_CHILD_TOOLS.has(tool));
	if (piChildTools.length)
		fail(
			`cannot provide Pi child tools (${piChildTools.join(", ")}); caller_ping and subagent_done are Pi-only. Remove them from tools.`,
		);
	const spawningTools = requested.filter((tool) => PI_SPAWNING_TOOLS.has(tool));
	if (spawningTools.length)
		fail(
			`cannot receive Pi orchestration tools (${spawningTools.join(", ")}). Remove them from tools; grant nested delegation with a spawn-agents allowlist instead.`,
		);
	if (role.cli === "claude" && role.kiroMcpServers?.trim())
		fail(
			"cannot use kiro-mcp-servers on Claude Code; it is a Kiro-only capability.",
		);
	let selectedKiroMcpServers: string[] = [];
	if (role.cli === "kiro")
		try {
			selectedKiroMcpServers = kiroMcpServers(role.kiroMcpServers);
		} catch (error) {
			fail(
				`has invalid kiro-mcp-servers: ${error instanceof Error ? error.message : String(error)}`,
			);
		}
	let nativeTools: string[] = [];
	try {
		nativeTools =
			role.cli === "claude"
				? claudeTools(tools).split(",")
				: [...kiroTools(tools), ...kiroMcpToolPatterns(selectedKiroMcpServers)];
	} catch (error) {
		fail(
			`requires a strictly mappable tools allowlist: ${error instanceof Error ? error.message : String(error)}`,
		);
	}

	const spawnAgents = (role.spawnAgents ?? "")
		.split(",")
		.map((agent) => agent.trim())
		.filter(Boolean);
	if (role.spawning === true && spawnAgents.length === 0)
		fail(
			"cannot spawn nested subagents without an explicit spawn-agents allowlist. Add spawn-agents: <role>[, <role>], or set spawning: false.",
		);
	if (role.spawning === false && spawnAgents.length > 0)
		fail("declares spawn-agents while spawning is false.");
	for (const agent of spawnAgents)
		if (!ROLE_NAME.test(agent))
			fail(`has an invalid spawn-agents role name "${agent}".`);
	if (spawnAgents.includes(role.name))
		fail("cannot list itself in spawn-agents.");
	if (spawnAgents.length && persistent)
		fail(
			"cannot delegate as a persistent specialist; the parent owns delegation for specialists. Remove spawn-agents or persistent.",
		);

	const model = (overrides.model ?? role.model)?.trim() || null;
	const modelRequest = parseModelRequest(model, fail);
	const thinking = (overrides.thinking ?? role.thinking)?.trim() || null;
	if (thinking && !NATIVE_EFFORT_LEVELS.some((level) => level === thinking))
		fail(
			`cannot represent thinking level ${thinking} (supported: ${NATIVE_EFFORT_LEVELS.join(", ")}; omit for the native default).`,
		);
	if (role.cli === "kiro" && role.systemPromptMode === "replace")
		fail(
			"cannot replace the native Kiro system prompt. Use system-prompt: append or omit it.",
		);

	const identity = role.body?.trim() || null;
	// Kiro always carries the role body in its owned profile prompt. Claude
	// follows Pi: an explicit system-prompt mode uses the native flag,
	// otherwise the body is part of the initial task wrapper.
	const identityChannel =
		role.cli === "kiro" ? identity : role.systemPromptMode ? identity : null;
	return {
		harness: role.cli,
		role: role.name,
		tools: requested.join(","),
		nativeTools,
		modelRequest,
		model:
			modelRequest.kind === "exact"
				? modelRequest.model
				: modelRequest.kind === "list"
					? modelRequest.models[0]
					: null,
		thinking,
		identity: identityChannel,
		identityText: identity,
		promptMode:
			role.cli === "kiro" ? "append" : (role.systemPromptMode ?? null),
		roleBlock: identity && !identityChannel ? identity : "",
		mode,
		sessionMode,
		skills: parseSkillNames(overrides.skills ?? role.skills),
		spawnAgents: spawnAgents.length ? spawnAgents : null,
		kiroMcpServers:
			role.cli === "kiro" && selectedKiroMcpServers.length
				? selectedKiroMcpServers
				: null,
	};
}

const MODE_HINTS = {
	autonomous:
		"Complete your task autonomously. When you are finished, simply stop — your session ends automatically.",
	interactive:
		"Complete your task. A human may interact with you in this session at any time and ends it when done.",
	persistent:
		"You are a persistent specialist. Complete this task, then stop; later tasks arrive as new messages in this same session.",
} satisfies Record<NativeRunMode, string>;
const SUMMARY_INSTRUCTION = {
	autonomous:
		"Your FINAL assistant message should summarize what you accomplished.",
	interactive:
		"Your FINAL assistant message for this task should summarize what you accomplished.",
	persistent:
		"Your FINAL assistant message for each task should summarize what you accomplished for that task.",
} satisfies Record<NativeRunMode, string>;

function delegationHint(agents: readonly string[]): string {
	return `You may delegate bounded, self-contained subtasks with the pi-subagents "subagent" tool (allowed agents: ${agents.join(", ")}). Nested subagents never receive more tools than you have and cannot delegate further. Their results arrive later as new messages beginning with "Nested subagent result"; after delegating, end your turn instead of polling.`;
}

/** Initial tagged turn text for a fresh native run. */
export function buildNativeTask(
	task: string,
	options: {
		roleBlock?: string;
		mode?: NativeRunMode;
		skills?: readonly MaterializedSkill[];
		inheritedContext?: string;
		spawnAgents?: readonly string[] | null;
	} = {},
): string {
	const mode = options.mode ?? "autonomous";
	return [
		options.roleBlock ?? "",
		...(options.skills ?? []).map((skill) => skill.block),
		MODE_HINTS[mode],
		options.spawnAgents?.length ? delegationHint(options.spawnAgents) : "",
		options.inheritedContext ?? "",
		task,
		SUMMARY_INSTRUCTION[mode],
	]
		.filter((part) => part.trim())
		.join("\n\n");
}

/** Everything resolved before any Herdr resource exists. */
export interface NativeLaunchPlan {
	spec: NativeLaunchSpec;
	/** Ordered native model candidates; `null` means the native default. */
	models: (string | null)[];
	skills: MaterializedSkill[];
	lineage?: {
		mode: "lineage-only" | "fork";
		parentSessionFile: string;
		context?: InheritedContext;
	};
	/** Selected personal Kiro MCP definitions, with no credential values. */
	kiroMcp?: KiroMcpSelection;
	/** Complete initial turn text, before the per-turn tag. */
	initialText: string;
}

export interface NativePlanContext {
	task: string;
	/** Absent when the parent has no persisted session (fork/lineage fail). */
	parentSessionFile?: string;
	installedSkills: () => InstalledSkill[];
	nativeTasks?: NativeTaskPreferences;
	/** True when a value names an authenticated Pi provider/model. */
	isPiModelRef?: (value: string) => boolean;
	inspector?: Pick<ProcessInspector, "procRoot">;
	/** Pre-rendered parent context entries (tests); defaults to the file. */
	parentEntries?: () => readonly any[];
	/** Test/config override; defaults to ~/.kiro/settings/mcp.json. */
	kiroMcpConfigFile?: string;
	/**
	 * Private directory for content-addressed skill snapshots. Without it,
	 * skills with supporting files are rejected.
	 */
	snapshotRoot?: string;
}

/**
 * Resolve models, skills, inherited context, and the bounded initial prompt.
 * Every rejection happens here, before any pane, workspace, or worktree.
 */
export function planNativeLaunch(
	spec: NativeLaunchSpec,
	context: NativePlanContext,
): NativeLaunchPlan {
	const fail = (reason: string): never => {
		throw new NativeCapabilityError(spec.role, spec.harness, reason);
	};
	let models: (string | null)[];
	switch (spec.modelRequest.kind) {
		case "default":
			models = [null];
			break;
		case "exact":
			models = [spec.modelRequest.model];
			break;
		case "list":
			models = [...spec.modelRequest.models];
			break;
		case "task": {
			const configured =
				context.nativeTasks?.[spec.harness]?.[spec.modelRequest.category];
			if (!configured?.length)
				fail(
					`has no native ${spec.harness} candidates for task:${spec.modelRequest.category}. Configure models.native.${spec.harness}.tasks.${spec.modelRequest.category} with native CLI model IDs; Pi models.tasks entries are Pi provider/model refs and never apply to native roles.`,
				);
			models = [...(configured ?? [])];
			break;
		}
	}
	for (const model of models)
		if (model && context.isPiModelRef?.(model))
			fail(
				`cannot use "${model}": it is a Pi provider/model reference. Native roles take native CLI model IDs.`,
			);
	// Persistent specialists never advance to another model after launch.
	if (spec.mode === "persistent") models = models.slice(0, 1);

	let kiroMcp: KiroMcpSelection | undefined;
	if (spec.kiroMcpServers?.length) {
		try {
			kiroMcp = resolveKiroMcpSelection(spec.kiroMcpServers, {
				sourceFile: context.kiroMcpConfigFile,
			});
		} catch (error) {
			fail(
				`cannot load its selected personal MCP servers: ${error instanceof Error ? error.message : String(error)}`,
			);
		}
	}

	if (
		spec.spawnAgents &&
		!(context.inspector ?? defaultProcessInspector).procRoot
	)
		fail(
			"cannot delegate here: nested requests must be bound to a verified owned process, which needs Linux /proc.",
		);

	let skills: MaterializedSkill[] = [];
	if (spec.skills.length) {
		try {
			skills = materializeSkills(
				spec.skills,
				context.installedSkills(),
				new Set(spec.tools.split(",").filter(Boolean)),
				context.snapshotRoot,
			);
		} catch (error) {
			fail(
				`cannot carry a requested Pi skill: ${error instanceof Error ? error.message : String(error)}`,
			);
		}
	}

	let lineage: NativeLaunchPlan["lineage"];
	let inheritedBlock = "";
	if (spec.sessionMode !== "standalone") {
		if (!context.parentSessionFile)
			fail(
				`cannot use ${spec.sessionMode} without a persisted parent session.`,
			);
		lineage = {
			mode: spec.sessionMode,
			// SAFETY: fail() above throws when the parent session is absent.
			parentSessionFile: context.parentSessionFile!,
		};
		if (spec.sessionMode === "fork") {
			let entries: readonly any[];
			try {
				entries =
					context.parentEntries?.() ??
					readParentContextEntries(lineage.parentSessionFile);
			} catch (error) {
				fail(
					`cannot fork: the parent session could not be read (${error instanceof Error ? error.message : String(error)}).`,
				);
			}
			// SAFETY: fail() above always throws when entries were not assigned.
			lineage.context = renderInheritedContext(entries!);
			inheritedBlock = formatInheritedContextBlock(lineage.context);
		}
	}

	const initialText = buildNativeTask(context.task, {
		roleBlock: spec.roleBlock,
		mode: spec.mode,
		skills,
		inheritedContext: inheritedBlock,
		spawnAgents: spec.spawnAgents,
	});
	const bytes = Buffer.byteLength(initialText, "utf8");
	if (bytes > MAX_INITIAL_PROMPT_BYTES)
		fail(
			`cannot deliver a ${bytes}-byte initial prompt; the native limit is ${MAX_INITIAL_PROMPT_BYTES} bytes including role, skills, and inherited context.`,
		);
	return { spec, models, skills, lineage, kiroMcp, initialText };
}

export interface NativeRun {
	version: 1;
	harness: NativeHarnessName;
	kind: "fresh" | "resume";
	processRun: ProcessRun;
	markerFile: string;
	runDir: string;
	sessionKey: string;
	/** Native model passed to this attempt (null: native default). */
	model: string | null;
	driver: NativeDriver;
	/** Durable worktree lease held for this run's lifetime, if bound. */
	worktreeLease?: string;
	/** Integrity hash of the loadout this run drives (policy hash). */
	loadoutSha256: string;
	claude?: ClaudeRun;
	kiro?: KiroRun;
	bridge?: NativeBridge;
}

export interface PreparedNativeRun {
	run: NativeRun;
	/** Native CLI command, to be wrapped by supervisedCommand. */
	command: string;
}

function writePrivate(path: string, content: string): void {
	mkdirSync(dirname(path), { recursive: true, mode: 0o700 });
	writeFileSync(path, content, { flag: "wx", mode: 0o600 });
}

export interface NativeResumeRequest {
	marker: NativeSessionMarker;
	markerFile: string;
	message: string;
	mode: "autonomous" | "interactive";
	/** Revalidated personal Kiro MCP definitions, with no credential values. */
	kiroMcp?: KiroMcpSelection;
}

/**
 * Create a fresh native session (plan) or reopen an existing one (resume).
 * Owned files are exclusively created; the session lease is acquired before
 * any process can start and released only after exit is confirmed.
 */
export function prepareNativeRun(options: {
	id: string;
	artifactDir: string;
	cwd: string;
	name: string;
	agent?: string;
	plan?: NativeLaunchPlan;
	/** Model candidate for this attempt; defaults to the plan's first. */
	model?: string | null;
	resume?: NativeResumeRequest;
	worktree?: NativeWorktreeBinding;
	/**
	 * Fallback attempt: take over the parent-reserved worktree lease from
	 * this run ID by atomic handoff instead of acquiring a new one.
	 */
	worktreeLeaseFrom?: string;
	inspector?: ProcessInspector;
	now?: number;
}): PreparedNativeRun {
	const runDir = join(options.artifactDir, "native-runs", options.id);
	mkdirSync(runDir, { recursive: true, mode: 0o700 });
	const processRun = createProcessRun(options.id, join(runDir, "process.json"));
	const resume = options.resume;
	const plan = options.plan;
	if (!resume && !plan)
		throw new Error("A native launch needs a plan or a resume request.");
	if (resume && resume.mode !== resume.marker.loadout.mode)
		throw new Error(
			`Native resume must keep the recorded ${resume.marker.loadout.mode} mode.`,
		);
	const markerFile =
		resume?.markerFile ??
		join(options.artifactDir, "native-sessions", `${options.id}.json`);
	const sessionKey = resume?.marker.sessionKey ?? options.id;
	const harness = resume?.marker.harness ?? plan!.spec.harness;
	const loadout = resume?.marker.loadout;
	const mode: NativeRunMode = resume ? resume.mode : plan!.spec.mode;
	const model =
		options.model !== undefined
			? options.model
			: resume
				? (loadout?.model ?? null)
				: (plan!.models[0] ?? null);
	const spawnAgents = resume
		? (loadout?.spawnAgents ?? null)
		: plan!.spec.spawnAgents;
	const driver = createNativeDriver({
		mode,
		firstTurn: {
			id: options.id,
			kind: resume ? "resume" : "initial",
			ackTimeoutMs: harness === "claude" ? CLAUDE_START_ACK_MS : KIRO_ACK_MS,
		},
	});
	const run: NativeRun = {
		version: 1,
		harness,
		kind: resume ? "resume" : "fresh",
		processRun,
		markerFile,
		runDir,
		sessionKey,
		model,
		driver,
		loadoutSha256: resume?.marker.loadoutSha256 ?? "",
	};
	let leaseHeld = false;
	try {
		mkdirSync(dirname(markerFile), { recursive: true, mode: 0o700 });
		if (resume) {
			acquireNativeSessionLease(markerFile, sessionKey, processRun);
			leaseHeld = true;
		}
		// A durable worktree lease survives parent crashes: a later driver
		// (resume or another parent) is refused until this run's owned
		// processes, including descendants, are provably gone.
		if (options.worktree?.manifestFile) {
			const path = nativeWorktreeLeaseFile(options.worktree.manifestFile);
			const parent = currentLeaseParent(options.inspector);
			if (options.worktreeLeaseFrom)
				handoffRunLease(path, options.worktreeLeaseFrom, processRun, parent);
			else
				acquireRunLease(
					path,
					options.worktree.path,
					processRun,
					"Native worktree",
					options.inspector,
					parent,
				);
			run.worktreeLease = path;
		}
		if (spawnAgents)
			run.bridge = prepareNativeBridge({
				runDir,
				runId: options.id,
				agents: spawnAgents,
			});
		if (resume) {
			// Fail-closed recheck immediately before launch: the loadout,
			// identity, and skill snapshots must still verify exactly.
			const reason = verifyNativeSessionMarker(
				resume.marker,
				resume.markerFile,
			);
			if (reason)
				throw new Error(`Native resume refused: the session ${reason}.`);
		}
		const firstText = resume
			? buildNativeTask(resume.message, { mode })
			: plan!.initialText;
		const tagged = nativePrompt(firstText, driver.turns[0].token);
		let identity: string | null;
		let identityFile: string | undefined;
		if (resume) {
			identity = readIdentityText(resume.marker);
			identityFile = resume.marker.identityFile;
		} else {
			identity = plan!.spec.identityText;
			if (identity) {
				identityFile = join(dirname(markerFile), `${options.id}.identity.md`);
				writePrivate(identityFile, identity);
			}
		}
		const spec = plan?.spec;
		const tools = loadout?.tools ?? spec!.tools;
		const nativeTools = loadout?.nativeTools ?? spec!.nativeTools;
		const kiroMcp = resume?.kiroMcp ?? plan?.kiroMcp;
		const thinking = loadout ? loadout.thinking : spec!.thinking;
		const promptMode = loadout ? loadout.promptMode : spec!.promptMode;
		// Claude receives the identity through its prompt channel only when the
		// role asked for one; resume replays exactly the recorded channel.
		const identityChannel = harness === "kiro" || promptMode ? identity : null;
		let command: string;
		if (harness === "claude") {
			run.claude = prepareClaudeRun({
				runDir,
				processRun,
				cwd: options.cwd,
				sessionId: resume?.marker.nativeSessionId ?? randomUUID(),
				resume: !!resume,
				mcpServer: run.bridge?.server,
			});
			command = claudeCommand(run.claude, tagged, {
				tools: nativeTools.join(","),
				model,
				thinking,
				identity: identityChannel,
				promptMode,
			});
		} else {
			run.kiro = prepareKiroRun({
				runDir,
				processRun,
				cwd: options.cwd,
				markerFile,
				tools: nativeTools,
				identity: identityChannel,
				resume: resume
					? {
							agentName: loadout!.kiroAgentName ?? "",
							// SAFETY: verifyNativeSessionMarker requires a Kiro session ID.
							sessionId: resume.marker.nativeSessionId!,
						}
					: undefined,
				mcpServer: run.bridge?.server,
				personalMcp: kiroMcp,
			});
			command = kiroCommand(run.kiro, tagged, { model, thinking });
		}
		if (!resume) {
			writeSkillSnapshots(plan!.skills);
			let lineage: NativeLoadout["lineage"];
			if (plan!.lineage) {
				lineage = {
					mode: plan!.lineage.mode,
					parentSessionFile: plan!.lineage.parentSessionFile,
				};
				const context = plan!.lineage.context;
				if (context) {
					const file = join(runDir, "inherited-context.md");
					writePrivate(file, `${context.text}\n`);
					lineage.context = {
						file,
						sha256: context.sha256,
						bytes: context.bytes,
						messages: context.messages,
						omittedMessages: context.omittedMessages,
					};
				}
			}
			const newLoadout: NativeLoadout = {
				tools,
				nativeTools,
				model,
				thinking,
				promptMode,
				identitySha256: identity ? sha256(identity) : null,
				mode,
				sessionMode: spec!.sessionMode,
				skills: plan!.skills.map((skill) => {
					const record: NativeLoadout["skills"][number] = {
						name: skill.name,
						filePath: skill.filePath,
						sha256: skill.sha256,
						bytes: skill.bytes,
					};
					if (skill.snapshot)
						record.snapshot = {
							dir: skill.snapshot.dir,
							sha256: skill.snapshot.sha256,
						};
					return record;
				}),
				spawnAgents,
			};
			if (run.kiro) {
				newLoadout.kiroAgentName = run.kiro.profileName;
				if (kiroMcp)
					newLoadout.kiroMcp = {
						sourceFile: kiroMcp.sourceFile,
						servers: kiroMcp.servers.map((server) => ({ ...server })),
					};
			}
			if (lineage) newLoadout.lineage = lineage;
			if (options.worktree) newLoadout.worktree = options.worktree;
			// A marker, not a fabricated Pi transcript: it anchors identity,
			// loadout, and result references without native history.
			const marker: NativeSessionMarker = {
				version: 2,
				type: "native_session",
				harness,
				nativeSessionId: run.claude?.sessionId ?? null,
				sessionKey,
				runId: options.id,
				name: options.name,
				cwd: run.claude?.cwd ?? run.kiro!.cwd,
				createdAt: options.now ?? Date.now(),
				loadout: newLoadout,
				loadoutSha256: loadoutSha256(newLoadout),
			};
			if (options.agent) marker.agent = options.agent;
			if (identityFile) marker.identityFile = identityFile;
			writeNativeSessionMarker(markerFile, marker);
			run.loadoutSha256 = marker.loadoutSha256;
			acquireNativeSessionLease(markerFile, sessionKey, processRun);
			leaseHeld = true;
		}
		appendNativeRunRecord(markerFile, {
			runId: options.id,
			kind: run.kind,
			event: "started",
			model,
		});
		return { run, command };
	} catch (error) {
		// No process can exist yet: the command has not been produced.
		if (run.kiro) cleanupKiroRun(run.kiro);
		if (leaseHeld) releaseNativeSessionLease(markerFile, options.id);
		// A handed-off lease stays with this (never-started) run's parent
		// reservation; the fallback sequence releases it at final settlement.
		if (run.worktreeLease && !options.worktreeLeaseFrom)
			releaseRunLease(run.worktreeLease, options.id);
		throw error;
	}
}

export type NativeResumeCheck =
	| {
			ok: true;
			marker: NativeSessionMarker;
			kiroMcp?: KiroMcpSelection;
	  }
	| { ok: false; error: string };

/**
 * Verify a native marker can be resumed with exactly its recorded loadout,
 * before any Herdr resource exists. Persistent specialists never revive.
 */
export function checkNativeResume(
	marker: AnyNativeSessionMarker,
	markerFile: string,
	inspector: ProcessInspector = defaultProcessInspector,
): NativeResumeCheck {
	const reason = verifyNativeSessionMarker(marker, markerFile);
	if (reason) return { ok: false, error: `the session ${reason}` };
	// SAFETY: verifyNativeSessionMarker rejects every non-v2 marker.
	const current = marker as NativeSessionMarker;
	if (current.loadout.mode === "persistent")
		return {
			ok: false,
			error:
				"it belongs to a persistent specialist; stopped or crashed specialists do not revive. Spawn a new specialist",
		};
	if (current.loadout.spawnAgents && !inspector.procRoot)
		return {
			ok: false,
			error:
				"its nested-spawn grant needs verified process ownership (Linux /proc)",
		};
	let kiroMcp: KiroMcpSelection | undefined;
	if (current.loadout.kiroMcp) {
		try {
			kiroMcp = revalidateKiroMcpSelection(current.loadout.kiroMcp);
		} catch (error) {
			return {
				ok: false,
				error: `its personal Kiro MCP grant is unavailable: ${error instanceof Error ? error.message : String(error)}`,
			};
		}
	}
	const lease = inspectNativeSessionLease(markerFile, inspector);
	if (lease.kind === "held" || lease.kind === "invalid")
		return {
			ok: false,
			error: `the native session is still leased: ${lease.reason}`,
		};
	return { ok: true, marker: current, kiroMcp };
}

/** Native session identity, from the parent choice (Claude) or owned hook (Kiro). */
export function nativeSessionId(run: NativeRun): string | undefined {
	if (run.claude) return run.claude.sessionId;
	if (run.kiro?.nativeSessionId) return run.kiro.nativeSessionId;
	try {
		const data = JSON.parse(readFileSync(run.markerFile, "utf8"));
		return isNonEmptyString(data?.nativeSessionId)
			? data.nativeSessionId
			: undefined;
	} catch {
		return undefined;
	}
}

export function nativeTurnAdapter(run: NativeRun): NativeTurnAdapter {
	if (run.claude) return claudeAdapter(run.claude);
	if (run.kiro) return kiroAdapter(run.kiro);
	throw new Error("Native harness state is missing.");
}

/** Correlated native turn phase for widget projection only, never completion. */
export function nativeTurnPhase(run: NativeRun): string | undefined {
	return nativeTurnAdapter(run).readState()?.phase;
}

/** Start acknowledgement deadlines when the process is actually launched. */
export function markNativeSubmitted(run: NativeRun, now = Date.now()): void {
	run.driver.turns[0].submittedAt ??= now;
}

export function tickNativeRun(
	run: NativeRun,
	send: (text: string) => void,
	now = Date.now(),
	onSettled?: (turn: NativeTurn) => void,
): void {
	tickNativeDriver(run.driver, nativeTurnAdapter(run), send, now, onSettled);
}

export function nativeOutcome(
	run: NativeRun,
	exit: { reason: string; exitCode: number; errorMessage?: string },
	onSettled?: (turn: NativeTurn) => void,
): NativeRunOutcome {
	const outcome = nativeDriverOutcome(
		run.driver,
		nativeTurnAdapter(run),
		exit,
		onSettled,
	);
	// A hook error means some receipt may be missing: no-work is unprovable.
	if (readHookError(run.processRun)) outcome.neverStarted = false;
	return outcome;
}

/** Remove only owned, unchanged transient files that live outside artifacts. */
function cleanupNativeRun(run: NativeRun): void {
	if (run.kiro) cleanupKiroRun(run.kiro);
}

/**
 * Remove owned transient files and release the session lease only after the
 * owned native process is proven gone. With an unconfirmed exit the Kiro
 * profile, the lease, and all evidence are retained, because a live native
 * process still depends on them.
 */
export function releaseNativeRun(
	run: NativeRun,
	exit: ExitConfirmation = confirmProcessExit(run.processRun),
	outcome?: string,
	options: {
		/**
		 * Keep the parent-reserved worktree lease: a fallback attempt may
		 * follow, and the sequence releases it at final settlement.
		 */
		keepWorktreeLease?: boolean;
	} = {},
): ExitConfirmation {
	if (exit.kind === "confirmed") {
		try {
			cleanupNativeRun(run);
		} catch {
			// Retained owned files are safer than deleting uncertain state.
		}
		releaseNativeSessionLease(run.markerFile, run.processRun.id);
		if (run.worktreeLease && !options.keepWorktreeLease)
			releaseRunLease(run.worktreeLease, run.processRun.id);
		if (outcome)
			appendNativeRunRecord(run.markerFile, {
				runId: run.processRun.id,
				kind: run.kind,
				event: "settled",
				outcome,
			});
	}
	return exit;
}

/** Files retained for manual inspection while exit is unconfirmed. */
export function retainedNativeEvidence(run: NativeRun): string[] {
	const retained = [run.markerFile, run.runDir];
	if (run.kiro?.profileHash && !run.kiro.cleanedUp)
		retained.push(run.kiro.profilePath);
	return retained;
}

export interface NativeHarnessOperations {
	/** Verify CLI and hook prerequisites before Herdr resources exist. */
	assertAvailable(harness: NativeHarnessName): void;
	/** Validate prepared native configuration before the process starts. */
	validate(run: NativeRun): void;
}

const defaultExec: ExecFile = (file, args, options) =>
	execFileSync(file, args, {
		encoding: "utf8",
		timeout: options.timeout,
		stdio: "pipe",
	});

export function createNativeHarnessOperations(
	exec: ExecFile = defaultExec,
): NativeHarnessOperations {
	return {
		assertAvailable(harness) {
			try {
				exec("python3", ["-c", "import fcntl"], { timeout: 5000 });
			} catch (error) {
				throw new Error(
					`Native ${nativeHarnessLabel(harness)} hooks require python3 with fcntl: ${error instanceof Error ? error.message : String(error)}`,
				);
			}
			if (harness === "kiro") {
				assertKiroAvailable(exec);
				return;
			}
			try {
				exec("claude", ["--version"], { timeout: 5000 });
			} catch (error) {
				throw new Error(
					`Claude Code CLI is unavailable: ${error instanceof Error ? error.message : String(error)}. Install claude and ensure it is on PATH.`,
				);
			}
		},
		validate(run) {
			if (run.kiro) validateKiroProfile(run.kiro, exec);
		},
	};
}

export type NativeStartupBlock = "claude-workspace-trust";

export interface NativeCompletionResult {
	reason: "done" | "error";
	exitCode: number;
	errorMessage?: string;
	/** A diagnosed human-only startup gate; never completion/no-work evidence. */
	startupBlock?: NativeStartupBlock;
	/** Set when the run ended because a parent interrupt could not settle. */
	interrupted?: boolean;
	/**
	 * Whether the owned native process is proven gone. Only a confirmed exit
	 * permits owned-file cleanup or a reviewable worktree handoff.
	 */
	exit: ExitConfirmation;
}

export interface NativeCompletionOptions {
	intervalMs?: number;
	/** Launch acknowledgement deadline for the process receipt, not task duration. */
	startupTimeoutMs?: number;
	/** Bounded wait for exit evidence after a supervision failure terminates the run. */
	terminationGraceMs?: number;
	/** Pane inspection cadence in ticks; inspections update the widget only. */
	inspectEveryTicks?: number;
	send(text: string): void;
	/** Signal only verified owned processes; see terminateProcessRun. */
	terminate(): TerminationResult | void;
	inspector?: ProcessInspector;
	inspectPane?: () => Promise<PaneInspection>;
	/** Bounded visible-pane text used only to diagnose a known startup gate. */
	readVisiblePane?: () => Promise<string>;
	onPaneInspection?: (inspection: PaneInspection, observedAt: number) => void;
	onStarted?: (observedAt: number) => void;
	onTick?: () => void;
	/** A tagged turn reached a terminal outcome (persistent task delivery). */
	onTurnSettled?: (turn: NativeTurn) => void;
	now?: () => number;
	delay?: (milliseconds: number, signal: AbortSignal) => Promise<void>;
}

const ABORT_MESSAGE = "Aborted while waiting for subagent to finish";

function readHookError(run: ProcessRun): string | null {
	try {
		const data = JSON.parse(readFileSync(errorReceiptFile(run), "utf8"));
		if (data?.type !== "error") return null;
		return isNonEmptyString(data.errorMessage?.trim())
			? data.errorMessage
			: "Native lifecycle hook reported an error without details.";
	} catch {
		return null;
	}
}

function abortableDelay(ms: number, signal: AbortSignal): Promise<void> {
	if (signal.aborted) return Promise.reject(new Error(ABORT_MESSAGE));
	return new Promise((resolve, reject) => {
		const onAbort = () => {
			clearTimeout(timer);
			reject(new Error(ABORT_MESSAGE));
		};
		const timer = setTimeout(() => {
			signal.removeEventListener("abort", onAbort);
			resolve();
		}, ms);
		signal.addEventListener("abort", onAbort, { once: true });
	});
}

/**
 * Wait for a native child's durable process exit. Success still requires the
 * driver outcome's correlated turn evidence. A bounded screen read may diagnose
 * one known startup gate, but is never completion/no-work evidence; Herdr
 * idle/done status is never completion.
 */
export async function waitForNativeCompletion(
	run: NativeRun,
	signal: AbortSignal,
	options: NativeCompletionOptions,
): Promise<NativeCompletionResult> {
	const now = options.now ?? Date.now;
	const delay = options.delay ?? abortableDelay;
	const inspector = options.inspector ?? defaultProcessInspector;
	const intervalMs = options.intervalMs ?? 1000;
	const startupTimeoutMs = options.startupTimeoutMs ?? 30_000;
	const terminationGraceMs = options.terminationGraceMs ?? 5_000;
	const inspectEvery = Math.max(1, options.inspectEveryTicks ?? 5);
	const start = now();
	let started = false;
	let missing = 0;
	let ticks = 0;
	let failure: string | undefined;
	let startupBlock: NativeStartupBlock | undefined;
	let interrupted = false;
	let terminatedAt: number | undefined;
	let termination: TerminationResult | void = undefined;
	let wrapperExitedAt: number | undefined;

	for (;;) {
		if (signal.aborted) throw new Error(ABORT_MESSAGE);
		const state = readProcessRunState(run.processRun, inspector);
		if (state.kind === "exited") {
			const exit = confirmProcessExit(run.processRun, inspector);
			// Owned descendants that outlive the wrapper keep the run alive.
			// Wait a bounded time for them; never signal or finalize early.
			wrapperExitedAt ??= now();
			if (
				exit.kind === "unconfirmed" &&
				now() - wrapperExitedAt <= terminationGraceMs
			) {
				await delay(intervalMs, signal);
				continue;
			}
			const error = failure ?? readHookError(run.processRun);
			const result: NativeCompletionResult = error
				? {
						reason: "error",
						exitCode: state.exitCode || 1,
						errorMessage: error,
						exit,
					}
				: { reason: "done", exitCode: state.exitCode, exit };
			if (startupBlock) result.startupBlock = startupBlock;
			if (interrupted) result.interrupted = true;
			return result;
		}
		if (state.kind !== "not-started" && !started) {
			started = true;
			options.onStarted?.(now());
		}
		if (state.kind === "running") missing = 0;
		else if (state.kind === "gone" || started) missing++;
		// Allow intervening reads for the exit trap's atomic rename to finish.
		if (missing >= 3)
			failure ??=
				"Native process disappeared or lost its run receipt without reporting an exit.";
		if (!started && now() - start >= startupTimeoutMs)
			failure ??=
				"Native subagent did not acknowledge startup with a valid process receipt within the launch deadline.";

		if (failure) {
			if (terminatedAt === undefined) {
				terminatedAt = now();
				writeCancelMarker(run.processRun);
				try {
					termination = options.terminate();
				} catch (error) {
					termination = {
						kind: "unverifiable",
						reason: error instanceof Error ? error.message : String(error),
					};
				}
			}
			const exit = confirmProcessExit(run.processRun, inspector);
			let settled: NativeCompletionResult | undefined;
			if (exit.kind === "confirmed")
				settled = {
					reason: "error",
					exitCode: exit.exitCode || 1,
					errorMessage: failure,
					exit,
				};
			else if (now() - terminatedAt > terminationGraceMs) {
				const signalled =
					termination?.kind === "unverifiable"
						? ` Termination was refused because ownership could not be verified (${termination.reason}).`
						: "";
				settled = {
					reason: "error",
					exitCode: 1,
					errorMessage: `${failure} Native process exit is unconfirmed: ${exit.reason}.${signalled}`,
					exit,
				};
			}
			if (settled) {
				if (interrupted) settled.interrupted = true;
				if (startupBlock) settled.startupBlock = startupBlock;
				return settled;
			}
		} else if (started) {
			failure = readHookError(run.processRun) ?? undefined;
			if (!failure) {
				try {
					tickNativeRun(
						run,
						(text) => {
							if (!isProcessRunLive(run.processRun, inspector))
								throw new Error("Native process exited before input delivery.");
							options.send(text);
						},
						now(),
						options.onTurnSettled,
					);
				} catch (error) {
					failure = error instanceof Error ? error.message : String(error);
					interrupted =
						error instanceof NativeTurnFailure && error.kind === "interrupted";
				}
			}
		}

		if (options.inspectPane && ticks % inspectEvery === 0) {
			let inspection: PaneInspection;
			try {
				inspection = await options.inspectPane();
			} catch {
				inspection = { kind: "unavailable", error: "inspectPane threw" };
			}
			options.onPaneInspection?.(inspection, now());
			const first = run.driver.turns[0];
			if (
				!failure &&
				run.harness === "claude" &&
				(first.kind === "initial" || first.kind === "resume") &&
				first.submittedAt !== undefined &&
				!first.acknowledged &&
				!first.outcome &&
				run.driver.turns.length === 1 &&
				inspection.kind === "present" &&
				inspection.agentStatus === "blocked" &&
				options.readVisiblePane
			) {
				try {
					const visible = (await options.readVisiblePane()).slice(-16_384);
					// A hook receipt may arrive while the pane read is in flight. Re-read
					// authoritative state before acting so screen evidence cannot race any
					// hook progress or hook failure.
					const receipt = nativeTurnAdapter(run).readState();
					if (
						isClaudeWorkspaceTrustPrompt(visible) &&
						receipt === null &&
						!readHookError(run.processRun)
					) {
						startupBlock = "claude-workspace-trust";
						failure = `Claude Code workspace trust blocked startup in ${run.claude!.cwd}. The prompt was not answered; inspect and close retained pane manually.`;
						terminatedAt = now();
						writeCancelMarker(run.processRun);
						try {
							termination = options.terminate();
						} catch (error) {
							termination = {
								kind: "unverifiable",
								reason: error instanceof Error ? error.message : String(error),
							};
						}
					}
				} catch {
					// Unknown/read-error evidence keeps the normal 120-second fallback.
				}
			}
		}
		ticks++;
		options.onTick?.();
		await delay(intervalMs, signal);
	}
}

export { currentNativeTurn };
