// This content is generated by AI (Kiro)
/**
 * Native harness seam for roles declaring `cli: claude` or `cli: kiro`.
 *
 * Only execution varies here: capability validation, native command/hook
 * preparation, correlated turn evidence, process receipts, and owned-file
 * cleanup. Herdr pane/worktree provisioning and parent result delivery stay in
 * the common launch and watch paths.
 *
 * The receipt and correlation approach is ported from
 * zhengfran/pi-interactive-subagents (MIT, Copyright (c) 2026 HazAT and
 * contributors), `pi-extension/subagents/poll.ts`.
 */
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { randomUUID } from "node:crypto";
import {
	NATIVE_EFFORT_LEVELS,
	claudeCommand,
	claudeOutcome,
	claudeTools,
	prepareClaudeRun,
	readClaudeState,
	tickClaudeRun,
	type ClaudeRun,
	type NativeTurnOutcome,
} from "./claude.ts";
import { isNonEmptyString } from "./type-guards.ts";
import {
	assertKiroAvailable,
	cleanupKiroRun,
	kiroCommand,
	kiroOutcome,
	kiroTools,
	prepareKiroRun,
	readKiroState,
	tickKiroRun,
	validateKiroProfile,
	type ExecFile,
	type KiroRun,
} from "./kiro.ts";
import {
	confirmProcessExit,
	createProcessRun,
	defaultProcessInspector,
	errorReceiptFile,
	isProcessRunLive,
	readProcessRunState,
	writeCancelMarker,
	type ExitConfirmation,
	type ProcessInspector,
	type ProcessRun,
	type TerminationResult,
} from "./process-run.ts";
import type { PaneInspection } from "./lifecycle.ts";

export const NATIVE_HARNESSES = ["claude", "kiro"] as const;
export type NativeHarnessName = (typeof NATIVE_HARNESSES)[number];

export function isNativeHarnessName(value: any): value is NativeHarnessName {
	return value === "claude" || value === "kiro";
}

export function nativeHarnessLabel(harness: NativeHarnessName): string {
	return harness === "claude" ? "Claude Code" : "Kiro";
}

/** Pi-only tools a native child can never receive. */
const PI_CHILD_TOOLS = new Set(["caller_ping", "subagent_done"]);
const PI_SPAWNING_TOOLS = new Set([
	"subagent",
	"subagent_interrupt",
	"subagents_list",
	"subagent_resume",
	"subagent_send",
	"subagent_stop",
	"subagents_write_task_models",
	"worktree_list",
	"worktree_remove",
]);
const NATIVE_MODEL_ID = /^[A-Za-z0-9][A-Za-z0-9._:/@[\]-]{0,199}$/;

/** Role fields relevant to native harness capability validation. */
export interface NativeRoleDefinition {
	name: string;
	cli: NativeHarnessName;
	model?: string;
	tools?: string;
	skills?: string;
	thinking?: string;
	spawning?: boolean;
	persistent?: boolean;
	autoExit?: boolean;
	interactive?: boolean;
	sessionMode?: string;
	systemPromptMode?: "append" | "replace";
	body?: string;
}

/** Per-call overrides that may conflict with native harness capabilities. */
export interface NativeLaunchOverrides {
	model?: string;
	thinking?: string;
	tools?: string;
	skills?: string;
	fork?: boolean;
	persistent?: boolean;
	interactive?: boolean;
}

export interface NativeLaunchSpec {
	harness: NativeHarnessName;
	/** Validated Pi-vocabulary allowlist that was mapped. */
	tools: string;
	/** Native tool names: Claude `--tools` entries or Kiro profile tools. */
	nativeTools: string[];
	/** Native model ID passed through to the CLI, never a Pi provider ref. */
	model: string | null;
	thinking: string | null;
	/** Identity passed through a native system-prompt channel, if any. */
	identity: string | null;
	promptMode: "append" | "replace" | null;
	/** Identity folded into the initial task when no prompt channel is used. */
	roleBlock: string;
}

export class NativeCapabilityError extends Error {
	readonly code = "native-harness-unsupported";
	constructor(role: string, harness: NativeHarnessName, reason: string) {
		super(
			`Role "${role}" uses the native ${nativeHarnessLabel(harness)} harness (cli: ${harness}), which ${reason}`,
		);
		this.name = "NativeCapabilityError";
	}
}

/**
 * Resolve and validate a native launch before any Herdr resource exists.
 * Without overrides this is also the discovery-time role validation.
 */
export function resolveNativeLaunchSpec(
	role: NativeRoleDefinition,
	overrides: NativeLaunchOverrides = {},
): NativeLaunchSpec {
	const fail = (reason: string): never => {
		throw new NativeCapabilityError(role.name, role.cli, reason);
	};
	if (overrides.persistent ?? role.persistent)
		fail(
			"does not support persistent specialists. Remove persistent, or use a Pi-backed role for turn-based follow-up work.",
		);
	const sessionMode =
		overrides.fork === true
			? "fork"
			: overrides.fork === false
				? "standalone"
				: (role.sessionMode ?? "standalone");
	if (sessionMode !== "standalone")
		fail(
			`supports only standalone sessions; ${sessionMode} (fork/lineage) context cannot be represented natively. Omit fork and session-mode, or use a Pi-backed role.`,
		);
	if ((overrides.skills ?? role.skills)?.trim())
		fail("cannot auto-load Pi skills. Remove skills, or use a Pi-backed role.");
	if (role.spawning === true)
		fail(
			"cannot spawn nested subagents. Set spawning: false or omit it; the parent owns delegation.",
		);
	if (role.autoExit !== true)
		fail(
			"supports only autonomous fresh runs. Set auto-exit: true; interactive native sessions are not supported yet.",
		);
	if ((overrides.interactive ?? role.interactive) === true)
		fail(
			"supports only autonomous runs; interactive: true is not supported. Remove interactive or set it to false.",
		);

	const tools = (overrides.tools ?? role.tools)?.trim();
	const requested = (tools ?? "")
		.split(",")
		.map((tool) => tool.trim())
		.filter(Boolean);
	const piChildTools = requested.filter((tool) => PI_CHILD_TOOLS.has(tool));
	if (piChildTools.length)
		fail(
			`cannot provide Pi child tools (${piChildTools.join(", ")}); caller_ping and subagent_done are Pi-only. Remove them from tools.`,
		);
	const spawningTools = requested.filter((tool) => PI_SPAWNING_TOOLS.has(tool));
	if (spawningTools.length)
		fail(
			`cannot spawn nested subagents or manage worktrees (${spawningTools.join(", ")}). Remove them from tools.`,
		);
	let nativeTools: string[] = [];
	try {
		nativeTools =
			role.cli === "claude" ? claudeTools(tools).split(",") : kiroTools(tools);
	} catch (error) {
		fail(
			`requires a strictly mappable tools allowlist: ${error instanceof Error ? error.message : String(error)}`,
		);
	}

	const model = (overrides.model ?? role.model)?.trim() || null;
	if (model) {
		if (/^task:/i.test(model))
			fail(
				"does not support task-category model routing. Pass an exact native model ID or omit model.",
			);
		if (model.includes(","))
			fail(
				"does not support Pi model fallback lists. Pass one exact native model ID.",
			);
		if (!NATIVE_MODEL_ID.test(model))
			fail(`cannot use model "${model}"; expected one native model ID.`);
	}
	const thinking = (overrides.thinking ?? role.thinking)?.trim() || null;
	if (thinking && !NATIVE_EFFORT_LEVELS.some((level) => level === thinking))
		fail(
			`cannot represent thinking level ${thinking} (supported: ${NATIVE_EFFORT_LEVELS.join(", ")}; omit for the native default).`,
		);
	if (role.cli === "kiro" && role.systemPromptMode === "replace")
		fail(
			"cannot replace the native Kiro system prompt. Use system-prompt: append or omit it.",
		);

	const identity = role.body?.trim() || null;
	// Kiro always carries the role body in its owned profile prompt. Claude
	// follows Pi: an explicit system-prompt mode uses the native flag,
	// otherwise the body is part of the initial task wrapper.
	const identityChannel =
		role.cli === "kiro" ? identity : role.systemPromptMode ? identity : null;
	return {
		harness: role.cli,
		tools: requested.join(","),
		nativeTools,
		model,
		thinking,
		identity: identityChannel,
		promptMode:
			role.cli === "kiro" ? "append" : (role.systemPromptMode ?? null),
		roleBlock: identity && !identityChannel ? identity : "",
	};
}

const NATIVE_MODE_HINT =
	"Complete your task autonomously. When you are finished, simply stop — your session ends automatically.";
const NATIVE_SUMMARY_INSTRUCTION =
	"Your FINAL assistant message should summarize what you accomplished.";

export function buildNativeTask(task: string, roleBlock: string): string {
	return [roleBlock, NATIVE_MODE_HINT, task, NATIVE_SUMMARY_INSTRUCTION]
		.filter((part) => part.trim())
		.join("\n\n");
}

export interface NativeSessionMarker {
	version: 1;
	type: "native_session";
	harness: NativeHarnessName;
	/** Claude: parent-chosen UUID. Kiro: published by the owned hook. */
	nativeSessionId: string | null;
	runId: string;
	name: string;
	agent?: string;
	cwd: string;
	createdAt: number;
	resume: "unsupported";
	loadout: {
		tools: string;
		nativeTools: string[];
		model: string | null;
		thinking: string | null;
		promptMode: "append" | "replace" | null;
		autoExit: true;
		kiroProfile?: string;
		worktree?: {
			path: string;
			workspaceId: string;
			branch: string;
			baseSha: string;
		};
	};
}

export function readNativeSessionMarker(
	path: string,
): NativeSessionMarker | null {
	try {
		const data = JSON.parse(readFileSync(path, "utf8"));
		return data?.type === "native_session" &&
			data.version === 1 &&
			isNativeHarnessName(data.harness)
			? data
			: null;
	} catch {
		return null;
	}
}

export interface NativeRun {
	harness: NativeHarnessName;
	processRun: ProcessRun;
	markerFile: string;
	runDir: string;
	claude?: ClaudeRun;
	kiro?: KiroRun;
}

export interface PreparedNativeRun {
	run: NativeRun;
	/** Native CLI command, to be wrapped by supervisedCommand. */
	command: string;
}

export function prepareNativeRun(options: {
	id: string;
	artifactDir: string;
	cwd: string;
	name: string;
	agent?: string;
	task: string;
	spec: NativeLaunchSpec;
	worktree?: NativeSessionMarker["loadout"]["worktree"];
	now?: number;
}): PreparedNativeRun {
	const { spec } = options;
	const runDir = join(options.artifactDir, "native-runs", options.id);
	const markerFile = join(
		options.artifactDir,
		"native-sessions",
		`${options.id}.json`,
	);
	mkdirSync(runDir, { recursive: true, mode: 0o700 });
	mkdirSync(dirname(markerFile), { recursive: true, mode: 0o700 });
	const processRun = createProcessRun(options.id, join(runDir, "process.json"));
	const nativeSessionId = spec.harness === "claude" ? randomUUID() : null;
	const run: NativeRun = {
		harness: spec.harness,
		processRun,
		markerFile,
		runDir,
	};
	const task = buildNativeTask(options.task, spec.roleBlock);
	let command: string;
	if (spec.harness === "claude") {
		run.claude = prepareClaudeRun({
			runDir,
			processRun,
			cwd: options.cwd,
			sessionId: nativeSessionId!,
			now: options.now,
		});
		command = claudeCommand(run.claude, task, {
			tools: spec.nativeTools.join(","),
			model: spec.model,
			thinking: spec.thinking,
			identity: spec.identity,
			promptMode: spec.promptMode,
		});
	} else {
		run.kiro = prepareKiroRun({
			runDir,
			processRun,
			cwd: options.cwd,
			markerFile,
			tools: spec.nativeTools,
			identity: spec.identity,
			now: options.now,
		});
		command = kiroCommand(run.kiro, task, {
			model: spec.model,
			thinking: spec.thinking,
		});
	}
	// A marker, not a fabricated Pi transcript. It anchors identity, loadout,
	// and result references without mixing native history into Pi's format.
	const marker: NativeSessionMarker = {
		version: 1,
		type: "native_session",
		harness: spec.harness,
		nativeSessionId,
		runId: options.id,
		name: options.name,
		cwd: run.claude?.cwd ?? run.kiro!.cwd,
		createdAt: options.now ?? Date.now(),
		resume: "unsupported",
		loadout: {
			tools: spec.tools,
			nativeTools: spec.nativeTools,
			model: spec.model,
			thinking: spec.thinking,
			promptMode: spec.promptMode,
			autoExit: true,
		},
	};
	if (options.agent) marker.agent = options.agent;
	if (run.kiro) marker.loadout.kiroProfile = run.kiro.profilePath;
	if (options.worktree) marker.loadout.worktree = options.worktree;
	try {
		writeFileSync(markerFile, `${JSON.stringify(marker, null, 2)}\n`, {
			flag: "wx",
			mode: 0o600,
		});
	} catch (error) {
		// No process can exist yet: the command has not been produced.
		cleanupNativeRun(run);
		throw error;
	}
	return { run, command };
}

/** Native session identity, from the parent choice (Claude) or owned hook (Kiro). */
export function nativeSessionId(run: NativeRun): string | undefined {
	if (run.claude) return run.claude.sessionId;
	if (run.kiro?.nativeSessionId) return run.kiro.nativeSessionId;
	return readNativeSessionMarker(run.markerFile)?.nativeSessionId ?? undefined;
}

/** Correlated native turn phase for widget projection only, never completion. */
export function nativeTurnPhase(run: NativeRun): string | undefined {
	const state = run.claude
		? readClaudeState(run.claude)
		: run.kiro
			? readKiroState(run.kiro)
			: null;
	return state?.phase;
}

/** Start acknowledgement deadlines when the process is actually launched. */
export function markNativeSubmitted(run: NativeRun, now = Date.now()): void {
	if (run.claude) run.claude.submittedAt = now;
	if (run.kiro) run.kiro.submittedAt = now;
}

export function tickNativeRun(
	run: NativeRun,
	send: (text: string) => void,
	now = Date.now(),
): void {
	if (run.claude) tickClaudeRun(run.claude, send, now);
	else if (run.kiro) tickKiroRun(run.kiro, send, now);
}

export function nativeOutcome(
	run: NativeRun,
	exit: { reason: string; exitCode: number; errorMessage?: string },
): NativeTurnOutcome {
	if (run.claude) return claudeOutcome(run.claude, exit);
	if (run.kiro) return kiroOutcome(run.kiro, exit);
	return { completed: false, summary: "Native harness state is missing." };
}

/** Remove only owned, unchanged transient files that live outside artifacts. */
function cleanupNativeRun(run: NativeRun): void {
	if (run.kiro) cleanupKiroRun(run.kiro);
}

/**
 * Remove owned transient files only after the owned native process is proven
 * gone. With an unconfirmed exit the Kiro profile and all evidence are
 * retained, because a live Kiro process still depends on its profile.
 */
export function releaseNativeRun(
	run: NativeRun,
	exit: ExitConfirmation = confirmProcessExit(run.processRun),
): ExitConfirmation {
	if (exit.kind === "confirmed") {
		try {
			cleanupNativeRun(run);
		} catch {
			// Retained owned files are safer than deleting uncertain state.
		}
	}
	return exit;
}

/** Files retained for manual inspection while exit is unconfirmed. */
export function retainedNativeEvidence(run: NativeRun): string[] {
	const retained = [run.markerFile, run.runDir];
	if (run.kiro?.profileHash && !run.kiro.cleanedUp)
		retained.push(run.kiro.profilePath);
	return retained;
}

export interface NativeHarnessOperations {
	/** Verify CLI and hook prerequisites before Herdr resources exist. */
	assertAvailable(harness: NativeHarnessName): void;
	/** Validate prepared native configuration before the process starts. */
	validate(run: NativeRun): void;
}

const defaultExec: ExecFile = (file, args, options) =>
	execFileSync(file, args, {
		encoding: "utf8",
		timeout: options.timeout,
		stdio: "pipe",
	});

export function createNativeHarnessOperations(
	exec: ExecFile = defaultExec,
): NativeHarnessOperations {
	return {
		assertAvailable(harness) {
			try {
				exec("python3", ["-c", "import fcntl"], { timeout: 5000 });
			} catch (error) {
				throw new Error(
					`Native ${nativeHarnessLabel(harness)} hooks require python3 with fcntl: ${error instanceof Error ? error.message : String(error)}`,
				);
			}
			if (harness === "kiro") {
				assertKiroAvailable(exec);
				return;
			}
			try {
				exec("claude", ["--version"], { timeout: 5000 });
			} catch (error) {
				throw new Error(
					`Claude Code CLI is unavailable: ${error instanceof Error ? error.message : String(error)}. Install claude and ensure it is on PATH.`,
				);
			}
		},
		validate(run) {
			if (run.kiro) validateKiroProfile(run.kiro, exec);
		},
	};
}

export interface NativeCompletionResult {
	reason: "done" | "error";
	exitCode: number;
	errorMessage?: string;
	/**
	 * Whether the owned native process is proven gone. Only a confirmed exit
	 * permits owned-file cleanup or a reviewable worktree handoff.
	 */
	exit: ExitConfirmation;
}

export interface NativeCompletionOptions {
	intervalMs?: number;
	/** Launch acknowledgement deadline for the process receipt, not task duration. */
	startupTimeoutMs?: number;
	/** Bounded wait for exit evidence after a supervision failure terminates the run. */
	terminationGraceMs?: number;
	/** Pane inspection cadence in ticks; inspections update the widget only. */
	inspectEveryTicks?: number;
	send(text: string): void;
	/** Signal only verified owned processes; see terminateProcessRun. */
	terminate(): TerminationResult | void;
	inspector?: ProcessInspector;
	inspectPane?: () => Promise<PaneInspection>;
	onPaneInspection?: (inspection: PaneInspection, observedAt: number) => void;
	onStarted?: (observedAt: number) => void;
	onTick?: () => void;
	now?: () => number;
	delay?: (milliseconds: number, signal: AbortSignal) => Promise<void>;
}

const ABORT_MESSAGE = "Aborted while waiting for subagent to finish";

function readHookError(run: ProcessRun): string | null {
	try {
		const data = JSON.parse(readFileSync(errorReceiptFile(run), "utf8"));
		if (data?.type !== "error") return null;
		return isNonEmptyString(data.errorMessage?.trim())
			? data.errorMessage
			: "Native lifecycle hook reported an error without details.";
	} catch {
		return null;
	}
}

function abortableDelay(ms: number, signal: AbortSignal): Promise<void> {
	if (signal.aborted) return Promise.reject(new Error(ABORT_MESSAGE));
	return new Promise((resolve, reject) => {
		const onAbort = () => {
			clearTimeout(timer);
			reject(new Error(ABORT_MESSAGE));
		};
		const timer = setTimeout(() => {
			signal.removeEventListener("abort", onAbort);
			resolve();
		}, ms);
		signal.addEventListener("abort", onAbort, { once: true });
	});
}

/**
 * Wait for a native child's durable process exit. Success still requires the
 * harness outcome's correlated turn evidence; this loop never parses screen
 * text and never treats Herdr idle/done status as completion.
 */
export async function waitForNativeCompletion(
	run: NativeRun,
	signal: AbortSignal,
	options: NativeCompletionOptions,
): Promise<NativeCompletionResult> {
	const now = options.now ?? Date.now;
	const delay = options.delay ?? abortableDelay;
	const inspector = options.inspector ?? defaultProcessInspector;
	const intervalMs = options.intervalMs ?? 1000;
	const startupTimeoutMs = options.startupTimeoutMs ?? 30_000;
	const terminationGraceMs = options.terminationGraceMs ?? 5_000;
	const inspectEvery = Math.max(1, options.inspectEveryTicks ?? 5);
	const start = now();
	let started = false;
	let missing = 0;
	let ticks = 0;
	let failure: string | undefined;
	let terminatedAt: number | undefined;
	let termination: TerminationResult | void = undefined;

	for (;;) {
		if (signal.aborted) throw new Error(ABORT_MESSAGE);
		const state = readProcessRunState(run.processRun, inspector);
		if (state.kind === "exited") {
			const error = failure ?? readHookError(run.processRun);
			const exit = confirmProcessExit(run.processRun, inspector);
			return error
				? {
						reason: "error",
						exitCode: state.exitCode || 1,
						errorMessage: error,
						exit,
					}
				: { reason: "done", exitCode: state.exitCode, exit };
		}
		if (state.kind !== "not-started" && !started) {
			started = true;
			options.onStarted?.(now());
		}
		if (state.kind === "running") missing = 0;
		else if (state.kind === "gone" || started) missing++;
		// Allow intervening reads for the exit trap's atomic rename to finish.
		if (missing >= 3)
			failure ??=
				"Native process disappeared or lost its run receipt without reporting an exit.";
		if (!started && now() - start >= startupTimeoutMs)
			failure ??=
				"Native subagent did not acknowledge startup with a valid process receipt within the launch deadline.";

		if (failure) {
			if (terminatedAt === undefined) {
				terminatedAt = now();
				writeCancelMarker(run.processRun);
				try {
					termination = options.terminate();
				} catch (error) {
					termination = {
						kind: "unverifiable",
						reason: error instanceof Error ? error.message : String(error),
					};
				}
			}
			const exit = confirmProcessExit(run.processRun, inspector);
			if (exit.kind === "confirmed")
				return {
					reason: "error",
					exitCode: exit.exitCode || 1,
					errorMessage: failure,
					exit,
				};
			if (now() - terminatedAt > terminationGraceMs) {
				const signalled =
					termination?.kind === "unverifiable"
						? ` Termination was refused because ownership could not be verified (${termination.reason}).`
						: "";
				return {
					reason: "error",
					exitCode: 1,
					errorMessage: `${failure} Native process exit is unconfirmed: ${exit.reason}.${signalled}`,
					exit,
				};
			}
		} else if (started) {
			failure = readHookError(run.processRun) ?? undefined;
			if (!failure) {
				try {
					tickNativeRun(
						run,
						(text) => {
							if (!isProcessRunLive(run.processRun, inspector))
								throw new Error("Native process exited before input delivery.");
							options.send(text);
						},
						now(),
					);
				} catch (error) {
					failure = error instanceof Error ? error.message : String(error);
				}
			}
		}

		if (options.inspectPane && ticks % inspectEvery === 0) {
			let inspection: PaneInspection;
			try {
				inspection = await options.inspectPane();
			} catch {
				inspection = { kind: "unavailable", error: "inspectPane threw" };
			}
			options.onPaneInspection?.(inspection, now());
		}
		ticks++;
		options.onTick?.();
		await delay(intervalMs, signal);
	}
}
