// This content is generated by AI (Kiro)
/**
 * Authenticated local bridge for nested delegation from native children.
 *
 * A native child with a `spawn-agents` allowlist receives one owned stdio MCP
 * server (plugin/mcp/subagent-bridge.py) exposing a single `subagent` tool.
 * The server writes HMAC-signed requests into this run's private request
 * directory; the parent claims each request atomically and validates run
 * identity, MAC, nonce freshness, age, and that the sender PID carries this
 * run's owner token before applying the parent-side delegation policy.
 * Nothing shells out to Pi, and the child never receives Pi's own tools.
 *
 * Threat model: requests are bound to one live run. Stale, replayed,
 * misdirected, and sibling requests signed with another run's secret are
 * rejected. It is not a boundary against a malicious same-user process that
 * reads this run's 0600 files: such a process can already run any command the
 * user can.
 */
import { createHmac, randomBytes, timingSafeEqual } from "node:crypto";
import {
	mkdirSync,
	readdirSync,
	readFileSync,
	renameSync,
	writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
	defaultProcessInspector,
	readOwnership,
	type ProcessInspector,
	type ProcessRun,
} from "./process-run.ts";
import { isString } from "./type-guards.ts";

export const bridgeServerPath = join(
	dirname(fileURLToPath(import.meta.url)),
	"plugin/mcp/subagent-bridge.py",
);
export const BRIDGE_SERVER_NAME = "pi-subagents";
/** The MCP server waits this long for the parent's acknowledgement. */
export const BRIDGE_WAIT_MS = 60_000;
/** Requests older than this are stale; the server withdraws them first. */
const BRIDGE_MAX_AGE_MS = 50_000;
const BRIDGE_MAX_REQUESTS_PER_POLL = 8;
export const BRIDGE_MAX_TASK_BYTES = 16 * 1024;
const NONCE = /^[0-9a-f]{32}$/;
const AGENT_NAME = /^[A-Za-z0-9][A-Za-z0-9._-]{0,99}$/;

export interface NativeBridge {
	runId: string;
	dir: string;
	configFile: string;
	requestDir: string;
	claimedDir: string;
	responseDir: string;
	secret: string;
	agents: string[];
	seen: Set<string>;
	server: { name: string; command: string; args: string[] };
}

/** Length-prefixed MAC input shared with the Python bridge server. */
export function bridgeMac(secret: string, fields: readonly string[]): string {
	const payload = fields
		.map((field) => `${Buffer.byteLength(field, "utf8")}:${field};`)
		.join("");
	return createHmac("sha256", Buffer.from(secret, "hex"))
		.update(payload, "utf8")
		.digest("hex");
}

export function prepareNativeBridge(options: {
	runDir: string;
	runId: string;
	agents: readonly string[];
}): NativeBridge {
	const dir = join(options.runDir, "bridge");
	const bridge: NativeBridge = {
		runId: options.runId,
		dir,
		configFile: join(dir, "config.json"),
		requestDir: join(dir, "requests"),
		claimedDir: join(dir, "claimed"),
		responseDir: join(dir, "responses"),
		secret: randomBytes(32).toString("hex"),
		agents: [...options.agents],
		seen: new Set(),
		server: { name: BRIDGE_SERVER_NAME, command: "python3", args: [] },
	};
	for (const path of [
		dir,
		bridge.requestDir,
		bridge.claimedDir,
		bridge.responseDir,
	])
		mkdirSync(path, { recursive: true, mode: 0o700 });
	writeFileSync(
		bridge.configFile,
		`${JSON.stringify({
			version: 1,
			run_id: bridge.runId,
			secret: bridge.secret,
			request_dir: bridge.requestDir,
			response_dir: bridge.responseDir,
			agents: bridge.agents,
			wait_ms: BRIDGE_WAIT_MS,
			max_task_bytes: BRIDGE_MAX_TASK_BYTES,
		})}\n`,
		{ flag: "wx", mode: 0o600 },
	);
	bridge.server.args = [bridgeServerPath, bridge.configFile];
	return bridge;
}

export interface BridgeRequest {
	nonce: string;
	pid: number;
	createdAt: number;
	agent: string;
	name: string;
	task: string;
}

export interface BridgeRejection {
	file: string;
	nonce?: string;
	reason: string;
}

export interface BridgeCollection {
	requests: BridgeRequest[];
	rejected: BridgeRejection[];
}

/** The parent's acknowledgement for one nested-spawn request. */
export interface BridgeResponse {
	accepted: boolean;
	text: string;
}

function macMatches(expected: string, actual: any): boolean {
	if (!isString(actual) || actual.length !== expected.length) return false;
	return timingSafeEqual(Buffer.from(expected), Buffer.from(actual));
}

/**
 * Claim and authenticate pending requests. Only claimed files are processed,
 * so a request the server withdrew after its wait deadline never launches.
 */
export function collectBridgeRequests(
	bridge: NativeBridge,
	processRun: ProcessRun,
	now = Date.now(),
	inspector: ProcessInspector = defaultProcessInspector,
): BridgeCollection {
	const requests: BridgeRequest[] = [];
	const rejected: BridgeRejection[] = [];
	let names: string[];
	try {
		names = readdirSync(bridge.requestDir)
			.filter((name) => name.endsWith(".json"))
			.sort();
	} catch {
		return { requests, rejected };
	}
	for (const [index, name] of names.entries()) {
		const source = join(bridge.requestDir, name);
		const claimed = join(bridge.claimedDir, name);
		try {
			renameSync(source, claimed);
		} catch {
			continue; // Withdrawn by the server, or claimed already.
		}
		const reject = (reason: string, nonce?: string) => {
			const rejection: BridgeRejection = { file: claimed, reason };
			if (nonce) rejection.nonce = nonce;
			rejected.push(rejection);
		};
		if (index >= BRIDGE_MAX_REQUESTS_PER_POLL) {
			reject("too many simultaneous requests");
			continue;
		}
		let data: any;
		try {
			data = JSON.parse(readFileSync(claimed, "utf8"));
		} catch {
			reject("unreadable request");
			continue;
		}
		const nonce = isString(data?.nonce) ? data.nonce : "";
		if (!NONCE.test(nonce) || name !== `${nonce}.json`) {
			reject("malformed nonce");
			continue;
		}
		if (
			data.version !== 1 ||
			!isString(data.run_id) ||
			!Number.isInteger(data.seq) ||
			!Number.isInteger(data.pid) ||
			data.pid <= 0 ||
			!Number.isInteger(data.created_at) ||
			!isString(data.agent) ||
			!isString(data.name) ||
			!isString(data.task)
		) {
			reject("malformed request", nonce);
			continue;
		}
		const expected = bridgeMac(bridge.secret, [
			"1",
			data.run_id,
			nonce,
			String(data.seq),
			String(data.pid),
			String(data.created_at),
			data.agent,
			data.name,
			data.task,
		]);
		if (!macMatches(expected, data.mac)) {
			reject("request authentication failed", nonce);
			continue;
		}
		if (data.run_id !== bridge.runId) {
			reject("request is bound to another native run", nonce);
			continue;
		}
		if (bridge.seen.has(nonce)) {
			reject("replayed request", nonce);
			continue;
		}
		bridge.seen.add(nonce);
		if (
			data.created_at > now + 5_000 ||
			now - data.created_at > BRIDGE_MAX_AGE_MS
		) {
			reject("stale request", nonce);
			continue;
		}
		if (readOwnership(data.pid, processRun.ownerToken, inspector) !== "owned") {
			reject("sender is not a verified process of this native run", nonce);
			continue;
		}
		if (!AGENT_NAME.test(data.agent)) {
			reject("invalid agent name", nonce);
			continue;
		}
		if (
			!data.name.trim() ||
			!data.task.trim() ||
			Buffer.byteLength(data.task, "utf8") > BRIDGE_MAX_TASK_BYTES
		) {
			reject("name and task must be non-empty and bounded", nonce);
			continue;
		}
		requests.push({
			nonce,
			pid: data.pid,
			createdAt: data.created_at,
			agent: data.agent,
			name: data.name.trim().slice(0, 80),
			task: data.task,
		});
	}
	return { requests, rejected };
}

/** Signed acknowledgement consumed by the waiting MCP server. */
export function writeBridgeResponse(
	bridge: NativeBridge,
	nonce: string,
	response: BridgeResponse,
): void {
	if (!NONCE.test(nonce)) return;
	const text = response.text.slice(0, 4000);
	const accepted = response.accepted ? "1" : "0";
	const path = join(bridge.responseDir, `${nonce}.json`);
	const temporary = `${path}.${randomBytes(4).toString("hex")}.tmp`;
	writeFileSync(
		temporary,
		`${JSON.stringify({
			version: 1,
			nonce,
			accepted: response.accepted,
			text,
			mac: bridgeMac(bridge.secret, ["1", nonce, accepted, text]),
		})}\n`,
		{ flag: "wx", mode: 0o600 },
	);
	renameSync(temporary, path);
}
