// This content is generated by AI (Kiro)
/**
 * Versioned native session markers, loadout integrity, and the exclusive
 * session lease that prevents two native processes from driving one native
 * conversation. A marker is not a Pi transcript: it records the identity and
 * the exact loadout a native session was created with, so resume can restore
 * it without consulting the current role definition.
 */
import {
	appendFileSync,
	existsSync,
	linkSync,
	readFileSync,
	renameSync,
	unlinkSync,
	writeFileSync,
} from "node:fs";
import { randomBytes } from "node:crypto";
import { dirname, join } from "node:path";
import { claudeTools, isNativeUuid } from "./claude.ts";
import { kiroMcpToolPatterns, kiroTools } from "./kiro.ts";
import { kiroMcpSelectionNames, type KiroMcpSelection } from "./kiro-mcp.ts";
import {
	confirmProcessExit,
	defaultProcessInspector,
	type ExitConfirmation,
	type ProcessInspector,
	type ProcessRun,
} from "./process-run.ts";
import { sha256, verifySkillSnapshot } from "./native-context.ts";
import { isPlainObject, isString, type JsonObject } from "./type-guards.ts";

export type NativeHarnessName = "claude" | "kiro";
export type NativeSessionMode = "standalone" | "lineage-only" | "fork";
export type NativeRunMode = "autonomous" | "interactive" | "persistent";

export interface NativeSkillRecord {
	name: string;
	filePath: string;
	sha256: string;
	bytes: number;
	/** Private content-addressed snapshot the delivered block points at. */
	snapshot?: { dir: string; sha256: string };
}

export interface NativeLineageRecord {
	mode: "lineage-only" | "fork";
	parentSessionFile: string;
	/** Fork only: the bounded inherited-context artifact. */
	context?: {
		file: string;
		sha256: string;
		bytes: number;
		messages: number;
		omittedMessages: number;
	};
}

export interface NativeWorktreeBinding {
	path: string;
	workspaceId: string;
	branch: string;
	baseSha: string;
	manifestFile?: string;
}

/**
 * Everything that bounds what a native session may do. Resume restores this
 * exactly; nothing in it may be widened by a later call.
 */
export interface NativeLoadout {
	tools: string;
	nativeTools: string[];
	model: string | null;
	thinking: string | null;
	promptMode: "append" | "replace" | null;
	identitySha256: string | null;
	mode: NativeRunMode;
	sessionMode: NativeSessionMode;
	skills: NativeSkillRecord[];
	/** Nested-spawn allowlist; null when the native child cannot delegate. */
	spawnAgents: string[] | null;
	/** Kiro-only personal MCP selection; contains no credential values. */
	kiroMcp?: KiroMcpSelection;
	kiroAgentName?: string;
	lineage?: NativeLineageRecord;
	worktree?: NativeWorktreeBinding;
}

export interface NativeSessionMarkerV1 {
	version: 1;
	type: "native_session";
	harness: NativeHarnessName;
	nativeSessionId: string | null;
	runId: string;
	name: string;
	agent?: string;
	cwd: string;
	createdAt: number;
	resume: "unsupported";
	loadout: JsonObject;
}

export interface NativeSessionMarker {
	version: 2;
	type: "native_session";
	harness: NativeHarnessName;
	/** Claude: parent-chosen UUID. Kiro: published by the owned hook. */
	nativeSessionId: string | null;
	/** Stable key: the run ID that created this native conversation. */
	sessionKey: string;
	runId: string;
	name: string;
	agent?: string;
	cwd: string;
	createdAt: number;
	/** Identity text file (0600) matching `loadout.identitySha256`. */
	identityFile?: string;
	loadout: NativeLoadout;
	loadoutSha256: string;
}

export type AnyNativeSessionMarker =
	| NativeSessionMarker
	| NativeSessionMarkerV1;

/** Deterministic JSON with sorted object keys for integrity hashing. */
export function canonicalJson(value: any): string {
	if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`;
	if (isPlainObject(value))
		return `{${Object.keys(value)
			.filter((key) => value[key] !== undefined)
			.sort()
			.map((key) => `${JSON.stringify(key)}:${canonicalJson(value[key])}`)
			.join(",")}}`;
	return JSON.stringify(value);
}

export function loadoutSha256(loadout: NativeLoadout): string {
	return sha256(canonicalJson(loadout));
}

export function readNativeSessionMarker(
	path: string,
): AnyNativeSessionMarker | null {
	try {
		const data = JSON.parse(readFileSync(path, "utf8"));
		if (
			data?.type !== "native_session" ||
			(data.harness !== "claude" && data.harness !== "kiro")
		)
			return null;
		if (data.version === 1 || data.version === 2) return data;
		return null;
	} catch {
		return null;
	}
}

/** Write a new marker exclusively; never overwrite an existing identity. */
export function writeNativeSessionMarker(
	path: string,
	marker: NativeSessionMarker,
): void {
	writeFileSync(path, `${JSON.stringify(marker, null, 2)}\n`, {
		flag: "wx",
		mode: 0o600,
	});
}

/**
 * Verify that a marker still describes exactly the loadout it was created
 * with. Returns a reason when resume must fail closed.
 */
export function verifyNativeSessionMarker(
	marker: AnyNativeSessionMarker,
	markerFile?: string,
): string | null {
	if (marker.version !== 2)
		return "it was created before native resume support (marker v1) and has no verifiable loadout";
	const loadout = marker.loadout;
	if (!isPlainObject(loadout) || !isString(marker.loadoutSha256))
		return "its loadout is missing";
	if (loadoutSha256(loadout) !== marker.loadoutSha256)
		return "its loadout does not match the recorded integrity hash";
	if (!isString(marker.cwd) || !marker.cwd.startsWith("/"))
		return "its working directory binding is missing";
	// The native grant must be exactly the strict mapping of the recorded
	// allowlist; anything else could widen what the resumed CLI may do.
	try {
		if (marker.harness === "claude" && loadout.kiroMcp !== undefined)
			return "its Claude loadout unexpectedly contains Kiro MCP servers";
		const mapped =
			marker.harness === "claude"
				? claudeTools(loadout.tools).split(",")
				: [
						...kiroTools(loadout.tools),
						...kiroMcpToolPatterns(
							loadout.kiroMcp ? kiroMcpSelectionNames(loadout.kiroMcp) : [],
						),
					];
		if (canonicalJson(mapped) !== canonicalJson(loadout.nativeTools))
			return "its native tools do not match the strict mapping of its recorded allowlist";
	} catch {
		return "its recorded tools allowlist is not strictly mappable";
	}
	if (marker.harness === "claude" && !isNativeUuid(marker.nativeSessionId))
		return "its native Claude session ID is missing or invalid";
	if (marker.harness === "kiro") {
		if (!isNativeUuid(marker.nativeSessionId))
			return "its native Kiro session ID was never published by the owned hook";
		if (!/^pi-subagent-[0-9a-f-]{36}$/.test(loadout.kiroAgentName ?? ""))
			return "its saved native Kiro agent name is missing or invalid";
	}
	// Resumed history references skill snapshots by path: they must still hold
	// exactly the bytes recorded at launch, never live or edited assets.
	// Snapshots live only in this session's own artifact directory.
	const snapshotRoot = markerFile
		? join(dirname(dirname(markerFile)), "native-skills")
		: undefined;
	for (const skill of loadout.skills ?? []) {
		if (!skill.snapshot) continue;
		if (snapshotRoot && dirname(skill.snapshot.dir) !== snapshotRoot)
			return `its skill "${skill.name}" snapshot is outside the session's artifact directory`;
		const reason = verifySkillSnapshot(
			skill.snapshot.dir,
			skill.snapshot.sha256,
		);
		if (reason) return `its skill "${skill.name}" ${reason}`;
	}
	if (loadout.identitySha256) {
		try {
			const identity = readFileSync(marker.identityFile ?? "", "utf8");
			if (sha256(identity) !== loadout.identitySha256)
				return "its role identity file changed after launch";
		} catch {
			return "its role identity file is missing";
		}
	}
	return null;
}

/**
 * The recorded role identity, read once and bound to the loadout hash: the
 * text a resume launches with is exactly the text verified, even if the file
 * is replaced after the marker check.
 */
export function readIdentityText(marker: NativeSessionMarker): string | null {
	if (!marker.loadout.identitySha256) return null;
	const identity = readFileSync(marker.identityFile ?? "", "utf8");
	if (sha256(identity) !== marker.loadout.identitySha256)
		throw new Error(
			"Native resume refused: the session's role identity file changed after verification.",
		);
	return identity;
}

/** Append-only record of every run that drove this native session. */
export function appendNativeRunRecord(
	markerFile: string,
	record: {
		runId: string;
		kind: "fresh" | "resume";
		event: "started" | "settled";
		outcome?: string;
		model?: string | null;
	},
): void {
	try {
		appendFileSync(
			`${markerFile}.runs.jsonl`,
			`${JSON.stringify({ ...record, at: new Date().toISOString() })}\n`,
			{ mode: 0o600 },
		);
	} catch {
		// Evidence only; the marker and lease remain authoritative.
	}
}

/**
 * A durable lease binding one resource (a native session, or a managed
 * worktree driven by a native run) to the single run driving it. It carries
 * the run's receipt path and owner token, so any later parent process can
 * check whether that run's owned processes are provably gone.
 */
export interface NativeSessionLease {
	version: 1;
	sessionKey: string;
	runId: string;
	receiptFile: string;
	ownerToken: string;
	createdAt: number;
	/**
	 * Worktree leases only: a reservation by the launching parent process.
	 * While that exact process lives, the lease stays held even after its
	 * current run exits, so a fallback handoff never exposes the worktree.
	 */
	parent?: LeaseParent;
}

/** Identity of a live parent process: PID plus kernel start time. */
export interface LeaseParent {
	pid: number;
	/** `/proc/<pid>/stat` start time, or `unverifiable` without /proc. */
	startTime: string;
	/** Random per-parent-process token proving handoff authority. */
	token: string;
}

// One token per parent process, surviving /reload module re-evaluation so an
// in-flight fallback sequence keeps its handoff authority.
const PARENT_TOKEN_KEY = Symbol.for("pi-subagents/native-lease-parent-token");
function parentToken(): string {
	// SAFETY: only this module writes this extension-private global symbol.
	const slots = globalThis as Record<symbol, string | undefined>;
	slots[PARENT_TOKEN_KEY] ??= randomBytes(16).toString("hex");
	return slots[PARENT_TOKEN_KEY]!;
}

function readStartTime(
	pid: number,
	inspector: ProcessInspector,
): string | null {
	if (!inspector.procRoot) return null;
	try {
		const stat = readFileSync(`${inspector.procRoot}/${pid}/stat`, "utf8");
		// Fields after the parenthesized command: state ppid ... starttime (22).
		return stat.slice(stat.lastIndexOf(")") + 2).split(" ")[19] ?? null;
	} catch {
		return null;
	}
}

/** This parent process's lease identity. */
export function currentLeaseParent(
	inspector: ProcessInspector = defaultProcessInspector,
): LeaseParent {
	return {
		pid: process.pid,
		startTime: readStartTime(process.pid, inspector) ?? "unverifiable",
		token: parentToken(),
	};
}

/**
 * `alive`: the same process (PID and start time) still runs. `gone`: the PID
 * is dead or reused. `unverifiable`: the PID lives but its identity cannot be
 * proven, which keeps the reservation held (fail closed).
 */
function leaseParentState(
	parent: LeaseParent,
	inspector: ProcessInspector,
): "alive" | "gone" | "unverifiable" {
	if (!inspector.isAlive(parent.pid)) return "gone";
	if (parent.startTime === "unverifiable" || !inspector.procRoot)
		return "unverifiable";
	const startTime = readStartTime(parent.pid, inspector);
	if (startTime === null)
		return inspector.isAlive(parent.pid) ? "unverifiable" : "gone";
	return startTime === parent.startTime ? "alive" : "gone";
}

export function nativeLeaseFile(markerFile: string): string {
	return `${markerFile}.lease`;
}

/** Durable worktree lease beside the worktree's ownership manifest. */
export function nativeWorktreeLeaseFile(manifestFile: string): string {
	return `${manifestFile}.native-lease`;
}

function readLease(path: string): NativeSessionLease | null {
	try {
		const data = JSON.parse(readFileSync(path, "utf8"));
		return data?.version === 1 &&
			isString(data.runId) &&
			isString(data.receiptFile) &&
			isString(data.ownerToken)
			? data
			: null;
	} catch {
		return null;
	}
}

export type LeaseInspection =
	| { kind: "free" }
	| { kind: "held"; lease: NativeSessionLease; reason: string }
	| {
			kind: "stale";
			lease: NativeSessionLease;
			exit: Extract<ExitConfirmation, { kind: "confirmed" }>;
	  }
	| { kind: "invalid"; reason: string };

/**
 * A lease is stale only when its run's exit is confirmed, including every
 * owned descendant; an unconfirmed exit, or an unreadable lease, keeps the
 * resource held.
 */
export function inspectRunLease(
	path: string,
	inspector: ProcessInspector = defaultProcessInspector,
): LeaseInspection {
	let raw: string;
	try {
		raw = readFileSync(path, "utf8");
	} catch (error: any) {
		if (error?.code === "ENOENT") return { kind: "free" };
		return { kind: "invalid", reason: String(error?.message ?? error) };
	}
	const lease = readLease(path);
	if (!lease)
		return {
			kind: "invalid",
			reason: `unreadable lease ${path} (${raw.length} bytes); inspect it manually`,
		};
	const run: ProcessRun = {
		id: lease.runId,
		receiptFile: lease.receiptFile,
		ownerToken: lease.ownerToken,
	};
	const exit = confirmProcessExit(run, inspector);
	if (exit.kind !== "confirmed")
		return {
			kind: "held",
			lease,
			reason: `run ${lease.runId} may still be driving it (${exit.reason})`,
		};
	if (lease.parent) {
		const parent = leaseParentState(lease.parent, inspector);
		if (parent !== "gone")
			return {
				kind: "held",
				lease,
				reason: `parent process ${lease.parent.pid} still reserves it${parent === "unverifiable" ? " (its identity cannot be verified)" : ""} between native runs`,
			};
	}
	return { kind: "stale", lease, exit };
}

export function inspectNativeSessionLease(
	markerFile: string,
	inspector: ProcessInspector = defaultProcessInspector,
): LeaseInspection {
	return inspectRunLease(nativeLeaseFile(markerFile), inspector);
}

/**
 * Acquire the lease at `path` for `run`. A stale lease (confirmed exit) is
 * reclaimed with an atomic rename, re-verified after the rename so a
 * concurrently created live lease is restored instead of stolen.
 */
export function acquireRunLease(
	path: string,
	key: string,
	run: ProcessRun,
	label: string,
	inspector: ProcessInspector = defaultProcessInspector,
	parent?: LeaseParent,
): void {
	const inspection = inspectRunLease(path, inspector);
	if (inspection.kind === "held")
		throw new Error(`${label} is in use: ${inspection.reason}.`);
	if (inspection.kind === "invalid")
		throw new Error(`${label} lease is invalid: ${inspection.reason}.`);
	if (inspection.kind === "stale") {
		const moved = `${path}.stale-${randomBytes(6).toString("hex")}`;
		renameSync(path, moved);
		const reclaimed = readLease(moved);
		if (reclaimed?.runId !== inspection.lease.runId) {
			try {
				linkSync(moved, path);
				unlinkSync(moved);
			} catch {
				// Another lease now exists; the exclusive create below fails.
			}
			throw new Error(`${label} lease changed while it was being reclaimed.`);
		}
		try {
			unlinkSync(moved);
		} catch {
			// The runs log keeps the history; a leftover stale copy is harmless.
		}
	}
	const lease: NativeSessionLease = {
		version: 1,
		sessionKey: key,
		runId: run.id,
		receiptFile: run.receiptFile,
		ownerToken: run.ownerToken,
		createdAt: Date.now(),
	};
	if (parent) lease.parent = parent;
	writeFileSync(path, `${JSON.stringify(lease)}\n`, {
		flag: "wx",
		mode: 0o600,
	});
}

/**
 * Atomically hand a parent-reserved lease from one run to the next: the lease
 * file is replaced by rename, so it never disappears between runs. Refused
 * unless the current lease names `fromRunId` under this parent's reservation.
 */
export function handoffRunLease(
	path: string,
	fromRunId: string,
	run: ProcessRun,
	parent: LeaseParent,
): void {
	const current = readLease(path);
	if (current?.runId !== fromRunId || current.parent?.token !== parent.token)
		throw new Error(
			`Native worktree lease handoff refused: the lease no longer names run ${fromRunId} under this parent's reservation.`,
		);
	const next: NativeSessionLease = {
		...current,
		runId: run.id,
		receiptFile: run.receiptFile,
		ownerToken: run.ownerToken,
		createdAt: Date.now(),
		parent,
	};
	const temporary = `${path}.handoff-${randomBytes(6).toString("hex")}`;
	writeFileSync(temporary, `${JSON.stringify(next)}\n`, {
		flag: "wx",
		mode: 0o600,
	});
	renameSync(temporary, path);
}

export function acquireNativeSessionLease(
	markerFile: string,
	sessionKey: string,
	run: ProcessRun,
	inspector: ProcessInspector = defaultProcessInspector,
): void {
	acquireRunLease(
		nativeLeaseFile(markerFile),
		sessionKey,
		run,
		"Native session",
		inspector,
	);
}

/** Release only this run's lease, and only after its exit is confirmed. */
export function releaseRunLease(path: string, runId: string): void {
	if (readLease(path)?.runId !== runId) return;
	try {
		unlinkSync(path);
	} catch {
		// A missing lease is already released.
	}
}

/**
 * Final settlement of a parent-reserved lease: remove it only when this
 * parent holds the reservation and the run it names is provably gone.
 * Returns whether the reservation is now released (or was absent).
 */
export function releaseReservedLease(
	path: string,
	inspector: ProcessInspector = defaultProcessInspector,
): boolean {
	const lease = readLease(path);
	if (!lease) return !existsSync(path);
	if (lease.parent?.token !== parentToken()) return false;
	const exit = confirmProcessExit(
		{
			id: lease.runId,
			receiptFile: lease.receiptFile,
			ownerToken: lease.ownerToken,
		},
		inspector,
	);
	if (exit.kind !== "confirmed") return false;
	releaseRunLease(path, lease.runId);
	return true;
}

export function releaseNativeSessionLease(
	markerFile: string,
	runId: string,
): void {
	releaseRunLease(nativeLeaseFile(markerFile), runId);
}
