// This content is generated by AI (Kiro)
/**
 * Durable process receipts and verified process ownership for native harness
 * children, independent of the terminal and agent harness.
 *
 * Receipt/trap wrapper ported from zhengfran/pi-interactive-subagents (MIT,
 * Copyright (c) 2026 HazAT and contributors),
 * `pi-extension/subagents/process-run.ts`. Owner-token identity, verified
 * signalling, owned-process scans, and the start-cancel marker are additions.
 */
import { randomUUID } from "node:crypto";
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { shellQuote } from "./terminal.ts";

/** Environment variable carrying a run's unguessable ownership token. */
export const OWNER_ENV = "PI_NATIVE_RUN_OWNER";

export interface ProcessRun {
	id: string;
	receiptFile: string;
	/**
	 * Unguessable per-run token. The wrapper re-executes itself with it in its
	 * exec-time environment, so every owned process (wrapper and inheriting
	 * descendants) is identifiable independently of its PID.
	 */
	ownerToken: string;
}

export interface ProcessReceipt {
	version: 1;
	runId: string;
	owner: string;
	/** PID of the dedicated, non-interactive launch wrapper (not a shell prompt). */
	pid: number;
	exitCode?: number;
}

export function createProcessRun(id: string, receiptFile: string): ProcessRun {
	return { id, receiptFile, ownerToken: randomUUID() };
}

/** Harness hooks publish diagnostics here even when the process exits zero. */
export function errorReceiptFile(run: ProcessRun): string {
	return `${run.receiptFile}.error`;
}

/** A wrapper that starts after this marker exists exits before the native CLI. */
export function cancelMarkerFile(run: ProcessRun): string {
	return `${run.receiptFile}.cancel`;
}

export function writeCancelMarker(run: ProcessRun): void {
	try {
		writeFileSync(cancelMarkerFile(run), `${Date.now()}\n`, { mode: 0o600 });
	} catch {
		// A missing marker leaves the late-start window open; callers still
		// require receipt or owned-process evidence before confirming exit.
	}
}

export function readProcessReceipt(run: ProcessRun): ProcessReceipt | null {
	try {
		const data = JSON.parse(readFileSync(run.receiptFile, "utf8"));
		if (
			data?.version !== 1 ||
			data.runId !== run.id ||
			data.owner !== run.ownerToken ||
			!Number.isInteger(data.pid) ||
			data.pid <= 0 ||
			(data.exitCode !== undefined &&
				(!Number.isInteger(data.exitCode) ||
					data.exitCode < 0 ||
					data.exitCode > 255))
		) {
			return null;
		}
		return data;
	} catch {
		return null;
	}
}

export function isProcessAlive(pid: number): boolean {
	try {
		process.kill(pid, 0);
		return true;
	} catch (error) {
		// SAFETY: process.kill throws Node errno errors carrying a `code`.
		return (error as NodeJS.ErrnoException).code === "EPERM";
	}
}

/** Platform seams for ownership checks; Linux reads `/proc`. */
export interface ProcessInspector {
	/** `null` when this platform cannot read process environments. */
	procRoot: string | null;
	uid: number | null;
	isAlive(pid: number): boolean;
	kill(pid: number, signal: NodeJS.Signals): void;
}

export const defaultProcessInspector: ProcessInspector = {
	procRoot: process.platform === "linux" ? "/proc" : null,
	uid: process.getuid?.() ?? null,
	isAlive: isProcessAlive,
	kill: (pid, signal) => process.kill(pid, signal),
};

/**
 * `owned`: the PID's exec-time environment carries this run's token.
 * `not-owned`: the PID is gone, or belongs to a process without the token
 * (for example a reused PID). `unverifiable`: the PID exists but this
 * platform or permission state cannot establish ownership.
 */
export type Ownership = "owned" | "not-owned" | "unverifiable";

function errnoCode(error: any): string | undefined {
	return error?.code;
}

function environCarries(environ: string, token: string): boolean {
	return environ.split("\0").includes(`${OWNER_ENV}=${token}`);
}

export function readOwnership(
	pid: number,
	token: string,
	inspector: ProcessInspector = defaultProcessInspector,
): Ownership {
	if (!inspector.procRoot) {
		return inspector.isAlive(pid) ? "unverifiable" : "not-owned";
	}
	try {
		const environ = readFileSync(
			`${inspector.procRoot}/${pid}/environ`,
			"utf8",
		);
		return environCarries(environ, token) ? "owned" : "not-owned";
	} catch (error) {
		const code = errnoCode(error);
		if (code === "ENOENT" || code === "ESRCH") return "not-owned";
		try {
			// Another user's process cannot carry this run's environment.
			const owner = statSync(`${inspector.procRoot}/${pid}`).uid;
			return inspector.uid != null && owner !== inspector.uid
				? "not-owned"
				: "unverifiable";
		} catch {
			return inspector.isAlive(pid) ? "unverifiable" : "not-owned";
		}
	}
}

export type OwnedProcessScan =
	| {
			kind: "complete";
			pids: number[];
			/** Same-user PIDs whose environment is unreadable (bounded sample). */
			unreadable: number[];
			unreadableCount: number;
	  }
	| { kind: "unavailable"; reason: string };

const UNREADABLE_SAMPLE = 5;

/**
 * Enumerate every process whose exec-time environment carries this run's
 * token. `complete` with no PIDs is positive evidence that no readable owned
 * process exists. Following the worktree cleanup process-visibility policy
 * (ADR-0011), an individually unreadable same-user process (for example a
 * non-dumpable keyring or sshd) is disclosed as incomplete coverage rather
 * than blocking; such processes are never signalled. Failed enumeration and
 * platforms without `/proc` are unavailable.
 */
export function scanOwnedProcesses(
	run: ProcessRun,
	inspector: ProcessInspector = defaultProcessInspector,
): OwnedProcessScan {
	if (!inspector.procRoot)
		return {
			kind: "unavailable",
			reason: `process ownership cannot be verified on ${process.platform}`,
		};
	let entries: string[];
	try {
		entries = readdirSync(inspector.procRoot);
	} catch (error) {
		return {
			kind: "unavailable",
			reason: `process enumeration failed: ${error instanceof Error ? error.message : String(error)}`,
		};
	}
	const pids: number[] = [];
	const unreadable: number[] = [];
	let unreadableCount = 0;
	for (const entry of entries) {
		if (!/^\d+$/.test(entry)) continue;
		const pid = Number.parseInt(entry, 10);
		const ownership = readOwnership(pid, run.ownerToken, inspector);
		if (ownership === "owned") pids.push(pid);
		else if (ownership === "unverifiable") {
			unreadableCount++;
			if (unreadable.length < UNREADABLE_SAMPLE) unreadable.push(pid);
		}
	}
	return { kind: "complete", pids, unreadable, unreadableCount };
}

/** Receipt-derived state; liveness never trusts a PID without ownership. */
export type ProcessRunState =
	| { kind: "not-started" }
	| { kind: "running"; pid: number; verified: boolean }
	| { kind: "exited"; pid: number; exitCode: number }
	| { kind: "gone"; pid: number };

export function readProcessRunState(
	run: ProcessRun,
	inspector: ProcessInspector = defaultProcessInspector,
): ProcessRunState {
	const receipt = readProcessReceipt(run);
	if (!receipt) return { kind: "not-started" };
	if (receipt.exitCode !== undefined)
		return { kind: "exited", pid: receipt.pid, exitCode: receipt.exitCode };
	const ownership = readOwnership(receipt.pid, run.ownerToken, inspector);
	if (ownership === "not-owned") return { kind: "gone", pid: receipt.pid };
	return {
		kind: "running",
		pid: receipt.pid,
		verified: ownership === "owned",
	};
}

export function isProcessRunLive(
	run: ProcessRun | undefined,
	inspector: ProcessInspector = defaultProcessInspector,
): boolean {
	return !!run && readProcessRunState(run, inspector).kind === "running";
}

/**
 * Persist startup and process exit atomically, even for failed cd/CLI startup.
 * The wrapper first re-executes itself with the run's owner token in its
 * exec-time environment (same PID), refuses to start without it, and refuses
 * to launch the native CLI once the parent wrote the cancel marker. It reads
 * commands from its script file, never from terminal stdin.
 */
export function supervisedCommand(command: string, run: ProcessRun): string {
	const token = shellQuote(run.ownerToken);
	const prefix = `${JSON.stringify({ version: 1, runId: run.id, owner: run.ownerToken }).slice(0, -1)},`;
	return [
		`if [ "\${${OWNER_ENV}-}" != ${token} ] && [ -f "$0" ]; then exec env ${OWNER_ENV}=${token} bash "$0"; fi`,
		`[ "\${${OWNER_ENV}-}" = ${token} ] || exit 125`,
		"__pi_write_receipt() (",
		"  umask 077",
		`  printf '%s"pid":%s%s}\\n' ${shellQuote(prefix)} "$$" "$1" > ${shellQuote(`${run.receiptFile}.tmp`)} &&`,
		`    mv -f -- ${shellQuote(`${run.receiptFile}.tmp`)} ${shellQuote(run.receiptFile)}`,
		")",
		`trap '__pi_exit=$?; __pi_write_receipt ",\\"exitCode\\":$__pi_exit"; exit "$__pi_exit"' EXIT`,
		// Without explicit handlers Bash runs the EXIT trap with the previous
		// status on a fatal signal, which would record a terminated run as 0.
		"trap 'exit 129' HUP",
		"trap 'exit 130' INT",
		"trap 'exit 143' TERM",
		'__pi_write_receipt "" || exit 125',
		// Checked after the start receipt: either the parent observes this
		// receipt, or this wrapper observes the parent's cancel marker.
		`[ -e ${shellQuote(cancelMarkerFile(run))} ] && exit 125`,
		command,
	].join("\n");
}

export type TerminationResult =
	| { kind: "signalled"; pids: number[]; group: boolean }
	| { kind: "nothing-owned" }
	| { kind: "unverifiable"; reason: string };

/**
 * Signal only processes proven to belong to this run. The wrapper's process
 * group is signalled only after its PID is verified as owned and it leads that
 * group; every other target is an individually verified token holder. When
 * ownership cannot be established, nothing is signalled.
 */
export function terminateProcessRun(
	run: ProcessRun,
	signal: NodeJS.Signals = "SIGTERM",
	inspector: ProcessInspector = defaultProcessInspector,
): TerminationResult {
	const receipt = readProcessReceipt(run);
	const wrapper =
		receipt && receipt.exitCode === undefined
			? readOwnership(receipt.pid, run.ownerToken, inspector)
			: "not-owned";
	const scan = scanOwnedProcesses(run, inspector);
	if (scan.kind === "unavailable" && wrapper !== "owned")
		return { kind: "unverifiable", reason: scan.reason };
	const targets = new Set(scan.kind === "complete" ? scan.pids : []);
	let group = false;
	if (receipt && wrapper === "owned") {
		targets.add(receipt.pid);
		if (readProcessGroup(receipt.pid, inspector) === receipt.pid) {
			try {
				inspector.kill(-receipt.pid, signal);
				group = true;
			} catch {
				// Fall back to individually verified targets below.
			}
		}
	}
	if (targets.size === 0 && !group) return { kind: "nothing-owned" };
	const signalled: number[] = [];
	for (const pid of targets) {
		// Re-verify immediately before signalling each individual PID.
		if (readOwnership(pid, run.ownerToken, inspector) !== "owned") continue;
		try {
			inspector.kill(pid, signal);
			signalled.push(pid);
		} catch {
			// The process may have exited after verification.
		}
	}
	return { kind: "signalled", pids: signalled, group };
}

function readProcessGroup(
	pid: number,
	inspector: ProcessInspector,
): number | null {
	if (!inspector.procRoot) return null;
	try {
		const stat = readFileSync(`${inspector.procRoot}/${pid}/stat`, "utf8");
		// Fields after the parenthesized command: state ppid pgrp ...
		const fields = stat.slice(stat.lastIndexOf(")") + 2).split(" ");
		const pgrp = Number.parseInt(fields[2] ?? "", 10);
		return Number.isInteger(pgrp) && pgrp > 0 ? pgrp : null;
	} catch {
		return null;
	}
}

/**
 * `confirmed`: the wrapper recorded its exit, or a complete owned-process scan
 * found no process and the cancel marker prevents a late start.
 * `unconfirmed`: an owned process may still be running.
 */
export type ExitConfirmation =
	| {
			kind: "confirmed";
			/** `receipt`: the wrapper recorded its exit; `scan`: no owned process found. */
			evidence: "receipt" | "scan";
			exitCode: number | null;
			/** Owned descendants still running after the wrapper exited. */
			lingering: number[];
			/** Same-user processes the scan could not inspect (count). */
			unreadableCount: number;
	  }
	| { kind: "unconfirmed"; reason: string };

export function confirmProcessExit(
	run: ProcessRun,
	inspector: ProcessInspector = defaultProcessInspector,
): ExitConfirmation {
	const state = readProcessRunState(run, inspector);
	if (state.kind === "exited") {
		const scan = scanOwnedProcesses(run, inspector);
		return {
			kind: "confirmed",
			evidence: "receipt",
			exitCode: state.exitCode,
			lingering: scan.kind === "complete" ? scan.pids : [],
			unreadableCount: scan.kind === "complete" ? scan.unreadableCount : 0,
		};
	}
	if (state.kind === "running")
		return {
			kind: "unconfirmed",
			reason: `launch wrapper ${state.pid} is still running${state.verified ? "" : " (ownership unverifiable)"}`,
		};
	const scan = scanOwnedProcesses(run, inspector);
	if (scan.kind === "unavailable")
		return { kind: "unconfirmed", reason: scan.reason };
	if (scan.pids.length > 0)
		return {
			kind: "unconfirmed",
			reason: `owned process(es) ${scan.pids.join(", ")} still running without an exit receipt`,
		};
	if (state.kind === "not-started") {
		// A wrapper between exec and its start receipt would see the marker.
		writeCancelMarker(run);
		const recheck = readProcessRunState(run, inspector);
		if (recheck.kind !== "not-started")
			return confirmProcessExit(run, inspector);
	}
	return {
		kind: "confirmed",
		evidence: "scan",
		exitCode: null,
		lingering: [],
		unreadableCount: scan.unreadableCount,
	};
}
