// This content is generated by AI (Kiro)
/**
 * Integration tests for native harness turn delivery through real Herdr panes.
 *
 * The offline `claude` and `kiro-cli` fixture stand-ins run in a pane of the
 * dedicated test workspace. Follow-ups and simulated human input travel over
 * real `herdr pane run`, so this covers the actual typed-input path that unit
 * tests fake. No model is contacted.
 *
 * Run `npm run test:integration` from inside herdr.
 */
import { describe, it, beforeEach, afterEach } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
	cleanupTestEnv,
	createTestEnv,
	createTrackedSurface,
	getAvailableBackends,
	restoreBackend,
	runInPane,
	setBackend,
	shellQuote,
	waitForPaneReady,
	type TestEnv,
} from "./harness.ts";
import { launchNativeSubagent } from "../../pi-extension/subagents/launch.ts";
import {
	createNativeHarnessOperations,
	planNativeLaunch,
	resolveNativeLaunchSpec,
} from "../../pi-extension/subagents/native-harness.ts";
import { enqueueNativeTurn } from "../../pi-extension/subagents/native-turns.ts";
import { terminateProcessRun } from "../../pi-extension/subagents/process-run.ts";
import { inspectPane } from "../../pi-extension/subagents/terminal.ts";
import * as subagentsModule from "../../pi-extension/subagents/index.ts";

const testApi = subagentsModule.__test__;
const FIXTURE_BIN = join(
	dirname(fileURLToPath(import.meta.url)),
	"..",
	"fixtures",
	"native-bin",
);
/**
 * Parent-side availability and profile checks run the offline fixtures too,
 * never a Claude or Kiro CLI that happens to be installed on the host.
 */
const fixtureOperations = createNativeHarnessOperations((file, args, options) =>
	execFileSync(file, args, {
		encoding: "utf8",
		timeout: options.timeout,
		stdio: "pipe",
		env: { ...process.env, PATH: `${FIXTURE_BIN}:${process.env.PATH}` },
	}),
);
const backends = getAvailableBackends();

if (backends.length === 0)
	console.log(
		"⚠️  herdr is unavailable — skipping native harness integration tests",
	);

async function waitUntil(check: () => boolean, timeoutMs = 20_000) {
	const deadline = Date.now() + timeoutMs;
	while (!check()) {
		if (Date.now() > deadline) throw new Error("timed out waiting");
		await new Promise((resolve) => setTimeout(resolve, 50));
	}
}

for (const backend of backends) {
	describe(`native harness over real herdr [${backend}]`, {
		timeout: 90_000,
	}, () => {
		let previous: string | undefined;
		let env: TestEnv;

		beforeEach(() => {
			previous = setBackend(backend);
			env = createTestEnv(backend);
		});

		afterEach(() => {
			cleanupTestEnv(env);
			restoreBackend(previous);
		});

		async function launch(
			harness: "claude" | "kiro",
			role: { autoExit?: boolean; tools: string },
		) {
			const project = join(env.dir, `${harness}-project`);
			const sessionDir = join(env.dir, `${harness}-sessions`);
			mkdirSync(project, { recursive: true });
			mkdirSync(sessionDir, { recursive: true });
			const log = join(env.dir, `${harness}-fixture.json`);
			const surface = createTrackedSurface(env, `native-${harness}`);
			await waitForPaneReady(surface);
			// The launch script inherits the pane shell's exported environment.
			runInPane(
				surface,
				`export PATH=${shellQuote(FIXTURE_BIN)}:"$PATH" FAKE_NATIVE_LOG=${shellQuote(log)}`,
			);
			const spec = resolveNativeLaunchSpec({
				name: `${harness}-integ`,
				cli: harness,
				tools: role.tools,
				autoExit: role.autoExit,
				body: "You are an integration fixture.",
			});
			const running = await launchNativeSubagent(
				{
					kind: "native",
					name: `native-${harness}`,
					task: "Integration task",
					surface,
					parent: {
						cwd: project,
						sessionFile: join(sessionDir, "parent.jsonl"),
						sessionId: "integration-parent",
						sessionDir,
					},
					behavior: { interactive: spec.mode === "interactive" },
					plan: planNativeLaunch(spec, {
						task: "Integration task",
						installedSkills: () => [],
					}),
					cwd: project,
				},
				undefined,
				fixtureOperations,
			);
			return { running, surface, log };
		}

		const deps = {
			send: runInPane,
			inspectPane,
			terminate: (run: Parameters<typeof terminateProcessRun>[0]) =>
				terminateProcessRun(run),
			intervalMs: 100,
			terminationGraceMs: 5_000,
		};

		it("types a queued Claude follow-up through herdr only after the verified Stop", async () => {
			const { running, log } = await launch("claude", {
				autoExit: true,
				tools: "read,bash",
			});
			const run = running.native;
			const queued = enqueueNativeTurn(
				run.driver,
				{
					id: "integration-follow-up",
					kind: "follow-up",
					text: "Second\nstep",
				},
				{ followUpAckTimeoutMs: 30_000, label: "Claude Code" },
			);
			assert.equal(queued.ok, true);
			const result = await testApi.watchNativeSubagent(
				// SAFETY: the native launch result carries every RunningSubagent
				// member the native watcher reads.
				running as Parameters<typeof testApi.watchNativeSubagent>[0],
				new AbortController().signal,
				deps,
			);
			assert.equal(result.exitCode, 0, result.summary);
			assert.equal(result.summary, "Claude follow-up result 2");
			assert.deepEqual(
				result.native?.turns?.map((turn) => `${turn.kind}=${turn.outcome}`),
				["initial=completed", "follow-up=completed"],
			);
			const inputs = readFileSync(`${log}.events`, "utf8")
				.trim()
				.split("\n")
				.map((line) => JSON.parse(line).input);
			assert.match(
				inputs[0],
				/^\[pi-subagent-turn:[0-9a-f-]{36}\] Second step$/,
			);
			assert.equal(inputs.at(-1), "/exit");
		});

		it("keeps an interactive Kiro session open for human turns until the human quits", async () => {
			const { running, surface, log } = await launch("kiro", { tools: "read" });
			const run = running.native;
			const watching = testApi.watchNativeSubagent(
				// SAFETY: see the Claude case above.
				running as Parameters<typeof testApi.watchNativeSubagent>[0],
				new AbortController().signal,
				deps,
			);
			await waitUntil(() => run.driver.turns[0].outcome === "completed");
			runInPane(surface, "HUMAN what next?");
			await waitUntil(() => run.driver.lastState?.untrackedTurns === 1);
			const queued = enqueueNativeTurn(
				run.driver,
				{ id: "after-human", kind: "follow-up", text: "Wrap up" },
				{ followUpAckTimeoutMs: 30_000, label: "Kiro" },
			);
			assert.equal(queued.ok, true);
			await waitUntil(() => run.driver.turns[1]?.outcome === "completed");
			runInPane(surface, "/quit"); // the human ends the session
			const result = await watching;
			assert.equal(result.exitCode, 0, result.summary);
			assert.equal(result.native?.humanTurns, 1);
			assert.equal(result.native?.lastHumanSummary, "Human-driven answer");
			assert.equal(result.summary, "Kiro follow-up result 2");
			const inputs = readFileSync(`${log}.events`, "utf8")
				.trim()
				.split("\n")
				.map((line) => JSON.parse(line).input);
			assert.deepEqual(inputs[0], "HUMAN what next?");
			assert.equal(
				inputs.filter((input) => input === "/quit").length,
				1,
				"the parent never typed its own exit into an interactive session",
			);
		});
	});
}
